### ISSUE TITLE
Local Discovery is not working on Android 12

### ISSUE THREAD

**Issue by eduardbeutel** [syncthing/syncthing-android#1862] opened 2022-11-22 21:25 UTC
FYI: For anyone looking for a solution to this see the "How I circumvented the problem" section at the end.

### Problem description

I have a local network of four devices, one windows pc and 3 android devices: phone1, phone2, tablet.
Phone 2 is the latest addition with Android 12 and I tried connecting it to the pc via local discovery and it doesn't work.
After adding the pc on phone 2 via QR code I never get the "add device" message on the pc and the pc is shown as Disconnected on phone 2.

### What I tested trying to isolate the problem

1. I tested this with the other android devices by re-introducing them to the pc and they don't have any problem. This means the windows firewall doesn't create any problems.

2. I tested multicast between phone 2 and the pc and messages are received both ways.

### Version Information of the device where **Local Discovery doesn't work**: phone2

    App Version: 1.22.1.1
    Syncthing Version: v1.22.2-dev.1.g15c0afec ( from Fdroid )
    Android Version: Android 12 ( LineageOS 19 )
    Settings Disabled: Enable NAT Transversal, Global Discovery, Enable Relaying
    Settings Enabled: Local Discovery

### Version Information of devices where **Local Discovery does work**: phone1, tablet

    App Version: 1.22.1.1
    Syncthing Version: v1.22.2-dev.1.g15c0afec ( from Fdroid )
    Android Version: Android 10 ( Custom ROM )
    Settings Disabled: Enable NAT Transversal, Global Discovery, Enable Relaying
    Settings Enabled: Local Discovery

    App Version: 1.22.1.1
    Syncthing Version: v1.22.2-dev.1.g15c0afec ( from Fdroid )
    Android Version: Android 7.1.2 ( Custom ROM )
    Settings Disabled: Enable NAT Transversal, Global Discovery, Enable Relaying
    Settings Enabled: Local Discovery

### How I circumvented the problem

The solution is to manually add the Android 12 device and then manually set the IP of the Android 12 device on the "other" device.

The same problem and the solution is discussed here: 
https://forum.syncthing.net/t/i-am-not-working-syncthing-since-i-installed-android-12-on-my-pixel-3a/18997

**Comment by imsodin** [comment] 2022-11-22 22:05
Duplicate of https://github.com/syncthing/syncthing-android/issues/1628

**Closed by imsodin** 2022-11-22 22:05 UTC
