### ISSUE TITLE
Run only when charging, not respected with battery "not optimized"

### ISSUE THREAD

**Issue by bambam82** [syncthing/syncthing-android#977] opened 2017-10-23 16:01 UTC
The option "Run only when charging" isn't respected on :

- Android 8 (latest patch)
- Nexus 5x
- Syncthing-android version 0.9.17 
- Syncthing version 0.14.39

Now it's running continuously.

If I optimize the battery for Syncthing it will not run unless I disable the option "Run only when charging".

**Comment by Nutomic** [comment] 2017-10-23 18:30
You are probably describing [this problem](https://forum.syncthing.net/t/charging-only-run-condition-is-no-longer-working-as-expected/10772/7). It will be fixed in the next release.

**Comment by Catfriend1** [comment] 2018-04-13 12:50
@bambam82 Is this issue still present in the current release? I cannot reproduce it on my device. If so, please post a reproducer and tell me how much percent your battery is charged when the syncthing active/inactive status transitions.

**Closed** 2018-04-22 13:25 UTC
