### ISSUE TITLE
Unnecessary removals und addition of files

### ISSUE THREAD

**Issue by r4taw2mg** [syncthing/syncthing-android#860] opened 2017-03-14 16:39 UTC
Integrating a Android client into my working network of two laptop resulted in constant removal of files that got added later on as modified by the same device. On the device, the file were not removed.

This files have _not_ been changed or touched (to my knowledge). Though I use BoxCryptor to encrypt the files and I am synching the encrypted versions (*.bc).

This issue prevents access to certain files from time to time and also generates _a_ _lot_ of traffic (1 GB from the phone, not counting the traffic between the Windows PCs).

### Version Information

    App Version: 0.9.6
    Syncthing Version: v0.14.24 on Win10
    Android Version: Samsung Galaxy 3 with Android 4.2.2 and CM 10.1.3.

**Comment by AudriusButkevicius** [comment] 2017-03-14 16:47
Have you tried things without boxcryptor?I suspect it's rewriting files which cause them to be deleted and recreated.

**Comment by r4taw2mg** [comment] 2017-03-14 16:57
O man! Think about that!

I actually have two more folders in syncon the same configuration. The 
other two folderare not encrypted and I have not seen anystrange 
behaviour. That might just be the reason.

So I have to contact the BC folks.

What exactly is monitored by ST to find out if a file has been changed?

And how does it find removed files?

**Comment by AudriusButkevicius** [comment] 2017-03-14 17:08
I think boxcryptor just rewrites the files every now and then.

Files are missing if they do not exist or cannot be read,and modified if modification timestamp changes (which implies content changes).

Your assumption that you can just run the two together is fairly naive as both do somewhat complex things behind the scenes.

I am closing this as it's clearly not a bug.

**Closed by AudriusButkevicius** 2017-03-14 17:08 UTC

**Comment by r4taw2mg** [comment] 2017-03-14 19:09
"fairly naive" I call arrogant!

Google Drive works nicely with files encrypted by BoxCryptor. So why shouldn't ST?

**Comment by AudriusButkevicius** [comment] 2017-03-14 19:26
Conceptually they are the same, yet Google Drive is probably implemented in Java that has good clean access to the filesystem which works around all the quirks that we see when implementing syncthing in Go.
Also, Google Drive has a central source of truth, syncthing is decentralized making things harder, but that's not related to this problem.
