### ISSUE TITLE
List of ignored devices

### ISSUE THREAD

**Issue by unhammer** [syncthing/syncthing-android#938] opened 2017-08-21 12:29 UTC
###    what happened,

I swiped away an "Unknown device [ID] wants to connect" and then the next day it was there again.

###    what you expected to happen instead, and

I would be added to a list of "ignored devices" under the "Devices" tab/page, which I could later add if I felt like it

###    any steps to reproduce the problem.

Add a new device to network, don't add it to your phone.

### Version Information

    App Version: 0.9.12
    Syncthing Version: v0.14.32
    Android Version: Android 4.3 on Sony LT25i

**Comment by Catfriend1** [comment] 2018-05-08 11:43
This would help implementing it:
https://docs.syncthing.net/users/config.html

**Comment by unhammer** [comment] 2018-05-08 11:50
it's not possible to edit that directly without root, right?

**Comment by Catfriend1** [comment] 2018-05-08 11:52
As a workaround: export config, edit it on intsdcard, import config.

**Comment by Catfriend1** [comment] 2018-05-09 13:18
@AudriusButkevicius I would try to build an UI for this... any suggestions how this can be implemented?
Perhaps using mConfig root to determine the ignoredDevices and make a link button beside the "+" (add device) on the devices tab in main UI. Pressing the link button will launch a new activity stating "ignored device list - tap to remove".

**Comment by AudriusButkevicius** [comment] 2018-05-09 18:04
Well ignoring is done by adding stuff into the config, how you handle removal from ignoring is up to you. Currently there is no way to do that in syncthings UI, so I don't have a solution.

**Comment by Catfriend1** [comment] 2018-07-18 06:46
The original bug report @unhammer provided in the first post is a duplicate of the already fixed issue #679.
I'm putting a "reset ignored devices and folder" button on my todo list as this is currently not requested by many users and syncthing web UI doesn't provide any functionality to reset the ignored devices/folders list.

**Comment by Catfriend1** [comment] 2018-07-18 08:20
@unhammer Solution is on it's way ...

**Closed** 2018-07-18 17:11 UTC
Labels: enhancement
