### ISSUE TITLE
sync certain folders only when on wifi

### ISSUE THREAD

**Issue by oneyb** [syncthing/syncthing-android#1186] opened 2018-07-22 12:43 UTC
Dear Syncthing-Android developers,

Great app and thank you for driving this great project. I have a hopefully modest feature request.

I would like to sync certain folders only when on wifi. 

Thank you for listening!

### Version Information

    App Version: 0.10.11
    Syncthing Version: v0.14.48
    Android Version: Android 7.

**Comment by Catfriend1** [comment] 2018-07-22 20:47
Sorry, duplicate of https://github.com/syncthing/syncthing-android/issues/511
I first have refactoring then run conditions to be more powerful and stable on my plan. Maybe then, pausing folders with a map of their untouched original state may come on top later.

**Closed** 2018-07-22 20:50 UTC
