### ISSUE TITLE
App shows "loading" but syncs in background

### ISSUE THREAD

**Issue by uok** [syncthing/syncthing-android#481] opened 2015-11-10 14:56 UTC
Thanks for updating Syncthing Android to be compatible with v0.12!
Currently the app is stuck on "loading..." (api_loading) but syncs in background. Also accessing the web GUI works. I already tried forced shutdown/phone reboot but this didn't help.
Any ideas?

**Comment by licaon-kter** [comment] 2015-11-10 15:18
How long did you wait?

**Comment by uok** [comment] 2015-11-10 17:14
~5 minutes or longer. Sync in "the background" has already finished (confirmed with web GUI) but the app GUI still says "loading..."

**Comment by licaon-kter** [comment] 2015-11-10 18:20
I've seen long "loading..." too, although I did not check with the WebUI, it started eventually.

**Comment by AudriusButkevicius** [comment] 2015-11-10 20:06
#482?

**Comment by GijsTimmers** [comment] 2015-11-11 13:16
I'm having the same problem. After a couple of minutes, I saw a toast message saying 'failed to load config' or something like that.

**Comment by licaon-kter** [comment] 2015-11-11 13:21
@GijsTimmers: Did you ever granted root permissions? If so, you need to chmod/chown the folders (700) and files (600) to the syncthing user u0_aXXX.

**Comment by GijsTimmers** [comment] 2015-11-11 13:46
Hi, thank you. I guess the username is faulty. How do I find the right one?

```
$ adb shell
$ su
# cd /mnt/sdcard2/
# chmod 700 Shared/
# chown u0_aXXX Shared/
No such user 'u0_aXXX'
```

**Comment by licaon-kter** [comment] 2015-11-11 13:54
No, the error is about **/data/data/com.nutomic.syncthingandroid** folder.

If you want to preserve current keys/config (if you have them), FORCE CLOSE syncthing and just rename that folder to **com.nutomic.syncthingandroid_bak** and start syncthing again. After keygen you can (as root) `ls -la /data/data/com.nutomic.syncthingandroid/files` and see what user/group the app uses so you can set up your old folder with those (delete the new folder, rename the old back).

Use a (root enabled) file manager to do as much as you can.

**Comment by GijsTimmers** [comment] 2015-11-11 14:37
I did what you said. Seemed that there were three files owned by `root` instead of `u0_a105`. I changed the ownership with ES File Manager and restarted the app. Right now, it only shows the loading icon. The Web UI does not work either.

**Comment by licaon-kter** [comment] 2015-11-11 14:49
BTW, you can't sync read-only folders, as the app needs to write a **.stfolder** file in there.

**Comment by Nutomic** [comment] 2015-11-15 16:19
Did you enable and then disable root in the app? In that case, we run [this code](https://github.com/syncthing/syncthing-android/blob/master/src/main/java/com/nutomic/syncthingandroid/fragments/SettingsFragment.java#L314). Can you check manually if this works on you device? (the `chown -R --reference=`)

**Comment by klement** [comment] 2015-11-16 11:39
I too have issues with root - changing options I always break the app and need to wipe data to start again. I think this is behaviour which should NEVER happen, since casual user is just screwed.

Is there a known way to get it working with root? I want to sync my whole /sdcard (for backup purposes).

**Comment by licaon-kter** [comment] 2015-11-16 11:43
Casual user does not have root access.

**Comment by AudriusButkevicius** [comment] 2015-11-16 11:44
Exactly.

This is another one of these: 
Q: Doctor, it hurts when I do this. 
A: Well, then don't do this

**Comment by klement** [comment] 2015-11-16 11:50
OK. I understand that it's open source and your good will to work on this and appreciate the effort.

This reminds me of my early days when coding - my app crashed when the user entered text into field where it expected number - money amount. The user is of course not expected to do that. The app should survive it nevertheless. In principle it's the same thing.

The app has root, it should be able to fix permissions for itself, right? :)

**Comment by Nutomic** [comment] 2015-11-16 11:54
We do revert the permissions when you disable root in the app. Are you disabling root from you su app perhaps?

**Comment by klement** [comment] 2015-11-16 11:57
I'm not disabling root, I actually want root since I want the app to have unrestricted access to all files in the phone. 

The problem is that once I enable root and change any setting (so far it seems that any setting change does it), the app breaks - it no longer loads, I see that it's constantly asking for root (and getting the root) and after some time it fails with a message that config couldn't be created.

**Comment by GijsTimmers** [comment] 2015-11-16 12:01
> The problem is that once I enable root and change any setting (so far it seems that any setting change does it), the app breaks - it no longer loads, I see that it's constantly asking for root (and getting the root) and after some time it fails with a message that config couldn't be created.

I'm having the exact same thing, probably due to that cause as well.

**Comment by lunix15** [comment] 2015-11-17 15:15
I've the some problem too..
Seem that in the MainActivity, inside the onApiChange(SyncthingService.State currentState) at line 74, 'currentState' keeps on being in the STARTING state.. so mLoadingDialog.dismiss() in never called

**Comment by licaon-kter** [comment] 2015-11-17 15:29
@klement Given this is not fixed https://github.com/syncthing/syncthing-android/issues/453 what use case do you have for root?

**Comment by klement** [comment] 2015-11-17 15:50
Well, if I set everything up, then enable root as the very last step and
never touch it again, everything seems to be working fine for me.

My use case is backing up /sdcard with everything on it to my linux server.

**Comment by licaon-kter** [comment] 2015-11-17 15:58
There 2 issues here:
1. Read https://github.com/syncthing/syncthing-android/issues/453 again
2. You should be able to read /sdcard without root anyway, afaik.

**Comment by lunix15** [comment] 2015-11-17 16:46
Sorry guys.. is not 5 minutes or longer.. is for ever and ever......

**Comment by klement** [comment] 2015-11-17 19:24
1. This is similar to the issue I hit.
2. Hmm, really? I thought that reading Android/data etc required root

**Comment by licaon-kter** [comment] 2015-11-17 21:14
You can test this easily with ES Explorer, don't enable root in app and deny root in SuperSU for the app (just to be sure). I just tested it and it works fine, as it should as **/sdcard** is user playground.

For **/data/data/** you need root and you hit that bug. And unfortunately most apps don't save/export important stuff to /sdcard/Android/data :(

**Comment by klement** [comment] 2015-11-17 21:19
You are correct. I don't need root then.

**Comment by zbits** [comment] 2015-11-20 13:15
I started having the same issue after upgrading to 0.7.4 (0.12.x).  The app says "Loading..." forever but will still sync my files.  Running unrooted Android 5.1.

**Comment by go2null** [comment] 2016-08-25 01:24
Duplicated by #687?

**Comment by Nutomic** [comment] 2017-11-13 11:12
This was most likely fixed in one of the recent releases. If not, please open a new issue with logs.

**Closed by Nutomic** 2017-11-13 11:12 UTC
Labels: bug, root
