### ISSUE TITLE
Swiping is broken in introduction screen

### ISSUE THREAD

**Issue by A31Nesta** [syncthing/syncthing-android#1792] opened 2022-05-21 11:25 UTC
The introduction screen when you open the app for the first time gets stuck if I try to swipe to the next slide (instead of pressing the Next button.
I expected it to go to the next slide when I swipe.

To reproduce the issue you just have to:

1. Open the app for the first time.
2. Drag your finger from right to left in the introduction

This is a screen recording of me trying to swipe between slides and sometimes pressing the buttons (just to prove that the buttons work):
https://drive.google.com/file/d/16nU6osMXkFf5dqFnovHxnGIizjp9tr7N/view?usp=sharing

### Version Information

    App Version: 1.20.1 (currently latest version in the Play Store)
    Android Version: Android 12
    MIUI Version (Xiaomi phones tends to have issues some apps): 13.0.8 Global

**Comment by tomasz1986** [comment] 2022-05-21 11:57
This is a duplicate of https://github.com/syncthing/syncthing-android/issues/1334.

**Comment by A31Nesta** [comment] 2022-05-21 12:36
Yeah it was probably a better idea to just comment there, I just thought that it would be a good idea to give some more information

**Closed** 2022-05-21 16:17 UTC
