### ISSUE TITLE
New devices want to connect constantly

### ISSUE THREAD

**Issue by bxabi** [syncthing/syncthing-android#1018] opened 2018-02-07 17:49 UTC
App Version: 0.10.4
    Syncthing Version: v0.14.43
    Android Version: Android 7.1

The syncthing on ny phone constantly reports that my other devices want to connect.
I only want to connect a single device to my phone, but there is no way to cancel those connections, they are constantly coming back. Actually I have no ide why they appear, I never connected them to the phone.
There is no way to disable this strange device discovery feature, nor in the android app, and nor on the other devices.

The linux desktop version doesn't have this problem, the unwanted devices show up only on the android version.

None of the devices is configured as introducer.

**Comment by AudriusButkevicius** [comment] 2018-02-07 18:10
You must have you android devices added on the machines that are making connection attempts.

**Comment by bxabi** [comment] 2018-02-07 22:19
No, I added the android device to a single computer. No ide why the others are appearing. The android device is sending requests, it is one way.

**Comment by AudriusButkevicius** [comment] 2018-02-07 22:22
I am not saying android is sending them, android is receiving them, yet I would still double check that android is not added on any other device. Also, does it only happen when Android is in LAN with other devices that are shared with someone else? For example device A might mistake android for some device B, and android and device B happen to advertise the same address.

**Comment by bxabi** [comment] 2018-02-07 22:23
It is getting connection requests also from 2 devices which are not on the same LAN.

**Comment by bxabi** [comment] 2018-02-07 22:30
So it is like Android is A, and B,C,D linux devices.
The connections: A is connected to B, and B,C,D are connected to each other.
A is getting requests from C and D, even if I didn't connect them. I can dismiss the notification but it is showing up in a while again.

**Comment by bxabi** [comment] 2018-02-07 22:33
A,B,C are in LAN, D is a VPS.

**Comment by AudriusButkevicius** [comment] 2018-02-07 22:34
Anyways, I am closing this, as this needs to be debugged on the forum first, as it's not clear what the issue is here. Provide logs from all sides on the forum so we can look into this.

**Closed by AudriusButkevicius** 2018-02-07 22:34 UTC

**Comment by AudriusButkevicius** [comment] 2018-02-07 22:35
Or provide screenshots.

**Comment by bxabi** [comment] 2018-03-28 12:24
Hi, I just wanted to notify you that the issue apeears to be fixed, the annoying notifications are not appearing since about a week ago.
