### ISSUE TITLE
On WSA, syncthing unable to progress past ""Generating keys. This may take a while."

### ISSUE THREAD

**Issue by 93-infinity** [syncthing/syncthing-android#1910] opened 2023-05-17 14:49 UTC
### Version Information

    App Version: ???
    Syncthing Version: Version 1.23.4 (4340) 
    Android Version: Android 13 / WSA 2303.40000.5.0

"If your only tool is ~~a hammer~~ syncthing then every problem looks like ~~a nail~~ a file sync issue" 🤣 

There's a new feature of Windows called "Windows Subsystem for Android" that allows running Android apps on Windows. Since using adb to get files into and out of the filesystem is cumbersome, I thought I could use syncthing, a tool that I've thrown at every problem I've been having recently.

Upon completing the permissions wizard, it remained at the "Generating secure keys. This may take a few minutes." dialog, where it remains stuck indefinitely. If one force closes syncthing and reopens it, the above dialog is gone, and it opens to the main "Folders/Devices" screen. But there's a spinner in the white space and nothing is clickable (incl. the hamburger menu).

I know it's probably a strange environment to be using syncthing on and I'm not expecting it to work, but I thought I may as well provide some feedback anyway. I captured a logcat with output before opening syncthing and then launching it and remaining stuck, is it possible for me to send it to someone non-publicly (email)?

**Comment by Catfriend1** [comment] 2023-06-16 23:07
I think you're aware of there's a Windows Syncthing binary to run instead of the Android app... It might be the architecture for which the Syncthingnative is built and included in the apk what causes the app to hang after failed execution.

**Comment by imsodin** [comment] 2023-06-17 09:45
Duplicate of https://github.com/syncthing/syncthing-android/issues/1451

**Closed by imsodin** 2023-06-17 09:45 UTC
