### ISSUE TITLE
Unable to select the download folder as the synchronization directory on Xiaomi 14 Ultra phones

### ISSUE THREAD

**Issue by go1me** [syncthing/syncthing-android#2102] opened 2024-09-15 17:03 UTC
Unable to select the download folder as the synchronization directory on Xiaomi 14 Ultra phones

Cannot use this folder，To protect your privacy, please choose another folder

The button is gray

### Version Information

    App Version: 1.27.10
    Syncthing Version: 1.27.10
    Android Version: Android 14

**Comment by tomasz1986** [comment] 2024-09-18 08:30
Basically a duplicate of https://github.com/syncthing/syncthing-android/issues/1638.

You may try to use the workaround suggested in https://github.com/syncthing/syncthing-android/issues/1638#issuecomment-1030676341.

**Closed by tomasz1986** 2024-09-18 08:30 UTC
