### ISSUE TITLE
IllegalStateException: Fragment FoldersFragment is not currently in the FragmentManager

### ISSUE THREAD

**Issue by Zillode** [syncthing/syncthing-android#316] opened 2015-03-27 19:21 UTC
Happened on startup (so onSaveInstanceState should have been empty?)
```
03-27 20:18:25.269    1892-1892/com.nutomic.syncthingandroid.debug I/art﹕ Not late-enabling -Xcheck:jni (already on)
03-27 20:18:25.321    1892-1892/com.nutomic.syncthingandroid.debug W/ActivityThread﹕ Application com.nutomic.syncthingandroid.debug is waiting for the debugger on port 8100...
03-27 20:18:25.323    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ Sending WAIT chunk
03-27 20:18:25.344    1892-1899/com.nutomic.syncthingandroid.debug I/art﹕ Debugger is active
03-27 20:18:25.544    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ Debugger has connected
03-27 20:18:25.544    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:29.175    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:29.385    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:29.595    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:29.804    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:30.014    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:30.224    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:30.435    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:30.645    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:30.856    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:31.064    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ waiting for debugger to settle...
03-27 20:18:31.277    1892-1892/com.nutomic.syncthingandroid.debug I/System.out﹕ debugger has settled (1501)
03-27 20:18:31.610    1892-2028/com.nutomic.syncthingandroid.debug D/OpenGLRenderer﹕ Render dirty regions requested: true
03-27 20:18:31.612    1892-1892/com.nutomic.syncthingandroid.debug D/﹕ HostConnection::get() New Host Connection established 0xa6cfe0b0, tid 1892
03-27 20:18:31.617    1892-1892/com.nutomic.syncthingandroid.debug D/Atlas﹕ Validating map...
03-27 20:18:31.635    1892-1892/com.nutomic.syncthingandroid.debug E/FragmentManager﹕ Fragment FoldersFragment{2532a797} is not currently in the FragmentManager
03-27 20:18:31.635    1892-1892/com.nutomic.syncthingandroid.debug E/FragmentManager﹕ Activity state:
03-27 20:18:31.635    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ Local FragmentActivity 3b9e31c7 State:
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mCreated=truemResumed=false mStopped=false mReallyStopped=false
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mLoadersStarted=true
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ Active Fragments in 4439dee:
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ #0: DrawerFragment{3efcf28f #0 id=0x7f0a0057}
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mFragmentId=#7f0a0057 mContainerId=#7f0a0057 mTag=null
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mState=4 mIndex=0 mWho=android:fragment:0 mBackStackNesting=0
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mAdded=true mRemoving=false mResumed=false mFromLayout=false mInLayout=false
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mHidden=false mDetached=false mMenuVisible=true mHasMenu=false
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mRetainInstance=false mRetaining=false mUserVisibleHint=true
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mFragmentManager=FragmentManager{4439dee in MainActivity{3b9e31c7}}
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mActivity=com.nutomic.syncthingandroid.activities.MainActivity@3b9e31c7
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mSavedViewState={16908298=AbsListView.SavedState{d35091c selectedId=0 firstId=-1 viewTop=0 position=0 height=0 filter=null checkState={}}, 2131361857=android.view.AbsSavedState$1@30039925, 2131361858=android.view.AbsSavedState$1@30039925, 2131361859=android.view.AbsSavedState$1@30039925, 2131361860=android.view.AbsSavedState$1@30039925, 2131361861=android.view.AbsSavedState$1@30039925, 2131361862=android.view.AbsSavedState$1@30039925, 2131361863=android.view.AbsSavedState$1@30039925, 2131361864=android.view.AbsSavedState$1@30039925, 2131361865=android.view.AbsSavedState$1@30039925, 2131361866=android.view.AbsSavedState$1@30039925, 2131361867=android.view.AbsSavedState$1@30039925, 2131361868=android.view.AbsSavedState$1@30039925}
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mContainer=android.widget.LinearLayout{21cfaafa V.E...C. ......ID 0,0-0,0 #7f0a0057 app:id/drawer}
03-27 20:18:31.638    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mView=android.support.v4.app.NoSaveStateFrameLayout{22e028ab V.E..... ......I. 0,0-0,0}
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mInnerView=android.support.v4.app.NoSaveStateFrameLayout{22e028ab V.E..... ......I. 0,0-0,0}
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ Child FragmentManager{5179b08 in DrawerFragment{3efcf28f}}:
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ FragmentManager misc state:
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mActivity=com.nutomic.syncthingandroid.activities.MainActivity@3b9e31c7
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mContainer=android.support.v4.app.Fragment$1@c79a2a1
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mParent=DrawerFragment{3efcf28f #0 id=0x7f0a0057}
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mCurState=4 mStateSaved=true mDestroyed=false
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ Added Fragments:
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ #0: DrawerFragment{3efcf28f #0 id=0x7f0a0057}
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ FragmentManager misc state:
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mActivity=com.nutomic.syncthingandroid.activities.MainActivity@3b9e31c7
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mContainer=android.support.v4.app.FragmentActivity$2@8dd7cc6
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ mCurState=4 mStateSaved=true mDestroyed=false
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ View Hierarchy:
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ com.android.internal.policy.impl.PhoneWindow$DecorView{976a487 V.E..... ... 0,0-0,0}
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.LinearLayout{350f5fb4 V.E..... ... 0,0-0,0}
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.view.ViewStub{3fecc7dd G.E..... ... 0,0-0,0 #102036e}
03-27 20:18:31.639    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.FrameLayout{ea49f52 V.E..... ... 0,0-0,0}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.ActionBarOverlayLayout{300f0223 V.E..... ... 0,0-0,0 #7f0a002f app:id/decor_content_parent}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.NativeActionModeAwareLayout{131cc320 V.E..... ... 0,0-0,0 #1020002 android:id/content}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v4.widget.DrawerLayout{317304d9 VFE..... ... 0,0-0,0 #7f0a0055 app:id/drawer_layout}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v4.view.ViewPager{32495e9e VFED.... ... 0,0-0,0 #7f0a0056 app:id/pager}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.LinearLayout{21cfaafa V.E...C. ... 0,0-0,0 #7f0a0057 app:id/drawer}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v4.app.NoSaveStateFrameLayout{22e028ab V.E..... ... 0,0-0,0}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.LinearLayout{10459d7f V.E..... ... 0,0-0,0}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.RelativeLayout{32daf14c V.E..... ... 0,0-0,0}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{9861595 V.ED.... ... 0,0-0,0 #7f0a0045 app:id/device_id_title}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{2ee8c6aa V.ED.... ... 0,0-0,0 #7f0a0046 app:id/device_id}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.RelativeLayout{3720929b V.E..... ... 0,0-0,0}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{246bd638 V.ED.... ... 0,0-0,0 #7f0a0047 app:id/cpu_usage_title}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{47f7611 V.ED.... ... 0,0-0,0 #7f0a0048 app:id/cpu_usage}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.RelativeLayout{2264a376 V.E..... ... 0,0-0,0}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{31ebbd77 V.ED.... ... 0,0-0,0 #7f0a0049 app:id/ram_usage_title}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{16241de4 V.ED.... ... 0,0-0,0 #7f0a004a app:id/ram_usage}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.RelativeLayout{30d4624d V.E..... ... 0,0-0,0}
03-27 20:18:31.640    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{14ef8102 V.ED.... ... 0,0-0,0 #7f0a0041 app:id/download_title}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{2cd4ba13 V.ED.... ... 0,0-0,0 #7f0a0042 app:id/download}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.RelativeLayout{24f73450 V.E..... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{1511d649 V.ED.... ... 0,0-0,0 #7f0a0043 app:id/upload_title}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{2d58ab4e V.ED.... ... 0,0-0,0 #7f0a0044 app:id/upload}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.RelativeLayout{1f46e46f V.E..... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{7a3457c V.ED.... ... 0,0-0,0 #7f0a004b app:id/announce_server_title}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{39988e05 V.ED.... ... 0,0-0,0 #7f0a004c app:id/announce_server}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.view.View{1e182e5a V.ED.... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.view.View{2207588b V.ED.... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.view.View{9d3d68 V.ED.... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.ListView{12190581 VFED.VC. ... 0,0-0,0 #102000a android:id/list}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.ActionBarContainer{171ad626 V.ED.... ... 0,0-0,0 #7f0a0030 app:id/action_bar_container}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.widget.Toolbar{b10f267 V.E..... ... 0,0-0,0 #7f0a0031 app:id/action_bar}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.widget.TextView{2bcc814 V.ED.... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.ActionBarContextView{2cf78bd G.E..... ... 0,0-0,0 #7f0a0032 app:id/action_context_bar}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.ScrollingTabContainerView{84e2eb2 VFED.... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.widget.LinearLayoutCompat{2b304e03 V.ED.... ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.ScrollingTabContainerView$TabView{34a85180 VFE...C. .S. 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.CompatTextView{3d7fe3b9 V.ED.... .S. 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.ScrollingTabContainerView$TabView{ec83fe VFE...C. ... 0,0-0,0}
03-27 20:18:31.641    1892-1892/com.nutomic.syncthingandroid.debug D/FragmentManager﹕ android.support.v7.internal.widget.CompatTextView{95fc75f V.ED.... ... 0,0-0,0}
03-27 20:18:31.642    1892-1892/com.nutomic.syncthingandroid.debug D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
03-27 20:18:31.642    1892-1892/com.nutomic.syncthingandroid.debug E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.nutomic.syncthingandroid.debug, PID: 1892
    java.lang.IllegalStateException: Fragment FoldersFragment{2532a797} is not currently in the FragmentManager
            at android.support.v4.app.FragmentManagerImpl.putFragment(FragmentManager.java:571)
            at com.nutomic.syncthingandroid.activities.MainActivity.onSaveInstanceState(MainActivity.java:230)
            at android.app.Activity.performSaveInstanceState(Activity.java:1297)
            at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1272)
            at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:3923)
            at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3886)
            at android.app.ActivityThread.access$900(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by Nutomic** [comment] 2015-05-18 20:06
Is this still happening?

It might have been fixed [here](https://code.google.com/p/android/issues/detail?id=77285). Otherwise, we might have to use [`getChildFragmentManager()`](http://stackoverflow.com/a/19332607).

**Comment by Zillode** [comment] 2015-05-18 20:20
[Seems not](https://android.googlesource.com/platform/frameworks/support/+/tools_r22.2/v4/java/android/support/v4/app/FragmentStatePagerAdapter.java)

**Comment by Nutomic** [comment] 2015-05-18 20:31
Weird. I commented on the issue.

**Comment by Nutomic** [comment] 2015-06-10 23:10
Looks like this is actually a duplicate of #265 (correct me if I'm wrong).

**Closed by Nutomic** 2015-06-10 23:10 UTC
Labels: bug
