### ISSUE TITLE
crash code 2, beacon.NewMulticast  --> panic: runtime error: slice bounds out of range 

### ISSUE THREAD

**Issue by de-live-gdev** [syncthing/syncthing-android#352] opened 2015-04-12 09:22 UTC
Syncthing v0.10.30, S-Android v0.5.28, Android 5.1

Syncthing crashes after about 30 seconds of running.
Fresh setup, got 1 device connected and 0 shares.

Catlog: <http://pastebin.com/GwaDeY88>

    04-12 11:11:57.620: W/SyncthingNativeCode(17844): created by github.com/syncthing/protocol.NewConnection
    04-12 11:11:57.620: W/SyncthingNativeCode(17844): 	/var/lib/jenkins/jobs/Syncthing-Android-Release/workspace/ext/syncthing/src/github.com/syncthing/syncthing/Godeps/_workspace/src/github.com/syncthing/protocol/protocol.go:158 +0x344
    04-12 11:11:57.630: I/chromium(17844): [INFO:CONSOLE(103)] "UIOffline", source: http://127.0.0.1:3005/scripts/syncthing/core/controllers/syncthingController.js (103)
    04-12 11:11:57.630: E/SyncthingNativeCode(17844): Syncthing binary crashed with error code 2
    04-12 11:11:57.889: W/GetTask(17844): 	at com.nutomic.syncthingandroid.syncthing.b.a(Unknown Source)
    04-12 11:11:57.889: W/GetTask(17844): 	at com.nutomic.syncthingandroid.syncthing.b.doInBackground(Unknown Source)

Another logcat: (SyncthingNativeCode:v)
http://pastebin.com/ssBRpb8b

    W/SyncthingNativeCode(19072): panic: runtime error: slice bounds out of range
    W/SyncthingNativeCode(19072): goroutine 67 [running]:
    W/SyncthingNativeCode(19072): github.com/calmh/xdr.(*Reader).ReadBytesMaxInto(0x10bf20c0, 0x20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    W/SyncthingNativeCode(19072):   /var/lib/jenkins/jobs/Syncthing-Android-Release/workspace/ext/syncthing/src/github.com/syncthing
    ...
    ...
    W/SyncthingNativeCode(19072):   /var/lib/jenkins/jobs/Syncthing-Android-Release/workspace/ext/syncthing/src/github.com/syncthing/syncthing/internal/beacon/beacon.go:24 +0xa0
    W/SyncthingNativeCode(19072): created by github.com/syncthing/syncthing/internal/beacon.NewMulticast
    E/SyncthingNativeCode(19072): Syncthing binary crashed with error code 2

**Comment by de-live-gdev** [comment] 2015-04-12 09:42
Another logcat: (SyncthingNativeCode:v)
<http://pastebin.com/ssBRpb8b>

**Comment by Zillode** [comment] 2015-04-12 10:10
Thanks for your report,

I think this is a duplicate of https://github.com/syncthing/syncthing/issues/1606
Is this correct @calmh ?

**Comment by Zillode** [comment] 2015-04-29 18:24
[Yes it is](https://github.com/syncthing/syncthing/issues/1714). Will be fixed in the next release

**Closed by Zillode** 2015-04-29 18:24 UTC
Labels: upstream
