### ISSUE TITLE
slow storage access when syncing a large number of small files located in a single folder

### ISSUE THREAD

**Issue by eugenesan** [syncthing/syncthing-android#2103] opened 2024-09-17 22:01 UTC
Recently I had to update \~20k small files and the sync was going **VERY** slow (one file per \~2 seconds).
After 24 hours, I gave up waiting.

The weird thing is that I remember that when I added the files initially it was much faster.
Though at the time I used an older version of the App (probably v1.27.3, the last available on GooglePlay).

I tried to "update" the files on the device manually and let it re-scan, playing with performance related options but nothing helped.

What did help is setting `caseSensitiveFS` to `true` for the folders in question.
After doing that, it synced in a few minutes.

**The question is why and how can it be improved?**

Also, I found that `hashers` was set to `1` which might have contributed to the issue.
Not sure if that is the current default for the App or it just a leftover from a previous versions (I didn't touch the config for a while).
If I understand it correctly, switching the option to `0` should make syncthing scale the number of hashers.
Considering most modern Android devices come with up to 9 CPUs, `0` should be the default.

P.S.
I have 2 identical (Hardware and Software) Android devices and they both had the same issue and both benefited from the solution.

---
App Version: 1.27.10 (F-Droid)
Syncthing Version: v1.27.10
Android Version: Android 14 (Google Pixel)
---

**Comment by tomasz1986** [comment] 2024-09-18 07:58
The slow I/O in newer Android version is a known problem, and it is by design by Google for security reasons.

See https://www.reddit.com/r/androiddev/comments/kpn68k/android_11_very_slow_file_access_performance and https://forum.syncthing.net/t/how-to-deal-with-abysmal-i-o-performance-on-android-10/18406.

Not closing the issue for now, as I don't think we've actually got an open issue about it. Still, I'm not sure if it's even possible to fix the problem.

> If I understand it correctly, switching the option to `0` should make syncthing scale the number of hashers.

This depends on the OS. On Windows, macOS, and Android, if you set the value to `0`, then it will actually just default to `1` (see https://github.com/syncthing/syncthing/blob/cb24638ec9d8e5bc13317641d1f49b504eac9dc8/lib/model/model.go#L2561-L2576C3). If you want to use a larger number, you need to set it to a specific value manually.

**Comment by imsodin** [comment] 2024-09-18 17:10
Please don't do that, the option isn't enabled for fun or to torment you - it prevents scenarios than can lead to loss of data.

One of the next releases will improve the situation, at least regarding scanning.

**Closed by imsodin** 2024-09-18 17:10 UTC
