### ISSUE TITLE
Immeidiate crash on every run under Android 4.4.2

### ISSUE THREAD

**Issue by unfa** [syncthing/syncthing-android#226] opened 2015-03-08 15:52 UTC
This happens for versions 0.5.15, 0.5.16 and 0.5.17.

I'd like to give more info, but I don't know how and what.

![screenshot_2015-03-08-16-48-11](https://cloud.githubusercontent.com/assets/491704/6546414/6932d0b6-c5b3-11e4-9978-fcec15f99d1a.png)

**Comment by Zillode** [comment] 2015-03-08 18:01
Which device is this? We need a logcat: https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md#bug-reports

**Comment by unfa** [comment] 2015-03-10 16:36
I updated to version 0.5.18 and it's not crashing now.
However it seems to enter an endless loop while generating the device keys. I let it run for half an hour or so and it didn't do anything.

**The device**

Manufacturer: Krüger & Matz
Model: Soul
Specs: http://www.krugermatz.com/en/products/km0409

I'll try to provide a logcat later.

**Comment by unfa** [comment] 2015-03-10 17:14
An hour later I still see the same picture. Yes, I think it's hung.

**Comment by unfa** [comment] 2015-03-10 18:30
2 hours later I still see the same progress circle. Definitely an endless loop.

**Comment by Nutomic** [comment] 2015-03-10 18:31
We can't do anything without a log.

Also might be a duplicate of #216.

**Comment by Zillode** [comment] 2015-03-21 12:45
Closing for now, feel free to reopen with a logcat.

**Closed by Zillode** 2015-03-21 12:45 UTC
