### ISSUE TITLE
Lollipop 5.0.1: ExtSdCard: Permission Denied to standard folder: missing prompt

### ISSUE THREAD

**Issue by vjz224** [syncthing/syncthing-android#367] opened 2015-04-19 23:48 UTC
Unable to use Syncthing with Lollipop for custom folders on an external SD card (I am rooted). Error is "permission denied to <folder path>. Syncthing doesn't prompt for new storage / permission protocol:

http://www.androidcentral.com/lollipop-brings-changes-way-your-sd-card-works-kind-youll

Target folders are in the root directory of the ExtSdCard. This works perfectly on my S5 running 4.4.4 (details below).

Let me know what info I can provide.

Problem Device: NVidia Shield Tablet 4g LTE
SD Card: Sandisk micro-sd 128GB
Android Lollipop 5.0.1 (rooted)
Syncthing Version: 10.30

Working Device: Samsung Galaxy S5
SD Card: Sandisk micro-sd 32GB
Android KitKat 4.4.4 (rooted)
Syncthing Version: 10.30

**Comment by Nutomic** [comment] 2015-04-20 19:50
Can you post a logcat?

That article you linked doesn't describe any removed functionality, only added one. Did you apply any sd card hack to your S5?

**Comment by vjz224** [comment] 2015-04-20 19:53
I'd be happy to provide logs, I just need a little more instruction.

No other hacks were completed against the sd card. 

This issue points out a compatibility issue with android 5.0 and the storage API. Or call it a feature, whatever. I'm just hoping to help improve the product. I like it.

**Comment by Nutomic** [comment] 2015-04-20 21:00
[See here](https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md#bug-reports)

What I'm saying is, the change in that post should not break anything ;)

**Comment by NapalmCandy** [comment] 2015-04-21 10:45
I also have the same problem with S4 and android 5.0.1 also I am rooted. Intried a hack to give permissions to write on ExtSD ( http://www.blogdecelulares.com.ar/android/como-habilitar-la-escritura-en-la-tarjeta-microsd-externa-en-android-4-4-kitkat.html ) But it don't work. 

I didn't try before on older android.

**Comment by vjz224** [comment] 2015-04-21 13:04
Thx Nutomic.

Logcat available here: https://drive.google.com/file/d/0B9PCKrjbN4mhNFFaVjVMU21rVFk/view?usp=sharing

In app error screenshot also included in the zip.

I agree the program should continue to function with lollipop, especially on a rooted device. Other storage programs (ES Explorer) work just fine. I'm just not familiar enough with the the app or 5.x storage api changes to troubleshoot any further.

Also, tried to pull a config.xml and I am unable to locate a syncthing folder under Android/data.

How else can I help?

**Comment by ovizii** [comment] 2015-04-21 16:33
Exactly the same problem here, I get: folder not found.

**Comment by ovizii** [comment] 2015-04-21 16:43
The weirdest thing ever happened, I forced-stopped syncthing and restarted a few times and its syncing now !? I'll update this thread if I figure out what changed...

**Comment by Nutomic** [comment] 2015-04-22 22:01
sdcard1 should not be available to apps, only sdcard0 (same as on 4.4).

**Comment by vjz224** [comment] 2015-04-25 20:18
Lollipop can handle it folder support on any additional device with the new changes. How awesome would it be to have syncthing work out of the box with sdcard1.

You can close the issue if this isn't something you want the app to do...

**Comment by Nutomic** [comment] 2015-04-26 02:54
I definitely want this to work, but it needs support in golang. The new API uses URIs instead of paths, which golang doesn't support yet (afaik).

**Comment by Nutomic** [comment] 2015-04-27 22:14
Basically the same as #29, not sure why I had that closed :s

**Comment by Nutomic** [comment] 2015-05-18 00:37
Closing as duplicate of #29.

**Closed by Nutomic** 2015-05-18 00:37 UTC
