### ISSUE TITLE
High Power Consumption

### ISSUE THREAD

**Issue by wewondr** [syncthing/syncthing-android#368] opened 2015-04-22 19:40 UTC
Hello!
Today I noted an excessive power consumption of the app (on the second day of use). Synchronization is turned on only in WLAN. There were seven photos to transfer (14 MB via WLAN) and this required 8% of the total battery power. The sync works beautiful, but the power consumption is to much!
Syncthing Version: v0.10.30
Syncthing-Android Version: 0.5.28
Sony Xperia Z1 Compact
Android 4.4.4

**Comment by AudriusButkevicius** [comment] 2015-04-22 20:28
Are there two android devices involved by any chance?
Also, it would be useful to see how much network traffic was consumed to sync these 14mb, as that could indicate that the power consumption is due to the protocol chatter.

**Comment by wewondr** [comment] 2015-04-22 20:50
No, it's a sync between Android and Windows. Sadly I don't see the wlan network traffic of the app. No mobile data where used by the app (like the config is). 

Am 22. April 2015 22:28:06 MESZ, schrieb Audrius Butkevicius <notifications@github.com>:

**Comment by Nutomic** [comment] 2015-04-22 21:20
You can see the traffic used in system settings ("Data Usage").

Duplicate of #349?

**Comment by wewondr** [comment] 2015-04-23 04:27
okay, i missed the checkbox "view wlan".
syncthing has consumed 50.94 MB (transferred files = 14 MB).

**Comment by ManuelSchneid3r** [comment] 2015-06-11 13:28
Can confirm the high power consumption. Today 18% of my battery, for transferring 13,9MB of data (wlan usage).

**Comment by strout** [comment] 2015-08-24 18:45
"Me too" here. Android app info claims >3h CPU usage (of 6h total uptime) and 840B (bytes) sent/received.

One of the directories I'm syncing has symlinks in a sub-subdirectory (from a Linux machine) that are repeatedly retried/failed. That may be contributing somehow; I'll try deleting them.

**Comment by endolith** [comment] 2016-02-12 01:39
This is a problem for me, too.  I tried to sync my SD card for backup purposes and the phone becomes very hot and locks up and becomes unresponsive whenever syncthing is running.

**Comment by GLLM** [comment] 2016-03-14 18:11
Same here : battery drain is huge ...

1 folder sync'ed between Android 5.0.1 (Galaxy S4) and a server.

Hoping it will get solved in a foreseeable future ...

**Comment by lkwg82** [comment] 2016-04-10 14:17
@GLLM What is your version? I do have the same and everything was fine with android 4.4 and cm13 (android 6)

When you take a look into battery stats, how much percent is syncthing taking?

**Comment by GLLM** [comment] 2016-04-20 14:08
Hi !

My Server/NAS are on both on v0.12.22

Phone is on Android syncthing v0.7.11 (i.e. Syncthing v0.12.20)

The app can take like ~20/25% of the battery consumption of my phone in <30min ...
It's therefore unusable on a background sync basis.

So I launch it manually from time to time, then exit it + kill the process (simply exiting it on android does not stop the power leakage)

Thanks.

**Comment by GLLM** [comment] 2016-04-22 12:45
I've tried what I was reluctant do to : remove the app (initially from FDroid) and installed the one on Google Play, which is in a higer version :+1: 
* battery consumption is much less worrysome
* still : today, it is still the first battery eater program with 8% as of now, ahead of Android system, display & twitter.

So it's improved yet not perfect (Dropbox seemed to be using almost nothing even though it was syncing live)

Thx

**Comment by wweich** [comment] 2016-04-22 13:02
The battery statistic isn't really accurate.
After I activated the wake lock to prevent syncthing from being killed while the phone is in deep sleep, it changed from 2-3% to 10-18% in battery statistic, but the overall battery consumption (battery drain on a typical work day) didn't change a bit.

**Comment by GLLM** [comment] 2016-04-26 15:39
Hi

I've upgraded to 0.7.15.
And even thought battery stats are not accurate : my battery drain is still huge. And this drain did NOT happen prior to using Syncthing on my phone.

![syncthing_battery_issue](https://cloud.githubusercontent.com/assets/3989573/14824294/c451ccb8-0bd5-11e6-816f-8e994a1e12a2.png)

Dont know what to do.
But now I'm at 10% at 20h00, I was at 40 beforehand ... on average

GLLM

**Comment by licaon-kter** [comment] 2016-04-26 16:23
Picture of Syncthing battery details?
Picture of Syncthing network activity (mobile and/or Wi-Fi) details?

**Comment by AudriusButkevicius** [comment] 2016-04-26 16:29
If its disconnecting often or sending a lot of data, battery usage is expected.

**Comment by GLLM** [comment] 2016-06-06 14:43
Hello again,

I did not log for quite some time.
Here's some feedback: 
* been upgrading to each & every binary version on my phone, server & NAS
* been noticing a daily drain between 20 and 35% on a _daily_ basis even though no changes were made in my sync'ed folders (android photo folder)
* never had any battery issue with dropbox, priori to dropping & deleting my account in favor of Syncthing


Today is (no new pics taken)
![syncthing_batt](https://cloud.githubusercontent.com/assets/3989573/15825721/284ca2ca-2c05-11e6-9d30-8a8d1dd1a885.png)

![batt2](https://cloud.githubusercontent.com/assets/3989573/15825894/c9761c30-2c05-11e6-97c1-1475ad08afb4.png)
![batt3](https://cloud.githubusercontent.com/assets/3989573/15825892/c96c798c-2c05-11e6-9ad8-da6541dbe7bc.png)

It's getting annoying :(

What more info can I provide ?

Thanks.

**Comment by licaon-kter** [comment] 2016-06-06 14:50
Look at that signal, why do you believe you have 4G/LTE there? That constant switching and searching (orange/red signal colour bar) eats up your battery.

Do this for a test, limit Syncthing only on Wi-Fi for a day (start at 100% battery) and see how that fares.

**Comment by wweich** [comment] 2016-06-06 15:42
The battery meter from Android doesn't say much. When I enabled the experimental wake lock option, syncthing jumped from 2% to ~15% in the Android battery meter, but the real battery drain didn't really change.

**Comment by GLLM** [comment] 2016-06-14 06:49
@licaon-kter 
I did stop the synchro over LTE and only kept that over WiFi and 8t basically stopped the battery drainage. So it seems you were right.
However, the same settings with Dropbox (sync over LTE, in the same place with the same average reception quality) never induces the same battery leakage, or at least not in the same order of magnitude... hence my surprise !

I'll keep the sync I've WiFi for a while and consider if this has any drawbacks I cannot withstand.

Cheers
GLLM

**Comment by capi** [comment] 2016-06-14 08:43
It might be that in your area you get a lot of re-connects when using LTE/3G (e.g. on every switch between those two technologies), causing a complete handshake to be sent. How was the data usage for Syncthing?

**Comment by lkwg82** [comment] 2016-07-26 20:28
relates to #671

**Comment by micahscopes** [comment] 2017-02-04 23:12
I'm having this issue too.  Only syncing over wifi.  If there are stuck folders (out of sync master folders), syncthing can nail my battery in a matter of hours.

But even when "resting" (not syncing, no stuck folders), it seems to take at least 25% of my battery life.  I'm hardly changing any files for this to happen.  Compared to Resilio, which is taking a fraction of a percentage while resting.

I'm using GSAM to analyse the battery.  Running CM13, rooted.

**Comment by hubyhuby** [comment] 2017-03-11 07:11
TEST ON BATTERY LIFE:
Syncthing 0.14.16 consum way too much battery on Android in IDLE scenarios.
Running for 9 hours at night Syncthing consumed 14% of my battery doing nothing.
This mean roughly in a 24Hours day it should be responsible for 35% of battery lost when doing nothing at all.
I believe a Goal for this app would be to drain around 10% / day in IDLE scenarios (like this one). 
We are 2-3X too high.
----------
TEC SPECS:
Samsung galaxy a3 2016
Android 6.0.1
Dedicated relay server and @server with 5 persons using it 
----------
DATAS:
I have lost 24% battery in 9H05 away from the power plug during a night 
Not using the phone during this test (network stanby
Syncthing used 57% of the battery during this time (57% of 24% = 14%)

![batterysyncthing](https://cloud.githubusercontent.com/assets/26340942/23821415/ace7bb1c-0631-11e7-97cd-4d447184bf8a.png)

**Comment by micahscopes** [comment] 2017-03-11 07:28
I think it could do better even than 10%! Resilio Sync does very well when
idle, and I'm not totally certain but I think it is more on the order of
3%-4% over a 24hr period.

**Comment by Nutomic** [comment] 2017-03-11 09:38
@hubyhuby Android 6.0 is an unfortunate case, because inotify is broken. For this reason, we do folder rescans every 60 seconds with the default configuration. You can increase that interval in the web gui if thats okay for you.

**Comment by hubyhuby** [comment] 2017-03-11 09:59
@AudriusButkevicius Thks.
I have set the parameter for my rescanIntervals of my two folders to 300 (seconds I guess;).
1)BUT the value is always reseted to 0: 
-I save the parameters 
-If I go back RIGHT away it is still 300
-I go back in the normal GUI
-I come back in web gui => back to default 0

2) I noticed many parameters there, and was wondering if some other could help with the battery issue ?

Thks for your help
Yann

**Comment by Nutomic** [comment] 2017-03-11 10:20
Do you save the folder settings after you change the rescan interval? It should also show the changed rescan interval after you close the folders settings. And I dont think any of the other settings would affect battery usage.

**Comment by micahscopes** [comment] 2017-03-11 15:37
I was having an issue a while back where some of my folders had gotten
stuck in this weird state where one or two files would get out of sync and
remain that way.  It caused some of my peers statuses to read "98%"
perpetually. This really whammed the phone's battery life.  I have since
removed and added those folders back, which solved the stuck problem and
the battery issue. I'm on Android 6.0.1 and Syncthing has consumed only 2%
over 24+ hrs. When it was stuck, it was using 40%+ battery life, and would
drain my phone in less than a day.

**Comment by hubyhuby** [comment] 2017-03-12 09:35
@AudriusButkevicius, @Nutomic , My problem is closed.

I am using my own compiled version of the project. Which is not supposed to change this behavior...but in the end is generating the bug wis the "rescanIntervals"  !
To be sure I have installed your original V0.9.3 with sync 0.14.16 and it does work PERFECTLY for the parameter setup.

Thanks a lot for your help. Sorry for the disturbance.
I will now make sure to report every issue with the original Syncthing for android installation.

**Comment by hubyhuby** [comment] 2017-06-07 17:40
Dear  @Nutomic ,
I have tried the latest version of Syncthing (not my compile;) ), on samsung galaxy a3 2017.
And interestingely Samsung is providing an interesting profiling of the Syncthing app.
Also the phone keeps on saying we have to "optimise" the app, means shut it down ;) Even after you give all the usual autorisation to keep the app eating your batterie.

In short , users are prety much invited not to use syncthing, which is a problem I believe.
Please note that I have NO folder synchtonised, Syncthing is just supposed to be sitting IDLE.
An app like whatsapp that I use all the time consume 7%. And Syncthing IDLE consume 27% of my batterie in the same time :(

![screenshot_20170606-161837](https://user-images.githubusercontent.com/26340942/26892536-edac68f6-4bb8-11e7-8c48-ac43209d279c.png)

![screenshot_20170606-161758](https://user-images.githubusercontent.com/26340942/26892358-533ccd56-4bb8-11e7-87bf-6b671d1d73c9.png)
![screenshot_20170606-190143](https://user-images.githubusercontent.com/26340942/26892543-f7ff0188-4bb8-11e7-8962-1fc1ddfbad66.png)

**Comment by hubyhuby** [comment] 2017-07-05 05:03
Hi @AudriusButkevicius ,
Now I think, I may have catched something more precise concerning battery usage after some testing.
After exactely 1H30 on my device Samsung A3 2016 with android 6, I have 50% increase in CPU usage wether I have folder synchronised or not.
This is CONSISTENTLY hapening at least on my device. Would be nice to have a confirmation from someone out there .

![screenshot_20170606-161758](https://user-images.githubusercontent.com/26340942/26892358-533ccd56-4bb8-11e7-87bf-6b671d1d73c9.png)  
![screenshot_20170705-054253](https://user-images.githubusercontent.com/26340942/27849800-13fd4b68-6150-11e7-998e-1388fe243925.png)

**Comment by Nutomic** [comment] 2017-07-06 06:01
It would probably be helpful if you can catch some logs during that time. Possibly with [debug flags enabled](https://docs.syncthing.net/dev/debugging.html).

**Comment by nicuh** [comment] 2017-08-13 07:23
Syncthing Version: v0.14.32
Syncthing-Android Version: 0.9.12
Samsung S6
Android 7.0

I had the same issue, the battery consumption was high even the folder sync interval was set for 3 days.
I boiled down the cause to the fact that Uptime was never longer than 10-15 minutes. Which means the background Syncthing was being restarted, even the battery optimization was off.
I tried everything, all the combinations of settings, like _Always run in background_, with and without _Sync only on wifi_, with and without _Run service with foreground priority_.

In the end, the solution that worked for me was to disable **restartOnWakeup** in the advanced settings. According to Syncthing documentation, this restarts the background process: 
> Whether to perform a restart of Syncthing when it is detected that we are waking from sleep mode (i.e. a folded up laptop).

Here are the steps for disabling it:
- Go to Web GUI
- Click on Actions menu button and choose Advanced
- Find restartOnWakeup in the Options section and uncheck it

**Comment by capi** [comment] 2017-08-17 09:11
@nicuh Sounds interesting, need to dig into that.

**Comment by Nutomic** [comment] 2017-08-18 01:53
I'm not having any trouble with battery usage, but if other people can confirm that disabling restartOnWakeup solves the problem, we could do that by default for everyone.

**Comment by acolomb** [comment] 2017-08-18 16:17
I can confirm that it betters the situation on my device - LG G4 with LineageOS / Android 7.1.2. At least I have Syncthing backround processes now running for several hours at a time, until I lose my WiFi connection (run conditions active).

Sometimes I still get serious battery drain from a libsyncthing.so process eating one or two complete CPU cores, around 24 - 49% CPU usage according to the OS Monitor app. I suppose this is not syncthing-android's fault. May be related to #910? I will try to get some logging output when I catch it again and have some spare time.

Anyhow, **restartOnWakeup = false** by default seems like an essential improvement for the app to me. Otherwise a power-hungry rescan after each device sleep phase kind of renders sleeping pointless.

**Comment by capi** [comment] 2017-08-18 18:10
As I use the foreground service option (otherwise Syncthing is killed off on my device), it doesn't make a difference, since my device never enters CPU sleep mode. But for people that don't need this, it really could make a difference, if Syncthing does not restart itself once it detects the clock forward jump after waking up from CPU sleep.

**Comment by AudriusButkevicius** [comment] 2017-08-19 13:50
https://github.com/syncthing/syncthing/issues/565 is the ticket that is being addressed by this.
Given it's very old, I'd say it would need more testing to see if everything works as expected without restarting.

I know for a fact things like UPnP will take some time to correct themselves, but it probably doesn't make much sense on a mobile anyway.

**Comment by Nutomic** [comment] 2017-08-20 06:59
We could use the experimental options in the app for this. Then the question is just if we should set restartOnWakeup = false by default, or only let users do it themselves.

**Comment by plittlefield** [comment] 2018-03-13 14:47
![android_battery_syncthing_usage](https://user-images.githubusercontent.com/8265704/37348989-4f512d4a-26cd-11e8-943c-f61b1fd45cb5.png)

Oh, it's not normally this bad.

Google Pixel (sailfish), Android 8.1.0, Syncthing for Android 0.10.5

**Comment by wweich** [comment] 2018-03-13 17:22
Version 0.10.5 is broken, so it connects over and over just to get disconnected as soon as the index exchange starts. No wonder it uses so much battery.

**Comment by plittlefield** [comment] 2018-03-13 18:16
OK, so just keep the charger close by for now until a fix? ;-)

**Comment by Catfriend1** [comment] 2018-04-22 20:48
According to https://forum.syncthing.net/t/question-about-restartonwakeup-setting/2222/14 restartonwakeup should be the default setting for syncthing android.

**Comment by Catfriend1** [comment] 2018-04-23 06:51
I am working on the "restartonWakeup" option in the app.

**Comment by Catfriend1** [comment] 2018-04-23 07:33
It's implemented in the UI and migration PR #1051 mentioned above.
Users with an existing configuration can manually toggle restartOnWakeup off in the app UI.
Users creating a new configuration on first start of the app get restartOnWakeup by default.

**Comment by AudriusButkevicius** [comment] 2018-04-23 07:53
Switching it off is not for free. You are trading battery usage for "my syncthing doesn't connect"

**Comment by Catfriend1** [comment] 2018-04-23 07:56
Lets see what new users report back. I am currently testing myself.

**Comment by Catfriend1** [comment] 2018-04-23 15:25
This discourse is over 3 years old, so we should at least give it a try as other users (see post above), calmh and me already found the battery saving the better option to live with on low-power devices. Plus, ignoring android doze syncthing core should not get in the state of being put to "standby" (timer increasing while app is frozen as interpreted by st core) so choosing between restartonwakeup or not is irrelevant to users living on Android 6+. Do you agree on having it easily configurable in the next version? That ensures, no one gets a showstopper when the change is released.

**Comment by AudriusButkevicius** [comment] 2018-04-23 17:14
I agree in it being configurable, yet not disabled by default as the wider effect on all device base is not clear. Ideally this should come with a disclaimer explaining the effects.

If we are not being put into doze, then syncthing shouldn't be restarted, hence should not consume more battery.

**Comment by Catfriend1** [comment] 2018-04-23 18:09
@AudriusButkevicius: ok, I'll update the pr to make it enabled by default so no change is forced on new users. The disclaimer string will also be updated.

**Closed** 2018-04-27 20:24 UTC
Labels: enhancement, pr-welcome
