### ISSUE TITLE
"Failed to create syncthing config¸check the logs" message, SIGSEGV inside

### ISSUE THREAD

**Issue by akamaus** [syncthing/syncthing-android#518] opened 2015-12-13 08:03 UTC
Hello,
I installed syncthing-0.7.5 from playmarket on my Huawei U9500. Upon start I got a white screen and message "Failed to create syncthing config¸check the logs". I downloaded the logs using adb logcat and got this:

```
I/DEBUG   (14067): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (14067): Build fingerprint: 'Huawei/U9500/hwu9500:4.0.3/HuaweiU9500/3.1.11:user/ota-rel-keys,release-keys'
I/DEBUG   (14067): pid: 22101, tid: 22101  >>> /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so <<<
I/DEBUG   (14067): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00dcfe64
I/DEBUG   (14067):  r0 70000001  r1 b00094fc  r2 00000000  r3 00dcfe64
I/DEBUG   (14067):  r4 b000a078  r5 ffffffff  r6 00dcfe64  r7 beaf3aa8
I/DEBUG   (14067):  r8 b0009910  r9 00000000  10 00000000  fp b0006d9b
I/DEBUG   (14067):  ip 0089701b  sp beaf3a68  lr 00896d3c  pc b000421c  cpsr 00000030
I/DEBUG   (14067):  d0  0000000000000000  d1  0000000000000000
I/DEBUG   (14067):  d2  0000000000000000  d3  0000000000000000
I/DEBUG   (14067):  d4  0000000000000000  d5  0000000000000000
I/DEBUG   (14067):  d6  0000000000000000  d7  0000000000000000
I/DEBUG   (14067):  d8  0000000000000000  d9  0000000000000000
I/DEBUG   (14067):  d10 0000000000000000  d11 0000000000000000
I/DEBUG   (14067):  d12 0000000000000000  d13 0000000000000000
I/DEBUG   (14067):  d14 0000000000000000  d15 0000000000000000
I/DEBUG   (14067):  d16 0000000000000000  d17 0000000000000000
I/DEBUG   (14067):  d18 0000000000000000  d19 0000000000000000
I/DEBUG   (14067):  d20 0000000000000000  d21 0000000000000000
I/DEBUG   (14067):  d22 0000000000000000  d23 0000000000000000
I/DEBUG   (14067):  d24 0000000000000000  d25 0000000000000000
I/DEBUG   (14067):  d26 0000000000000000  d27 0000000000000000
I/DEBUG   (14067):  d28 0000000000000000  d29 0000000000000000
I/DEBUG   (14067):  d30 0000000000000000  d31 0000000000000000
I/DEBUG   (14067):  scr 00000000
I/DEBUG   (14067): 
I/DEBUG   (14067):          #00  pc b000421c  /system/bin/linker
I/DEBUG   (14067):          #01  lr 00896d3c  <unknown>
I/DEBUG   (14067): 
I/DEBUG   (14067): code around pc:
I/DEBUG   (14067): b00041fc 6858e00a 208cf8d4 f8c41885 e00350d8  ..Xh... .....P..
I/DEBUG   (14067): b000420c 0895685a 50dcf8c4 e0013308 44794924  Zh.....P.3..$IyD
I/DEBUG   (14067): b000421c 2d00681d af49f47f 30acf8d4 f8d4b113  .h.-..I....0....
I/DEBUG   (14067): b000422c b96110b0 7176f240 9100481e 44784a1e  ..a.@.vq.H...JxD
I/DEBUG   (14067): b000423c 491f4b1e 447b447a 68094479 f8d4e7b1  .K.IzD{DyD.h....
I/DEBUG   (14067): 
I/DEBUG   (14067): code around lr:
I/DEBUG   (14067): 00896d1c ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   (14067): 00896d2c ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   (14067): 00896d3c ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   (14067): 00896d4c ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   (14067): 00896d5c ffffffff ffffffff ffffffff ffffffff  ................
I/DEBUG   (14067): 
I/DEBUG   (14067): memory map around addr 00dcfe64:
I/DEBUG   (14067): (no map below)
I/DEBUG   (14067): (no map for address)
I/DEBUG   (14067): 400fd000-40994000 /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so
I/DEBUG   (14067): 
I/DEBUG   (14067): stack:
I/DEBUG   (14067):     beaf3a28  00000000  
I/DEBUG   (14067):     beaf3a2c  00000000  
I/DEBUG   (14067):     beaf3a30  00000000  
I/DEBUG   (14067):     beaf3a34  00000000  
I/DEBUG   (14067):     beaf3a38  00000000  
I/DEBUG   (14067):     beaf3a3c  00000000  
I/DEBUG   (14067):     beaf3a40  00000000  
I/DEBUG   (14067):     beaf3a44  00000000  
I/DEBUG   (14067):     beaf3a48  00000000  
I/DEBUG   (14067):     beaf3a4c  00000000  
I/DEBUG   (14067):     beaf3a50  00000000  
I/DEBUG   (14067):     beaf3a54  00000000  
I/DEBUG   (14067):     beaf3a58  00000000  
I/DEBUG   (14067):     beaf3a5c  00000000  
I/DEBUG   (14067):     beaf3a60  df0027ad  
I/DEBUG   (14067):     beaf3a64  00000000  
I/DEBUG   (14067): #00 beaf3a68  00000000  
I/DEBUG   (14067):     beaf3a6c  00000000  
I/DEBUG   (14067):     beaf3a70  b000a078  
I/DEBUG   (14067):     beaf3a74  b000a078  
I/DEBUG   (14067):     beaf3a78  beaf3c06  [stack]
I/DEBUG   (14067):     beaf3a7c  00000118  
I/DEBUG   (14067):     beaf3a80  b000a078  
I/DEBUG   (14067):     beaf3a84  b000a078  
I/DEBUG   (14067):     beaf3a88  b00094f0  /system/bin/linker
I/DEBUG   (14067):     beaf3a8c  00000004  
I/DEBUG   (14067):     beaf3a90  beaf3aa8  [stack]
I/DEBUG   (14067):     beaf3a94  b0009910  /system/bin/linker
I/DEBUG   (14067):     beaf3a98  00000000  
I/DEBUG   (14067):     beaf3a9c  00000000  
I/DEBUG   (14067):     beaf3aa0  b0006d9b  /system/bin/linker
I/DEBUG   (14067):     beaf3aa4  b0004849  /system/bin/linker
I/DEBUG   (14067):     beaf3aa8  00000000  
I/DEBUG   (14067):     beaf3aac  00000000  
I/System  (21141): Failed to destroy process 22101
I/BootReceiver(  220): Copying /data/tombstones/tombstone_08 to DropBox (SYSTEM_TOMBSTONE)
I/System  (21141): libcore.io.ErrnoException: kill failed: ESRCH (No such process)
I/System  (21141):      at libcore.io.Posix.kill(Native Method)
I/System  (21141):      at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
I/System  (21141):      at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
I/System  (21141):      at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:136)
I/System  (21141):      at com.nutomic.syncthingandroid.util.ConfigXml.generateKeysConfig(ConfigXml.java:104)
I/System  (21141):      at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:75)
I/System  (21141):      at com.nutomic.syncthingandroid.syncthing.SyncthingService.updateState(SyncthingService.java:234)
I/System  (21141):      at com.nutomic.syncthingandroid.syncthing.SyncthingService.onStartCommand(SyncthingService.java:191)
I/System  (21141):      at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2359)
I/System  (21141):      at android.app.ActivityThread.access$1900(ActivityThread.java:123)
I/System  (21141):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
I/System  (21141):      at android.os.Handler.dispatchMessage(Handler.java:99)
I/System  (21141):      at android.os.Looper.loop(Looper.java:137)
I/System  (21141):      at android.app.ActivityThread.main(ActivityThread.java:4424)
I/System  (21141):      at java.lang.reflect.Method.invokeNative(Native Method)
I/System  (21141):      at java.lang.reflect.Method.invoke(Method.java:511)
I/System  (21141):      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
I/System  (21141):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
I/System  (21141):      at dalvik.system.NativeStart.main(Native Method)
E/SyncthingNativeCode(21141): Syncthing binary crashed with error code 11
W/ConfigXml(21141): Failed to open config, moving to config.xml.invalid and creating blank config
F/libc    (22106): Fatal signal 11 (SIGSEGV) at 0x00dcfe64 (code=1)
I/SyncthingRunnableIoNice(21141): ionice performed on libsyncthing.so
I/System  (21141): Failed to destroy process 22112
I/System  (21141): libcore.io.ErrnoException: kill failed: ESRCH (No such process)
I/System  (21141):      at libcore.io.Posix.kill(Native Method)
I/System  (21141):      at libcore.io.ForwardingOs.kill(ForwardingOs.java:77)
I/System  (21141):      at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:257)
I/System  (21141):      at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable$1.run(SyncthingRunnable.java:183)
```

I looked at app directory with adb shell and saw this:
```
root@android:/data/data/com.nutomic.syncthingandroid # pwd
/data/data/com.nutomic.syncthingandroid
root@android:/data/data/com.nutomic.syncthingandroid # ls -l                   
drwxrwx--x app_121  app_121           2015-12-13 10:13 cache
drwxrwxrwx app_121  app_121           2015-12-13 10:12 files
drwxr-xr-x system   system            2015-12-13 10:12 lib
drwxrwx--x app_121  app_121           2015-12-13 10:12 shared_prefs
root@android:/data/data/com.nutomic.syncthingandroid # ls files
root@android:/data/data/com.nutomic.syncthingandroid # 
```

Originally files mode was 771, I changed it to 777 just to be sure.

**Comment by Zillode** [comment] 2015-12-13 10:31
@calmh @AudriusButkevicius any ideas?

**Comment by moschkom** [comment] 2015-12-15 21:12
Wanted to try out syncthing for android. But ended up with (very likely) this issue. 
Installed the app from the Play Store. Some seconds after start it crashes with the mentioned notification. Where can I find the logs?

**Comment by Nutomic** [comment] 2015-12-16 18:14
@moschkom `adb logcat` on the command line, or with a logcat app.

**Comment by Cd-spb** [comment] 2016-01-21 08:52
Hello,
 I installed syncthing-0.7.6 from F-droid:
"Failed to create syncthing config¸check the logs"
```
I/ConfigXml(11511): App started for the first time. Generating keys and config.
F/libc    (11685): Fatal signal 11 (SIGSEGV) at 0x00e18e68 (code=1)
I/DEBUG   (134): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (134): Build fingerprint: 'SEMC/LT18i_1255-2998/LT18i:4.0.4/4.1.B.0.587/tL1_3w:user/release-keys
```
CatLog:
[2016-01-19-21-58-45.txt](https://github.com/syncthing/syncthing-android/files/98913/2016-01-19-21-58-45.txt)

**Comment by Cd-spb** [comment] 2016-01-21 09:23
As Unrud said:
>I also get error code 11 on Android 4.0.3.
> I compiled  0ce4962  without CGO and it works fine.
https://github.com/syncthing/syncthing-android/issues/515#issuecomment-173401009

**Comment by calmh** [comment] 2016-01-21 20:19
Sounds like a runtime or compiler bug, or possibly some other situation like out of memory that manifests as a segfault...

**Comment by Cd-spb** [comment] 2016-01-22 08:28
May be only on Android 4.0.x?
As akamaus said:
>4.0.3

As Unrud said:
>Android 4.0.3

As pascalfree said:
>Android 4.0.3

As gerroon said:
>are various Android 4xs

My
>4.0.4

Can I help as beta-testing?

**Comment by AlexKolesov** [comment] 2016-01-30 16:47
Any update here? Looks like I have the same problem. Android 4.0.4

**Comment by datgb** [comment] 2016-01-31 17:03
I have the same problem on my Lenovo and my samsung. Seems the developers dont know the solution seeing how they closed this as Fixed when he stated it wasnt fixed. https://forum.syncthing.net/t/fixed-crash-on-android-creating-config-file/6284

**Comment by licaon-kter** [comment] 2016-01-31 21:18
@datgb: What devices? What Android version? Ever used root? (btw, root access is broken)

**Comment by datgb** [comment] 2016-01-31 21:47
I tried on a rooted Samsung tab on 4.4. and didnt work. wont even install. then gives me the error once and locks up my package installer where I need to reset it just to get back into my files.

Also on a lenovo vibez on 4.4 and it installs but doesnt open and gives that error. this is not rooted.

**Comment by licaon-kter** [comment] 2016-01-31 21:51
If it did not install then it's not this issue I guess.
Package from Google Play app or F-Droid?

**Comment by senseicoder** [comment] 2016-02-03 18:59
Android 4.0.3 on Asus Transformer Tablet, installed from Google Play. I will get the log later. Does Syncthing work on any 4.0.3 device ?

**Comment by anton-tsyganenko** [comment] 2016-03-16 07:38
Same problem on Android 4.0.4 with package from f-droid.

**Comment by Nutomic** [comment] 2016-03-16 22:20
I just released a new version with better logging for this kind of error. Can you please try again with that and then open a new issue?

**Comment by alfredbuehler** [comment] 2016-03-19 07:17
I tried with version 0.7.11 on Android 4.0.4: 


```
03-19 08:01:52.710 I/SyncthingService(3310): Generated GUI username and password (username is GTS7562)
03-19 08:01:52.710 I/dalvikvm(3310): Could not find method android.net.ConnectivityManager.isActiveNetworkMetered, referenced from method com.nutomic.syncthingandroid.syncthing.DeviceStateHolder.<init>
03-19 08:01:53.920 I/DEBUG   (99): pid: 3330, tid: 3330  >>> /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so <<<
03-19 08:01:54.020 I/DEBUG   (99): 40000000-408c8000 /data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so
03-19 08:01:54.470 W/SyncthingNativeCode(3310): sh: <stdin>[1]: grep: not found
03-19 08:02:02.800 I/System  (3310): 	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:157)
03-19 08:02:02.800 I/System  (3310): 	at com.nutomic.syncthingandroid.util.ConfigXml.generateKeysConfig(ConfigXml.java:104)
03-19 08:02:02.800 I/System  (3310): 	at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:75)
03-19 08:02:02.800 I/System  (3310): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask.doInBackground(SyncthingService.java:358)
03-19 08:02:02.800 I/System  (3310): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask.doInBackground(SyncthingService.java:346)
03-19 08:02:02.880 E/AndroidRuntime(3310): Caused by: java.lang.RuntimeException: Syncthing binary crashed with error code 11, output:
03-19 08:02:02.880 E/AndroidRuntime(3310): 	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable.run(SyncthingRunnable.java:147)
03-19 08:02:02.880 E/AndroidRuntime(3310): 	at com.nutomic.syncthingandroid.util.ConfigXml.generateKeysConfig(ConfigXml.java:104)
03-19 08:02:02.880 E/AndroidRuntime(3310): 	at com.nutomic.syncthingandroid.util.ConfigXml.<init>(ConfigXml.java:75)
03-19 08:02:02.880 E/AndroidRuntime(3310): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask.doInBackground(SyncthingService.java:358)
03-19 08:02:02.880 E/AndroidRuntime(3310): 	at com.nutomic.syncthingandroid.syncthing.SyncthingService$StartupTask.doInBackground(SyncthingService.java:346)
03-19 08:02:03.250 W/SyncthingNativeCode(3310): usage: ionice <pid> [none|rt|be|idle] [prio]
03-19 08:02:03.290 I/SyncthingRunnableIoNice(3310): ionice performed on libsyncthing.so
03-19 08:02:03.290 I/System  (3310): 	at com.nutomic.syncthingandroid.syncthing.SyncthingRunnable$1.run(SyncthingRunnable.java:208)
03-19 08:02:03.290 E/SyncthingRunnableIoNice(3310): Failed to set ionice 1

```

**Comment by janblau** [comment] 2016-03-19 09:07
I also tried with version 0.7.11 on Android 4.0.4 and got the:same issue.

Syncthing version 0.7.4 was the last version that worked.

I do'nt know how to get a log to send it to you

**Comment by AudriusButkevicius** [comment] 2016-03-19 12:38
So the thing that changed in 0.7.5 is this:
https://github.com/syncthing/syncthing-android/commit/a05fa80470f83fde9d25bda3f3ade351e417f1e0

And I am sure that this is the cause of all of the problems.

**Comment by Nutomic** [comment] 2016-03-19 14:52
I just tested, and DNS seems to work with the normal Go compiler! That means we can switch back, and probably get rid of all these crashes :)

**Comment by janblau** [comment] 2016-03-20 08:24
In fact i have 3 android devices (1 tablet and 2 phones): one under android 4.0.4, one under android 4.4 and one under android 5.0.
Syncthing 0.7.11 works like a charm on all of them except the one under android 4.0.4.

**Comment by janblau** [comment] 2016-03-20 08:26
I'll make an adb logcat of the issue asap and send it here

**Comment by janblau** [comment] 2016-03-20 14:08
Here is the result of "adb logcat *:E

[syncthingPeax.txt](https://github.com/syncthing/syncthing-android/files/181318/syncthingPeax.txt)

**Comment by Nutomic** [comment] 2016-03-20 19:11
This and other crashes should be fixed in the next version, as we switch back from the cgo compiler to the standard go compiler. #590.

**Comment by janblau** [comment] 2016-03-25 13:11
I tried last version (0.7.12) on the android 4.0.4 phone: it works !!!
Thank you so much. You are very reactive and efficient. Good job guys.

**Closed** 2016-03-26 17:30 UTC
Labels: bug
