### ISSUE TITLE
Run condition ignored, 3Gb of mobile data shredded

### ISSUE THREAD

**Issue by madduck** [syncthing/syncthing-android#1873] opened 2022-12-04 11:29 UTC
I have a remote that's on a public IP, but I've configured Syncthing-Android to only run when on Wifi (see screenshot below).

Unfortunately, yesterday, however, Syncthing shredded through 3Gb of mobile data (2nd screenshot below).

At first I was thinking that this might be due to tethering, because I was in fact connected to the Internet from my laptop via the phone's hotspot. However, I've not been able to reproduce this issue, i.e. if I enable the hotspot and connect my laptop, then Syncthing will not run while the Internet is accessible via mobile.

I am running the DuckDuckGo VPN for app tracking protection, but it does not block non-VPN connections, so #1822 should not apply.

I'd love to help find the bug here, assuming there is one. I am not keen on reproducing the problem, but maybe there is some information I can make available in retrospect? Or what can I do to prepare the right log channels for the case that this ever happens again, and I can thus provide more information?

Or am I overlooking something, and there's a simple explanation?

Thanks,
Martin

### Version Information

    App Version: 1.22.1.1
    Syncthing Version: v1.22.2-dev-1.g15c0afec
    Android Version: Android 13 / GrapheneOS

#### Syncthing run conditions — wifi only

![Screenshot_20221204-121727](https://user-images.githubusercontent.com/195073/205487451-b707ade3-a592-4b92-aa67-02697234fede.png)

#### Syncthing shredding through data

![Screenshot_20221204-121953](https://user-images.githubusercontent.com/195073/205487567-a1307987-f87a-4a85-97fb-bf9d86de632e.png)

**Comment by tomasz1986** [comment] 2022-12-04 14:03
> Or am I overlooking something, and there's a simple explanation?

Known bug which has already been fixed (see https://github.com/syncthing/syncthing-android/issues/1852), very unfortunate sadly. It happened only upon upgrading to your currently used version, so it shouldn't repeat itself again, but if you want to be extra sure, you can upgrade to the current pre-release of v1.22.2. The new stable release should be coming soon too.

**Comment by imsodin** [comment] 2022-12-04 14:53
Yep, duplicate of #1852 indeed. And no need to upgrade, it can only happen on first start. As soon as any run conditions change or you restart, the problem is gone.

**Closed by imsodin** 2022-12-04 14:53 UTC

**Comment by madduck** [comment] 2022-12-04 15:51
Thanks guys, and sorry I failed to find the existing issue. The harm done isn't so bad, just a few Euros, so no worries. Thank you for your hard work on this amazing software!
