### ISSUE TITLE
syncthing Android crashes when I do just about anything

### ISSUE THREAD

**Issue by megodoonch** [syncthing/syncthing-android#1483] opened 2020-03-09 15:12 UTC
The syncthing app crashes constantly if I try to interact with it. Usually it's when I use another app while syncthing is running, and then try to return to syncthing. First there is a blank syncthing window, and then the screen goes black. Eventually I get a notification that it has crashed. Before that I can't close it, and sometimes it freezes the phone. 

This issue is so pervasive I can't even narrow down any further what triggers it, I'm sorry.

### Version Information

    App Version: 1.3.4
    Syncthing Version: v1.3.4
    Android Version: Android 8.0.0

**Comment by AudriusButkevicius** [comment] 2020-03-09 19:11
I think this is a duplicate of https://github.com/syncthing/syncthing-android/issues/1421

**Closed by AudriusButkevicius** 2020-03-09 19:11 UTC
