### ISSUE TITLE
Receive only folder

### ISSUE THREAD

**Issue by rominail** [syncthing/syncthing-android#1214] opened 2018-08-10 17:38 UTC
Hi guys,

I crawled the github issues and a bit of internet, particularly documentation on syncthing.net, from the 0.14.50 version on laptop, it's possible to set folder mode as receive only, is it the case for android app or will it be in next version?

Thanks guys you working well, one of the most useful app ;)

**Comment by AudriusButkevicius** [comment] 2018-08-10 18:46
Next version as 0.14.50 is not released yet.

**Comment by Catfriend1** [comment] 2018-08-11 21:08
You can try a release candidate 14.50.rc.1 in the current gplay beta channel but be careful as the receiveOnly stuff is still very young. Backup your important data first before trying beta builds.

**Comment by Catfriend1** [comment] 2018-08-11 21:58
Duplicate of https://github.com/syncthing/syncthing-android/issues/1210

**Closed** 2018-08-18 08:29 UTC
