### ISSUE TITLE
Shared folders are read-only on sd card  (<29) and inaccessible on all ext. storage (>=29, ~November 2020)

### ISSUE THREAD

**Issue by jonnojohnson** [syncthing/syncthing-android#29] opened 2014-06-05 16:06 UTC
SyncThing works great for repositories created on the internal SDCard. However if I try to create a rep on my external SDCard it doesn't complain. The other node attempts to sync & just shows sync progress set at 0%.
I'm running Android 4.4.2 on a GS4 & I know external SD card access for apps got restricted more since 4.4 but I think SyncThing is one of those apps where it makes complete sense to have ext SD access.
In the short term perhaps SyncThing for Android could complain if ext SD card access is not an option?

**Comment by cattledogit** [comment] 2015-01-29 16:20
First install of syncthing so have 0.5.6. Hope I'm posting in the right place.

Though I've made the required change to platform.xml per http://tinyurl.com/l3e8jod so that apps can access any folder on the ExtSD, and ES File Mgr. can edit all folders w/o granting it root access, syncthing can only access files in /storage/extSdCard/Android/data/com.numotic.syncthingandroid/files. This is useless though because Astro Player can't see media files in com.numotic.syncthingandroid, though it can see all non-data/com... folders.

Galaxy Note 2 with 4.4.2.

**Comment by Nutomic** [comment] 2015-01-29 16:30
@cattledogit At least `/sdcard/` should be available for syncthing. You can also select the advanced folder picker in settings and select any folder.

**Comment by cattledogit** [comment] 2015-01-29 19:50
> You can also select the advanced folder picker in settings and select any folder.

Thanks, fixed that problem for extSdCard.

**Comment by GRMrGecko** [comment] 2015-11-10 04:10
I just got a Nexus 6P and had an issue where it couldn't write to anywhere in the "SD Card", I'm assuming maybe a folder specific for the app would be allowed but I wanted it on the "SD Card". I found out how to fix by going to Settings->Apps->Syncthing->Permissions->Storage. Thought I'd post this here for people who are also having this issue.

**Comment by Nutomic** [comment] 2015-11-11 23:51
@GRMrGecko That would be #483. There's a workaround in 0.7.1.

**Comment by taaem** [comment] 2015-11-19 09:20
So no news on implementing the Storage Access API on Lollipop? Or is it still impossible to do because of the go language?

**Comment by wweich** [comment] 2015-11-19 10:48
@GRMrGecko your phone does not have an external sd card, so your problem (as Nutomic pointed out) has nothing to do with this issue here.

@taaem With Android 6 you can have full access to the external sd card like you have with the "internel sd card". So this issue will probably loose priority.

**Comment by necr0potenc3** [comment] 2015-11-29 04:18
This issue can be remediated (it's a hack, not a fix) by manually creating ".stfolder" file in external storage.

**Comment by Nutomic** [comment] 2015-11-29 17:38
@necr0potenc3 That only works for read-only folders though. Syncthing will not be able to write anything.

**Comment by tkedwards** [comment] 2016-01-05 09:00
It's really frustrating that Google put restrictions on using external SD cards like this, but the good news seems to be that the 'Adoptable Storage' feature in 6.0 should resolve this.
@Nutomic have you been able to test this yet on an Android 6 device using adoptable storage? Do you think it'll resolve this problem?

**Comment by wweich** [comment] 2016-01-06 15:45
Just tested this with my Moto X Style. After adding the card and setting it up as "internal storage" `/storage/emulated/0/` is the SD card and the internal storage seems to be not accessible for storage access anymore.
So only Apps and data they place inside the "App partition" and not on the "storage partition" are located on the internal storage.

**Comment by NYPD** [comment] 2016-01-06 16:21
As others have pointed, creating a folder named "com.nutomic.syncthingandroid"
`extSdCard/Android/data/com.nutomic.syncthingandroid`

Does allow syncthing to do its thing. I'm able to sync a large music collection under
`extSdCard/Android/data/com.nutomic.syncthingandroid/Phone Music`

So at least this is an option for some perhaps.

**Comment by wweich** [comment] 2016-01-06 16:39
Does syncthing have write permission inside that folder?
Do you know, if that is the default Android behaviour, or if perhaps your manufacturer changed Android to allow that?

**Comment by Kernald** [comment] 2016-01-06 16:49
Applications always had the ability to write on their external storage dedicated folder, at least up to 5.1 (I don't know for Android 6). However, I think read access to that folder is restricted from other applications.

**Comment by NYPD** [comment] 2016-01-06 21:30
The application I used to play the music from the `extSdCard/Android/data/com.nutomic.syncthingandroid/Phone Music` folder is GoneMad Music player. So perhaps some application are not able to read data in there, but luckily for me my music player is able to.

**Comment by Nutomic** [comment] 2016-01-17 23:05
You don't have to create the `Android/data/com.nutomic.syncthingandroid/` folder yourself, you can just select it in the app when creating a new folder ;)

One caveat about these folders is that they will be deleted when you uninstall Syncthing.

**Comment by alexforencich** [comment] 2016-01-23 00:59
This is a serious showstopper issue.  However, this page appears to inicate that there is a way for apps to explicitly request write access on android 5.0: https://metactrl.com/docs/sdcard-on-lollipop/ .  If it is possible to implement this in syncthing, then this could be an effective solution for this issue.

**Comment by bservet** [comment] 2016-01-26 12:47
I thought that Syncthing couldn't write to an external sdcard because the underlying framework was missing a needed feature?

With my phone (5.01) Syncthing seems to refuse writing to the /storage/extsdcard/music folder, or should this be supported with the current version?

**Comment by Kugeleis** [comment] 2016-03-21 20:12
I can confirm that using a folder as master (read only) it works copying a .stfolder file to this folder manually using ES file explorer. It starts syncing after a restart. I have a non-rooted Android 5.1.1.

**Comment by francescortiz** [comment] 2016-04-24 11:32
@Kugeleis hack works for me too with android 5.0.2

**Comment by vext01** [comment] 2016-04-26 21:48
The hack did not work on my LG-G4. Permission denied apparently.

**Comment by dper** [comment] 2016-04-26 22:10
I have a rooted 5.1. It seems like Syncthing can (at least sometimes) do the initial file transfer but after that will not write anything. The changes are visible in the web client on my desktop, and they /look/ like they're getting pushed, but in reality no. Then, if I try browsing to that folder using an Android file manager, the file manager freezes.  In this case, I have a directory just under `extSdCard`, and am not using the `Android` subdirectory.

**Comment by Kugeleis** [comment] 2016-04-27 09:11
@vext01: Did you use ES-explorer? This tool handles the write protection correctly when copying files.

**Comment by vext01** [comment] 2016-04-27 09:18
I used the built-in file manager on my G4.

Regardless I think the bug is that not any arbitrary directory on the SD can be synced. Users (including myself) don't want to rely on obscure hacks to get things working.

**Comment by AudriusButkevicius** [comment] 2016-04-27 09:24
Right, tell that to Google, who's own programming language is unable to access SD cards on their own OS.

**Comment by vext01** [comment] 2016-04-27 09:25
Agreed.

**Comment by vext01** [comment] 2016-04-27 09:41
Out of interest (I know very little about android internals), how is it the file manager app can write the SD card? It has some special credentials?

**Comment by Nutomic** [comment] 2016-04-27 09:56
It's written in Java, that's all. The problem is that Go doesn't support this.

**Comment by vext01** [comment] 2016-04-27 10:11
Ah. So, would it be possible (and I know it's awkward) to write a little Java proxy which could do file access on Syncthing's behalf?

I'm not sure how hard that is. Can you invoke Java code from go? Otherwise you would have to use some form of IPC I guess.

**Comment by dper** [comment] 2016-04-27 10:37
@vext01 Dealing with badness in Android 5.1 and external storage is not unique to this app, so your question is one that could be asked in a more general forum. And unfortunately (or fortunately?) Android 6 is different, or so I read. There's a question of how much time developers want to or should spend working around these regrettable decisions made by upstream Android developers, particularly if it's specific to Android 5.1. I would imagine it's not a particularly fun or interesting pursuit.

Sadly, this means some of us with Android phones running 5.1 have to deal with workarounds and fixes, such as they exist. But hey, it is what it is.

**Comment by vext01** [comment] 2016-04-27 10:53
Thanks. I'll hold out for a 6 update and see what happens then.

**Comment by wweich** [comment] 2016-04-27 11:14
With Android 6 you can choose to use the SD Card as main storage, instead of the internal storage.
If you do that, you will have no access to the internal storage anymore. File Managers will only see the SD Card. `/storage/emulated/0/`, `/sdcard/` and `/mnt/sdcard/` will all point to the SD Card, not the internal storage.
In some apps you will be able to set where to store the (offline) data (e.g. Google Play Music); some will use the SD Card (e.g. Spotify).

**Comment by Nutomic** [comment] 2016-04-27 11:15
@wweich Isn't the change in Android 6 that you can combine internal and external storage into a single storage? So you can still use both, but it's treated like a single partition.

**Comment by Kernald** [comment] 2016-04-27 12:20
@Nutomic yes, it's the feature named "adoptable storage". However, some device makers choose to not integrate it in their Marshmallow versions. I think it's the case on the Galaxy S7, for example.

**Comment by wweich** [comment] 2016-04-27 12:34
I have a Moto X Style (which AFAIK is one of the most stock like devices with SD Card), and with this device it is like I described.

My storage overview looks like this:
![screenshot_20160427-143208](https://cloud.githubusercontent.com/assets/1026763/14852173/0232e81e-0c85-11e6-9236-0d12c975c209.png)

**Comment by wweich** [comment] 2016-04-27 12:45
According to the [official doc](https://source.android.com/devices/storage/adoptable.html), my Moto X is using "adoptable storage" and I also got the "erase & format" prompt as described in [this Android Central article](http://www.androidcentral.com/inside-marshmallow-adoptable-storage).
The doc says nothing about if the normal storage (internal) can still be used as before or if both storages are merged.

Apps can still store their data in either place (like the current version of Play Music can (the older one could only use internal)).

**Comment by Kernald** [comment] 2016-04-27 13:01
From what I see (on a Shield Tablet K1), you can move an application from the internal storage to the external one as you see fit. However, any application is able to write on the external storage as it was possible before Android 5 (or was it 4.4?). I just tested syncthing on it, and I was able to *write* files to my SD card.

**Comment by wweich** [comment] 2016-04-27 13:16
Yeah, moving apps between internal storage and SD Card is possible. But I never did that, as the internal is faster and has plenty of space left.
But can you access your internal storage with a file manager like Total Commander, ES Explorer or the like? And can you Sync files with Syncthing to internal storage?

**Comment by Kernald** [comment] 2016-04-27 13:21
I can't find anything related to the internal storage. I see a `/data` folder (I see it empty, but I simply don't have the permissions to see what's inside, I think), but anything in `/mnt` and the likes point to the same place. I think (but I'm not even sure) the files here are physically stored on the SD card. However, I guess that if the SD card gets full, the system will transparently begin to use the internal storage, without telling anything. That's, at least, how it's advertised - a single, merged space, using two physical supports behind the scenes.

**Comment by bminer** [comment] 2016-05-19 01:22
Possible workaround is to install SDFix (assuming you have root access).  Sometimes running Syncthing with root access is a bit buggy.

Links to SDFix are below:
- http://forum.xda-developers.com/showthread.php?t=2684188
- https://play.google.com/store/apps/details?id=nextapp.sdfix

**Comment by herdz** [comment] 2016-05-23 07:33
Joining in with my 5.0 android device. Nothing works for extSDCard path.

**Comment by herdz** [comment] 2016-05-23 08:32
OK, looks like only via the webui I am able to sync on the extSDCard. The toggle button in the application itself doesn't work.

**Comment by wweich** [comment] 2016-05-23 09:11
There is no toggle button for extSDCard. Are you talking about #647 ?

**Comment by herdz** [comment] 2016-05-23 09:41
@wweich, yes I mean the folder setting's toggle button, if the folder is created by the device (as opposed to being shared). This doesn't work.

**Comment by skasync** [comment] 2016-06-03 08:25
Looks like nobody mentioned it so far:

would the snippets of the second answer help to gain write access to the external SD card the traditional way?

http://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop

I mean, you use the current code to try to write to /sdcard/external/path_choosen, get denied, try ACTION_OPEN_DOCUMENT_TREE to gain permission for the whole SDcard (or just the subdir to be created / shared), and on success -> can access  /sdcard/external/path_choosen with the code already in the app probably?

**Comment by Nutomic** [comment] 2016-06-03 09:26
@skasync No, because it doesn't work with the normal File APIs, but with special classes (which Go doesn't support).

**Comment by taaem** [comment] 2016-08-06 19:12
@Nutomic I had an idea but I don't know if its doable, what if one would create a virtual filesystem that would get mounted to /storage/emulated/0/... and everytime syncthing tries to create or read a file from there Syncthing gets that file via the Android File API.

**Comment by AudriusButkevicius** [comment] 2016-08-06 19:48
It's probably easier just to implement android file api support in go...

**Comment by jebeld17** [comment] 2016-10-02 16:07
> Hey all, in KitKat we introduced APIs that let apps read/write file in app-specific directories on secondary storage devices, such as SD cards.
We heard loud and clear that developers wanted richer access beyond these directories, so in Lollipop we added the new ACTION_OPEN_DOCUMENT_TREE intent. Apps can launch this intent to pick and return a directory from any supported DocumentProvider, including any of the shared storage supported by the device. Apps can then create, update, and delete files and directories anywhere under the picked tree without any additional user interaction. Just like the other document intents, apps can persist this access across reboots.
This gives apps broad, powerful access to manage files while still involving the user in the initial selection process. Users may choose to give your app access to a narrow directory like "My Vacation Photos," or they could pick the top-level of an entire SD card; the choice is theirs.

- Google @ Developer Conference 2014

**Comment by jebeld17** [comment] 2016-10-02 16:12
Requesting Permissions at Run Time:
[https://developer.android.com/training/permissions/requesting.html](url)

Run-down:
[http://stackoverflow.com/questions/33139754/android-6-0-marshmallow-cannot-write-to-sd-card](url)

**Comment by capi** [comment] 2016-10-02 17:28
@jebeld17 Yes, we are aware of the DocumentProvider API, the problem being that the Syncthing native binary is not aware of it. There are now some fixes in recent Go versions, but it'll take some time until the native binary can/will support it. The issue at hand is, that the Syncthing for Android application is basically a wrapper around the native binary, which is developed in Go and is cross-platform. And this binary has its limitations regarding Android.

**Comment by adarazs** [comment] 2016-10-07 11:16
This is the 3rd time in 2 years I found this software, got super excited that I can replace Dropbox & DropSync and then ran into this issue. Of course everything that's worth syncing is on the SD card in my phone because the internal storage is small, so videos, pictures, music, etc. are on the external storage.

It blows my mind that this is not the number one problem of this project being worked on non-stop, instead being open since 2+ years. This looks like such an amazing project otherwise, but it's completely useless for me and probably a bunch of others without this fix. :(

**Comment by AudriusButkevicius** [comment] 2016-10-07 11:20
Go complain about this to the go team, we have very little control around this.

**Comment by generalmanager** [comment] 2016-10-07 11:25
If you had read and understood all the intricacies of this issue, you
might not be so judgemental. There are also multiple workarounds and
cases presented in this thread which may or may not work for you. The
main roadblocks are upstream, so you might want to participate in those
projects instead of throwing a tantrum.

**Comment by adarazs** [comment] 2016-10-07 12:24
Looks like this is a sensitive issue for the developers too. Sorry for bothering by adding my voice here as a potential but again disappointed user. I wanted to express that there are people who care about this problem strongly. Syncthing seems to be the only good open source solution for the syncing problem everyone is having and the Android app is a key part of it, and the external SD cards as well.

I saw the workarounds and fixes in the thread, they don't work for me. I don't have root and I can't convert my SD card into adoptable storage.

I understand the limitations are there because of go, however if a problem is literally impossible to fix with a tool used for a task it might mean not using the right tools. 3 years after the release of KitKat, 2 years after the issue being open, with $600 bounty going for the go fix and nobody even wanting to touch it, it might be time to rethink the ways to solve this apart from saying it's impossible.

I'm not an Android or go developer, so this is just an idea: would it be possible to write the storage driver part outside the go app and use a storage abstraction to handle the file operations?

**Comment by capi** [comment] 2016-10-07 12:53
It would technically be possible, if either Syncthing itself provided a way to have "external" storage (i.e. a means for external processes to provide list/read/write operations) or the whole Syncthing protocol (BEP) was re-implemented in Java/Android. The later would be a complete re-implementation of what Syncthing does and given that currently mostly only @Nutomic works on the Android part, it's not something that's likely going to happen.

At the moment it still looks more promising hoping that upstream Go will add proper support which is usable to us, so that we can continue to use the native Syncthing binary.

**Comment by frispete** [comment] 2016-10-07 13:28
Although @Nutomic already did, here's the reference to the root issue again: https://github.com/golang/go/issues/10588.

**Comment by Nutomic** [comment] 2016-10-29 12:49
If anyone wants to work on fixing this issue: It is now possible to [call Android APIs from Go](https://github.com/golang/go/issues/16876). With that, it should be possible to write a wrapper around the [relevant Android APIs](https://developer.android.com/guide/topics/providers/document-provider.html#client). This wrapper can then be used by Syncthing.

**Comment by capi** [comment] 2016-10-30 19:40
But it would have to be added in the Syncthing binary, right? Nothing we can do on the Android side at the moment?

**Comment by AudriusButkevicius** [comment] 2016-10-30 19:43
Correct, and it needs quite a big revamp @calmh was working on to be able to support it on the syncthing side too.

**Comment by dionorgua** [comment] 2016-11-15 12:22
Hi,

There is a way to convert 'SD card' to adoptable storage on Samsung S7 (and probably all other Android 6 devices) without root. Just a few adb commands.

But could anybody confirm that converting SD card to adoptable storage will allow syncthing to write to such 'adoptable' storage?

**Comment by dper** [comment] 2016-11-15 12:26
@dionorgua It is my understanding that some manufacturers have removed adoptable storage from their (Android 6) builds for various devices.

**Comment by dionorgua** [comment] 2016-11-15 12:36
Samsung removed it only from UI. But you can convert it using adb. Don't want to advertise here, just google 'Samsung S7 adoptable storage'. Probably same for others.

**Comment by wweich** [comment] 2016-11-15 13:09
I've used adoptable storage on a near stock device (Moto X Style/Pure), so I don't know how it is on Galaxy S7.
But on that device, you cannot use both internal and SD card at the same time. In the UI, you have to migrate the data to the sd card. Then `/storage/emulated/0/` will point to the sd card and no file explorer app (or Syncthing) can access the real internal storage anymore.

That way, Syncthing can write to sd card without problems.

As you seem to have to have an S7 and used that method, why don't you try it and confirm for us if it works.

**Comment by dionorgua** [comment] 2016-11-15 13:35
I've not used it (yet). Just discovered that it's possible to enable 'adoptable storage'. Since it'll erase everything on SD card I need to be ready for this.
 
In any case thanks for confirmation that syncthing works with adoptable SD card.

**Comment by dper** [comment] 2016-11-16 22:22
On the Samsung Galaxy Note 4, using `adb` I just enabled adoptable storage. As described above, now `/storage/emulated/0` points to the SD card, and the real internal storage isn't used. It wastes storage space, but it successfully works around this bug.

**Comment by wweich** [comment] 2016-11-16 23:11
I used a 64GB card in my 32GB phone. But as the system and Apps are still on the phone memory, my usable space more than tripled.
Also, in some Apps (like Google Play Music or Spotify) you can choose where the offline data should be stored. That way, you have options to use both storage spaces.

**Comment by jult** [comment] 2016-12-01 09:23
What I find to be really strange is that I used to run syncthing silently in the background on my rooted Samsung Galaxy S3, it synced all my preferred external sdcard directories without a glitch for months, never an issue. Now android has 'upgraded' and syncthing doesn't do that anymore? What a sad sad way to go for android. Really, have they killed such basic functionality in favor of security theatre, or what's the reason for this change?

**Comment by dper** [comment] 2016-12-01 10:33
@jult That kind of thing is outside the scope of this issue. :-/ Here we're just trying to figure out how syncthing should handle the current situation, regardless of why it came about.

**Comment by licaon-kter** [comment] 2016-12-01 12:47
@jult That's an old device, what Android upgrade did you make?

**Comment by frispete** [comment] 2016-12-01 16:12
@jult Yes, security theatre obscure. 

Isn't it quite interesting, that google phones doesn't come with an sd card slot, hence their users don't have this problem... This is further obscured, that the choice of implementing syncthing in go is the major blocker in this respect. Needless to say, that go is a - google innovation - too. 

This is a perfect recipe for damaging the last remains of a good reputation.

**Comment by Nutomic** [comment] 2018-01-26 15:14
There was a [post on the forum](https://forum.syncthing.net/t/writing-to-external-sd-card-in-android-5-0-and-above/2492/75?u=nutomic) with an idea how this could be solved, but afaik no one is working on this.

Some related discussion is in #1008.

**Comment by Catfriend1** [comment] 2018-04-22 21:00
Syncthing 0.10.6+ supports sdcard write access when root privs are granted.
Without root privs, theres a way to patch with https://github.com/Catfriend1/tingle - be careful about this and backup first! (Can be unstable but already worked for me)

**Comment by Catfriend1** [comment] 2018-04-23 05:42
@lkwg82 It should not basically be needed to patch the os deeply to just run this app. Its much easier and common to use root. It is a PR for for the original tingle already. There is an explanation how it works.

**Comment by capi** [comment] 2018-05-27 18:19
@Catfriend1 I'd vote to keep this issue open. The current solutions are for rooted and for very advanced users only. Having a synchronization tool run for the "ordinary" user should not require any such things. Therefore I still think that this issue is still open.

My benchmark here is: it still doesn't work on my dad's phone, who I neither will root nor patch his OS :-)

**Comment by AudriusButkevicius** [comment] 2018-05-27 18:34
Sorry, I don't see a reason why this was closed in the first place. Sure, it works with root, but that's a workaround, not a solution.

**Comment by Catfriend1** [comment] 2018-08-06 16:08
Hmm the issue should stay open but honestly will never be totally fixed...

**Comment by AudriusButkevicius** [comment] 2018-08-06 17:26
Sure, that doesn't mean the issue does not exist.

**Comment by imsodin** [comment] 2019-08-11 10:08
Status update (please correct if I got anything wrong):

It looks like this problem will become even more urgent, as currently it looks like google will pull trough on introducing scoped storage in SDK 29, which is planned to become mandatory in the play store by November 2020. This means Syncthing can only access files it created itself or that resides in it's "own dir" (some directories in deeply-nested structures like `.../Android/data/com.nutomic.syncthing-android` and the like). At that point not even the current read-only workaround will work on any storage. For Syncthing to stay viable in a non-root context we need either a change of mind by google (I'd say unlikely), someone taking up the java implementation of Syncthings protocol (https://github.com/syncthing/syncthing-lite) or giving go-bindings a try to implement filesystem access through android APIs. A first step towards the last would be to run Syncthing with bindings instead of as a binary with the recently added "library-interface". In case anyone tries, you currently need to vendor dependencies (`go mod vendor`) until https://github.com/golang/go/issues/27234 is fixed.

**Comment by Catfriend1** [comment] 2020-07-07 23:17
For everyone brought here in 2020: The current discussion about Android 11 being expected to be the first version since 4.4 supporting writing to sdcard again is here: https://forum.syncthing.net/t/android-11-all-files-access-for-the-syncthing-app

**Comment by imsodin** [comment] 2022-04-17 09:40
As mentioned above the restrictions have changed, such that on Android >= 11 Syncthing can now write to SD cards. This issue was thus fixed by https://github.com/syncthing/syncthing-android/issues/1721 which made use of this new policy, and that was released in https://github.com/syncthing/syncthing-android/releases/tag/1.19.0.

**Closed** 2022-04-17 09:40 UTC
Labels: bug, android-restriction
