### ISSUE TITLE
Web interface fails to load after upgrade to 1.26.0

### ISSUE THREAD

**Issue by o-alquimista** [syncthing/syncthing-android#1996] opened 2023-11-07 16:17 UTC
The interface keeps trying to load forever, and never fully completes it. It appears to refresh the page every couple of seconds, and also briefly changes the translation from English to Portuguese. See attached video.

https://github.com/syncthing/syncthing-android/assets/25424263/657f0a3e-3c1e-45bd-99d9-5b7e1b5671fb

It was not reproducible in 1.23.7.

### Version Information
- App Version: 1.26.0 (Play Store)
- Syncthing Version: v1.26.0
- Android Version: Android 12
- Phone model: Nokia 5.4 (arm64)

**Comment by imsodin** [comment] 2023-11-07 16:56
Duplicate of https://github.com/syncthing/syncthing-android/issues/1995

**Closed by imsodin** 2023-11-07 16:56 UTC

**Comment by o-alquimista** [comment] 2023-11-07 17:01
@imsodin I cleared the cache, and the problem persists. Are you sure it's the same bug?

**Comment by tomasz1986** [comment] 2023-11-07 17:49
> I cleared the cache, and the problem persists. Are you sure it's the same bug?

Likely the same culprit, please check https://github.com/syncthing/syncthing-android/issues/1995#issuecomment-1799335883.
