### ISSUE TITLE
Nexus 6p: App crashes on adding new device

### ISSUE THREAD

**Issue by wolpert** [syncthing/syncthing-android#690] opened 2016-06-30 14:51 UTC
Nexus 6P, stock image, up-to-date. On fresh install, hitting the '+' sign in device tab causes it to crash every time. Does not happen on Nexus 10, stock, up to date. (Only two devices I tried it on so far)

**Comment by licaon-kter** [comment] 2016-06-30 17:33
Source, F-Droid or Google Play store?

Get logs from the app Settings page, both app an Android.

**Comment by brianmay** [comment] 2016-06-30 21:44
I have seen this too. Source Google Play store. Will try getting logs, so far don't see  anything useful - I think the crash might be preventing it from saving any logs.

**Comment by fr34kyn01535** [comment] 2016-07-01 17:03
Same happens to me on LG G5 using the builds on F-Droid, all builds prior to 0.7.20 are fine, seems like a bug has sneaked into this version.

**Comment by someonex** [comment] 2016-07-02 18:24
Have the same crash on a Nexus 6P. Here's the android log: [syncthingcrash.txt](https://github.com/syncthing/syncthing-android/files/344670/syncthingcrash.txt)

**Comment by ilanbe** [comment] 2016-07-03 09:03
Same problem :
syncthing version : 0.13.7 - Source Google Play store, new install 
LG G4 - Android 6.0

**Comment by wolpert** [comment] 2016-07-03 16:19
My rev was installed from Google Play. I'll check to see if my logcat gives anything different then aomeonex.

**Comment by wolpert** [comment] 2016-07-03 16:31
Here's the gist...
https://gist.github.com/wolpert/cb8175c5d574dc948fd899612dc01d30
Just did a fresh install of syncthing from google play store on my stock nexus 6p, OS version is 6.0.1, June 1 2016 security patch level.
Google play says its updated on June 27, 2016, version 0.7.21. (The comments on the page say syncthing update to 0.13.7)

I opened the app, went to devices and hit the plus. Got the failure you see here. No matter what I do on this device, I get this error. It doesn't happen on the nexus 9 with the same version of syncthing.

**Comment by jakubciepiela** [comment] 2016-07-03 19:46
I am seeing the same problem on Samsung S6 Edge.
Not only it crashes when trying to add new device. It crashes when i try to add device from my laptop using phone device's id.

**Comment by afxgit** [comment] 2016-07-08 06:33
Same issue on Galaxy Note 4 running 5.1.1  - are there any steps to supply required logs for troubleshooting?

**Comment by m33p** [comment] 2016-07-09 05:18
--------- beginning of crash
07-08 23:52:14.497 13594 13594 E AndroidRuntime: FATAL EXCEPTION: main

07-08 23:52:14.497 13594 13594 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 13594

07-08 23:52:14.497 13594 13594 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.SettingsActivity}: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5422)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Binary XML file line #49: Error inflating class EditText

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at com.nutomic.syncthingandroid.fragments.DeviceFragment.onCreateView(DeviceFragment.java:203)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2220)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.FragmentController.execPendingActions(FragmentController.java:325)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:6267)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	... 9 more

07-08 23:52:14.497 13594 13594 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #49: Error inflating class EditText

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	... 19 more

07-08 23:52:14.497 13594 13594 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_tag_text_outline_black_24dp.xml from drawable resource ID #0x7f020077

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2603)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.content.res.Resources.loadDrawable(Resources.java:2503)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.widget.TextView.<init>(TextView.java:881)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:64)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.widget.EditText.<init>(EditText.java:60)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:60)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.support.v7.widget.AppCompatEditText.<init>(AppCompatEditText.java:56)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:112)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:1008)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1067)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:746)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	... 25 more

07-08 23:52:14.497 13594 13594 E AndroidRuntime: Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #4: <item> tag requires a 'drawable' attribute or child tag defining a drawable

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:182)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:115)

07-08 23:52:14.497 13594 13594 E AndroidRuntime: 	at androi

07-08 23:52:14.499   955  3465 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.SettingsActivity

07-08 23:52:14.501   955  3465 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity

Happens from both the google play and f-droid versions on stock and custom roms for the nexus 6p

**Comment by licaon-kter** [comment] 2016-07-09 05:25
@m33p une https://gits.github.com to paste logs and just attach the link.

**Comment by m33p** [comment] 2016-07-09 07:19
Done sorry about that..

**Comment by Nutomic** [comment] 2016-07-11 00:19
This is the same problem as #693. The error doesn't really make sense, might be a problem with the support library.

I'm currently busy finishing my bachelor thesis, so I probably don't expect a fix very soon (unless someone else wants to look into it).

**Comment by Nutomic** [comment] 2016-07-11 14:50
@lkwg82 This same problem actually happened before, when we updated the build tools (see #632). Maybe you can check if it is the same problem?

**Comment by lkwg82** [comment] 2016-07-11 21:37
I downgraded the build tools in PR #695 just to have installable apks, which can be installed for testing.

**Comment by lkwg82** [comment] 2016-07-14 20:43
Everyone seeing this crash can check with a special debug build, if this happens because of upgrade the build tools. http://android.syncthing.net/job/Syncthing-Android-PR/241/

Mostly it is the syncthing-armeabi-debug.apk, but I'm not sure if this one or the unaligned one.

As far as I know this installes beside the regular app. So it is like installing it freshly. You will see two different syncthing installations on your phone.

@Nutomic Are theses informations correct?

**Comment by Nutomic** [comment] 2016-07-14 21:07
Just use the `syncthing-fat-debug.apk`, it works for all devices. And yes it will install beside the normal app.

**Comment by frispete** [comment] 2016-07-17 07:14
I'm moving to a new phone (s7 with MM), and this version works for me (but only after enabling root), while the one in play store crashes whenever I attempt to add a device.
Destination folder is on (additional) SD card. For some silly reasons, the internal space is called SD card now, too, under MM.

**Closed** 2016-07-20 18:40 UTC
Labels: bug
