### ISSUE TITLE
Syncthing is disabled after setting run condition to only run on wifi ??

### ISSUE THREAD

**Issue by 2SI3NX** [syncthing/syncthing-android#803] opened 2016-12-09 14:52 UTC
what happened:
Going into settings under > Run Conditions > enabling Always run in background and if i also enable Sync only on wifi and restrict to a certain network, when i click back to go to the main screen, Syncthing says: Syncthing is disabled - do you want to change your preferences?

If i uncheck 'Sync only on wifi and restrict to a certain network'
then I can go back into the app without it saying its disabled.

Now why on earth would it get disabled when i say i want to restrict to certain wifi networks?? Am i the only one this is happening to?

    what you expected to happen instead:
The opposite is supposed to happen.

    any steps to reproduce the problem.
Just do the steps i mentioned above

Version Information

Syncthing Version: v0.9.1 Android Syncthing via fdroid repo.
Android v.6.0.1

**Comment by licaon-kter** [comment] 2016-12-09 19:19
This is a duplicate of other issues. But depends, where you actually connected to that Wi-Fi at the time or not? If you are not, then it's not a bug, it's just the way it's working now.

**Comment by Beast141** [comment] 2016-12-11 02:18
Yes i was connected to the Wi-Fi at the time and it just keeps saying its disabled when i enable it.

**Comment by 2SI3NX** [comment] 2017-01-02 16:32
will this be fixed? which other issues are duplicated from this?

**Comment by 2SI3NX** [comment] 2017-01-28 00:38
@licaon-kter any news on this? will this obvious issue ever be fixed? Even after latest syncthing update from fdroid repo, everytime i try and enable run only when connected to wi-fi, it disables syncthing!!
I want to explicitly run this only on wifi, im sure im not the only one.

**Comment by Nutomic** [comment] 2017-01-28 02:01
This is a duplicate of #634. Unfortunately, we haven't found the reason for it yet.

**Closed by Nutomic** 2017-01-28 02:01 UTC
