### ISSUE TITLE
camera pictures don't trigger watch for changes

### ISSUE THREAD

**Issue by mdeff** [syncthing/syncthing-android#1606] opened 2021-02-09 23:25 UTC
I have a syncthing folder to sync my pictures at `/storage/emulated/0/DCIM/Camera` with "Watch for changes" enabled. I expect that whenever I take a new picture, syncthing would detect and propagate the change. That however doesn't happen without a manual rescan of the folder. But if another app makes a change (I've tried with the file explorer and [markor](https://play.google.com/store/apps/details?id=net.gsantner.markor), a markdown editor), then their change is automatically detected and propagated.

That issue was previously reported by another user in the [forum](https://forum.syncthing.net/t/watch-for-changes-on-pixel-5-with-google-camera-and-fotos-does-not-work/15772).

### Version Information

    App Version: 1.13.0
    Syncthing Version: 1.13.0
    Android Version: Android 11
    Device: Google Pixel 4a 5G

**Comment by imsodin** [comment] 2021-02-10 07:54
duplicate of #1353

**Closed by imsodin** 2021-02-10 07:54 UTC

**Comment by mdeff** [comment] 2021-02-10 12:09
Sorry I didn't see that. Thanks.
