### ISSUE TITLE
Show reason why Syncthing is stopped

### ISSUE THREAD

**Issue by Nutomic** [syncthing/syncthing-android#729] opened 2016-08-24 20:51 UTC
Eg because wifi is disabled, battery saver is active, etc.

The status could be shown in the notification, and in the drawer. Maybe also in the disabled dialog, but hopefully we won't need that dialog much longer.

See #727

**Comment by conrad-heimbold** [comment] 2016-10-19 12:01
The Android Material Doc's say, you should not use the notification bar for "Operations that don't require user involvement, like syncing information". 
Source: https://material.google.com/patterns/notifications.html 

Please respect these Doc's and do only show notifications, if files have been added or deleted, a new device wants to connect, or anything similar which is really a notification. 

If you want to know, what an app is doing in the background, just open that app! Syncthing should show its status (starting, running, paused, stopped) and reason for that (no wifi, not connected to charger, etc.) inside of the app, not in the notification area.

**Comment by capi** [comment] 2016-10-19 12:12
This ticket is about showing it inside the application (in the dialog that pops up at the moment), not about notifications. Please don't spam all notification-related threads now with this request.

**Comment by wweich** [comment] 2016-10-19 12:19
To wrap up #765: We should not only show this info in the notification, as it can be disabled.

**Comment by Catfriend1** [comment] 2018-08-04 17:43
I'm working on this.

**Comment by Catfriend1** [comment] 2019-03-09 22:39
Duplicate of #1263 and solved by "Show reasons for disabled service in notification dialog (#1264)"

**Closed by Catfriend1** 2019-03-09 22:39 UTC
Labels: enhancement
