### ISSUE TITLE
Can't sync to portable SD CARD in read-write mode, only read only mode works. (Android 10, MIUI 12).

### ISSUE THREAD

**Issue by digital-spinner** [syncthing/syncthing-android#1592] opened 2021-01-14 07:18 UTC
Syncthing can't sync in read-write mode to external / portable SD CARD including whatever directory on that SD CARD you wish to use. It says that "your version of Android only allows to sync in read only mode". And so.. Only read only mode works.
I have no problems with other apps accessing external SD CARD.

Also it has confusing message related to overwriting contents of the directory when sync is not possible!
It should say something else like issue or whetever just not to overwrite the contents because it is not clear what will be overwritten.

### Version Information

    App Version: 1.10.0
    Syncthing Version: v1.10.0
    Android Version: Android 10 QKQ1.200628.002 / MIUI 12.0.6.0 (QJSEUXM) GLOBAL STABLE
    Smartphone: Mi 10T Lite

**Comment by imsodin** [comment] 2021-01-14 08:45
Duplicate of https://github.com/syncthing/syncthing-android/issues/29

**Closed by imsodin** 2021-01-14 08:45 UTC
