### ISSUE TITLE
BlackBerry OS10

### ISSUE THREAD

**Issue by tigerxy** [syncthing/syncthing-android#215] opened 2015-02-21 22:20 UTC
![img_20150221_231814](https://cloud.githubusercontent.com/assets/7744359/6316235/f4c6c0fa-ba1f-11e4-89ce-491834037e6e.png)
Breaks at startup on BlackBerry 10.3.1 Z10.

**Comment by Zillode** [comment] 2015-02-21 22:23
Please provide a log, see https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md

**Comment by Zillode** [comment] 2015-03-16 18:56
@tigerxy can you try with the latest version? Seems like a duplicate of https://github.com/syncthing/syncthing-android/issues/226

**Comment by lordfolken** [comment] 2015-09-18 20:05
The program starts and says generating keys.. then it suddenly minimizes, and when i reopen it it says failed to generate keys and to check the logs. The application has the run in the background permission.  Version: 1.0.0.372

**Comment by Nutomic** [comment] 2015-09-20 20:51
We still need the logs ;)

**Comment by lordfolken** [comment] 2015-09-21 08:19
I have been trying to get you the logs. It needs some kind of debug token to get the adb bridge running. Up till now I haven't been able to do so.

**Comment by Nutomic** [comment] 2015-09-22 22:00
There should be a dialog popping up on the phone as soon as you connect it. You also may have to enable developer settings first (by tapping Settings -> Build number a few times). Otherwise, you can also use a logcat app.

**Comment by singpolyma** [comment] 2015-11-18 19:53
Some logs from a Q10 running BB10 10.3 for you: http://pastie.org/private/yso6pwftuzucdxxcckahla

**Comment by singpolyma** [comment] 2015-11-18 19:57
The core of the issue seems to be:

```
W/SyncthingNativeCode(137765093): runtime: panic before malloc heap initialized
W/SyncthingNativeCode(137765093): fatal error: runtime: cannot reserve arena virtual address space
W/SyncthingNativeCode(137765093): runtime stack:
W/SyncthingNativeCode(137765093): runtime.throw(0x8c7b1a)
W/SyncthingNativeCode(137765093):   /home/vagrant/build/com.nutomic.syncthingandroid/build/go/src/runtime/panic.go:491 +0xa4 fp=0x1029b700
sp=0x1029b6e8
W/SyncthingNativeCode(137765093): runtime.mallocinit()
W/SyncthingNativeCode(137765093):   /home/vagrant/build/com.nutomic.syncthingandroid/build/go/src/runtime/malloc.c:223 +0xf4 fp=0x1029b750
sp=0x1029b700
W/SyncthingNativeCode(137765093): runtime.schedinit()
W/SyncthingNativeCode(137765093):   /home/vagrant/build/com.nutomic.syncthingandroid/build/go/src/runtime/proc.c:137 +0x34 fp=0x1029b768
sp=0x1029b750
W/SyncthingNativeCode(137765093): runtime.rt0_go(0x1029b7b4, 0x3, 0x1029b889, 0x1029b8c5, 0x1029b8cf, 0x0, 0x1029b8fd, 0x1029b906, 0x1029b91b,
0x1029b929, ...)
W/SyncthingNativeCode(137765093):   /home/vagrant/build/com.nutomic.syncthingandroid/build/go/src/runtime/asm_arm.s:69 +0xb0 fp=0x1029b7a8
sp=0x1029b768
```

**Comment by AudriusButkevicius** [comment] 2015-11-18 20:00
It seems that it's simply not a compatible architecture.
Even though it's ARM, their kernel has something funky which breaks go.

**Comment by Nutomic** [comment] 2015-12-09 12:11
Looks like this was superseded by #449.

**Closed by Nutomic** 2015-12-09 12:11 UTC
Labels: upstream
