### ISSUE TITLE
UI crash – NullPtr: ComponentName.getPackageName() on null object

### ISSUE THREAD

**Issue by Lesik** [syncthing/syncthing-android#969] opened 2017-10-13 09:34 UTC
First of all I want to thank all contributors for this great app, which is easy to use and looks very decent for a free software project.

I just installed version 0.14.38 with Syncthing 0.9.14 from F-Droid on a LineageOS 14.1 device.

Shortly after the start of the app, I get a reproducible UI crash:

```
10-13 11:24:33.199  1730  2682 I ActivityManager: START u0 {cmp=com.nutomic.syncthingandroid/.activities.FolderActivity (has extras)} from uid 10113 on display 0
10-13 11:24:33.633  1730  1782 I ActivityManager: Displayed com.nutomic.syncthingandroid/.activities.FolderActivity: +392ms
10-13 11:24:33.668 11884 11903 D OpenGLRenderer: endAllActiveAnimators on 0x9c01da80 (ListView) with handle 0x9a85d4b0
10-13 11:24:34.165  1730  1812 D Sensors : LightSensor readEvents x = 51.000000, raw = 51
10-13 11:24:35.001  1423  1451 I ThermalDaemon: Sensor 'tsens_tz_sensor0' - alarm cleared 1 at 44.0 degC
10-13 11:24:35.163  1730  1812 D Sensors : LightSensor readEvents x = 51.000000, raw = 51
10-13 11:24:36.166  1730  1812 D Sensors : LightSensor readEvents x = 51.000000, raw = 51
10-13 11:24:36.936 11884 11884 E StrictMode: null
10-13 11:24:36.936 11884 11884 E StrictMode: java.lang.Throwable: file:///storage/emulated/0/DCIM exposed beyond app through Intent.getData()
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1798)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8981)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8942)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.app.Activity.startActivityForResult(Activity.java:4229)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.app.Activity.startActivityForResult(Activity.java:4187)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.app.Activity.startActivity(Activity.java:4526)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.app.Activity.startActivity(Activity.java:4494)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at com.nutomic.syncthingandroid.views.FoldersAdapter.lambda$getView$0(FoldersAdapter.java:58)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at com.nutomic.syncthingandroid.views.FoldersAdapter$$Lambda$1.onClick(Unknown Source)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.view.View.performClick(View.java:5637)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.view.View$PerformClick.run(View.java:22433)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.os.Handler.handleCallback(Handler.java:751)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.os.Looper.loop(Looper.java:154)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-13 11:24:36.936 11884 11884 E StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-13 11:24:36.949  1730  6762 E ActivityManager: Activity Manager Crash
10-13 11:24:36.949  1730  6762 E ActivityManager: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at com.android.server.pm.PackageManagerService.isComponentProtected(PackageManagerService.java:20974)
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at com.android.server.am.ActivityStarter.shouldExcludeFromRecents(ActivityStarter.java:2194)
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:830)
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4543)
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:4511)
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:165)
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2977)
10-13 11:24:36.949  1730  6762 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:565)
10-13 11:24:36.953 11884 11884 D AndroidRuntime: Shutting down VM
10-13 11:24:36.954 11884 11884 E AndroidRuntime: FATAL EXCEPTION: main
10-13 11:24:36.954 11884 11884 E AndroidRuntime: Process: com.nutomic.syncthingandroid, PID: 11884
10-13 11:24:36.954 11884 11884 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1690)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1637)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3101)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1520)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4229)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4187)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4526)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4494)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at com.nutomic.syncthingandroid.views.FoldersAdapter.lambda$getView$0(FoldersAdapter.java:58)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at com.nutomic.syncthingandroid.views.FoldersAdapter$$Lambda$1.onClick(Unknown Source)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.view.View.performClick(View.java:5637)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22433)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
10-13 11:24:36.954 11884 11884 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
10-13 11:24:36.957  1730  3531 W ActivityManager:   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity
```

Not all of the log is related to the crash I think but I decided to copy more than needed just in case.

**Comment by codemac** [comment] 2017-10-16 02:16
How do you see these android logs? I'm getting something similar here on an Oreo device.

**Comment by Nutomic** [comment] 2017-10-16 03:58
Did you click the "open folder" button before that crash happened? It's weird because I'm also running LineageOS 14.1 and don't get this crash. Anyway, the problem is also described in https://github.com/syncthing/syncthing-android/issues/838#issuecomment-335375598, we're sharing the folder path directly instead of using FileProvider.

@codemac You can use any `logcat` app from Google Play, or use logcat from a PC: https://developer.android.com/studio/command-line/logcat.html

**Comment by Lesik** [comment] 2017-10-16 13:39
@Nutomic Sometimes the crash happens on start, sometimes only when I click on the pre-configured Photos folder, sometimes not at all.

@codemac You seem to be using Linux. Search your package manager for adb, then run `adb logcat` (higher privileges possibly needed). Enable USB debugging on your phone and connect it to your computer.

**Comment by Nutomic** [comment] 2017-10-16 15:17
I suspect you are experiencing two different crashes, as this one can only happen when you press the button. Could you try and capture a log for the startup crash?

**Comment by Catfriend1** [comment] 2018-04-22 12:39
@Lesik Please let us know if the issue still persists. I am closing this due to missing answer.
@codemac: Those logs can be grabbed via android adb logcat or the CatLog app.

**Closed by Catfriend1** 2018-04-22 12:39 UTC
