### ISSUE TITLE
dynamic dns

### ISSUE THREAD

**Issue by ghanan** [syncthing/syncthing-android#57] opened 2014-07-04 18:34 UTC
Hi,
¿Does it work with dynamic dns like duckdns.org?

I'm using the phone as a modem for a laptop. Both are configured to sync with the same desktop using duckdns.org. The laptop find the desktop but the phone doesn't.

Thanks.

**Comment by uok** [comment] 2015-01-15 11:29
Thanks for updating the Syncthing Android to go 1.4! Is this issue fixed?
I entered "internalcomputername:port, externaldyndnshost:port" as address - using WLAN (e.g. internalcomputername is available) works, but outside with 3G (should use externaldyndnshost) it does not work. Maybe something is missing here for correct DNS resolve?

**Comment by AudriusButkevicius** [comment] 2015-01-15 12:11
It's not: https://github.com/golang/go/issues/8877
Should be fixed by may, unless @Nutomic wants to compile using cgo which would solve the issue, or forks syncthing and uses a full blown dns client ;)

**Comment by Zillode** [comment] 2015-03-17 12:08
Related development branches if anyone is interested: https://github.com/Zillode/syncthing-android/tree/android-goos and https://github.com/Zillode/syncthing-android/tree/android-goos-i386
Building for ARM works but i386 not

**Comment by lmas** [comment] 2015-06-18 17:47
Any status updates on this? Following some trails to the go repo says it's been fixed now?

**Comment by Zillode** [comment] 2015-06-18 18:12
Almost there, I think https://github.com/golang/go/commit/7165c9b30e36959dcf8d0a038c803b4d2d8be445 will be part of Go 1.5

**Comment by lmas** [comment] 2015-06-19 10:40
Yes I read that one, too. Have to wait until august then, when we'll hopefully get 1.5.

**Comment by rkfg** [comment] 2015-08-20 16:00
1.5 is out, I'm wondering if it now works as intended.

**Comment by Nutomic** [comment] 2015-08-22 16:55
@Zillode I tried to update Go to 1.5 by changing the wget url and sha1 hash in build-syncthing.sh, but I'm getting this output:

```
2015-08-22 18:54:31 (882 KB/s) - ‘go.src.tar.gz’ saved [12045689/12045689]

~/workspace/syncthing-android/build/go/src ~/workspace/syncthing-android
##### Building Go bootstrap tool.
cmd/dist
ERROR: Cannot find /home/felix/go1.4/bin/go.
Set $GOROOT_BOOTSTRAP to a working Go tree >= Go 1.4.
./make.bash: line 121: /home/felix/go1.4/bin/go: No such file or directory
```

Any idea what I'm doing wrong?

**Comment by AudriusButkevicius** [comment] 2015-08-22 17:18
That's trying to build it from source?
In which case you need to have a version of go to bootstrap.

**Comment by anderspitman** [comment] 2015-08-22 17:57
Yeah in 1.5 they [made the jump](https://golang.org/doc/go1.5#c) to a self-hosted compiler, so apparently building 1.5 from source [requires 1.4](https://docs.google.com/document/d/1OaatvGhEAq7VseQ9kkavxKNAfepWy2yhPUBs96FGV28/edit).

**Comment by Zillode** [comment] 2015-08-23 06:13
Yeah that's no fun:/
- I already tried Go1.5 but it didn't fix the DNS problem as far as I could test (done quickly).
- Need to update the build script but that's not that easy without downloading binary blobs

**Closed** 2015-11-19 20:14 UTC
Labels: bug, upstream
