### ISSUE TITLE
A lot more crashes more since 0.10.11

### ISSUE THREAD

**Issue by AudriusButkevicius** [syncthing/syncthing-android#1146] opened 2018-06-16 19:43 UTC
![image](https://user-images.githubusercontent.com/1144861/41501915-440674a4-71a5-11e8-8de7-c0918bb9dc7a.png)

```
java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.activities.MainActivity.lambda$onServiceStateChange$0$MainActivity (MainActivity.java:116)
  at com.nutomic.syncthingandroid.activities.MainActivity$$Lambda$0.onResult (Unknown Source:4)
  at com.nutomic.syncthingandroid.service.RestApi.lambda$getSystemInfo$7$RestApi (RestApi.java:398)
  at com.nutomic.syncthingandroid.service.RestApi$$Lambda$7.onSuccess (Unknown Source:2)
  at com.nutomic.syncthingandroid.http.ApiRequest.lambda$connect$0$ApiRequest (ApiRequest.java:98)
  at com.nutomic.syncthingandroid.http.ApiRequest$$Lambda$0.onResponse (Unknown Source:4)

java.lang.ClassCastException: 
  at android.app.SharedPreferencesImpl.getStringSet (SharedPreferencesImpl.java:234)
  at com.nutomic.syncthingandroid.service.SyncthingRunnable.buildEnvironment (SyncthingRunnable.java:435)
  at com.nutomic.syncthingandroid.service.SyncthingRunnable.run (SyncthingRunnable.java:133)
  at com.nutomic.syncthingandroid.service.SyncthingRunnable.run (SyncthingRunnable.java:106)

Caused by: java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.service.RestApi.editFolder (RestApi.java:285)
  at com.nutomic.syncthingandroid.activities.FolderActivity.updateFolder (FolderActivity.java:486)
  at com.nutomic.syncthingandroid.activities.FolderActivity.onPause (FolderActivity.java:253)

java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.service.RestApi.getOptions (RestApi.java:371)
  at com.nutomic.syncthingandroid.activities.MainActivity.lambda$showUsageReportingDialog$10$MainActivity (MainActivity.java:477)
  at com.nutomic.syncthingandroid.activities.MainActivity$$Lambda$9.onClick (Unknown Source)

java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.activities.MainActivity.lambda$showUsageReportingDialog$10$MainActivity (MainActivity.java:477)
  at com.nutomic.syncthingandroid.activities.MainActivity$$Lambda$9.onClick (Unknown Source)

Caused by: java.io.FileNotFoundException: 
  at java.io.FileInputStream.open (Native Method)
  at java.io.FileInputStream.<init> (FileInputStream.java:146)
  at com.nutomic.syncthingandroid.activities.WebGuiActivity.loadCaCert (WebGuiActivity.java:213)

java.lang.NullPointerException: 
  at android.support.v4.app.BackStackRecord.doAddOp (BackStackRecord.java:392)
  at android.support.v4.app.BackStackRecord.add (BackStackRecord.java:387)
  at android.support.v4.app.FragmentPagerAdapter.instantiateItem (FragmentPagerAdapter.java:104)
  at android.support.v4.view.ViewPager.addNewItem (ViewPager.java:1004)
  at android.support.v4.view.ViewPager.populate (ViewPager.java:1152)
  at android.support.v4.view.ViewPager.populate (ViewPager.java:1086)
  at android.support.v4.view.ViewPager.onMeasure (ViewPager.java:1616)
  at android.view.View.measure (View.java:22104)

Caused by: java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.activities.FolderActivity.updateFolder (FolderActivity.java:486)
  at com.nutomic.syncthingandroid.activities.FolderActivity.onPause (FolderActivity.java:253)

java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.service.RestApi.getGui (RestApi.java:375)
  at com.nutomic.syncthingandroid.fragments.DrawerFragment.showQrCode (DrawerFragment.java:210)
  at com.nutomic.syncthingandroid.fragments.DrawerFragment.onClick (DrawerFragment.java:241)

Caused by: java.lang.ClassCastException: 
  at com.nutomic.syncthingandroid.service.SyncthingService.onCreate (SyncthingService.java:136)

java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.activities.FolderActivity$2.onCheckedChanged (FolderActivity.java:111)

java.lang.NullPointerException: 
  at com.nutomic.syncthingandroid.activities.ShareActivity.lambda$onCreate$0$ShareActivity (ShareActivity.java:152)
  at com.nutomic.syncthingandroid.activities.ShareActivity$$Lambda$0.onClick (Unknown Source:6)
```

**Comment by Catfriend1** [comment] 2018-06-17 09:01
java.lang.ClassCastException: at android.app.SharedPreferencesImpl.getStringSet (SharedPreferencesImpl.java:234) at com.nutomic.syncthingandroid.service.SyncthingRunnable.buildEnvironment (SyncthingRunnable.java:435) at com.nutomic.syncthingandroid.service.SyncthingRunnable.run (SyncthingRunnable.java:133) at com.nutomic.syncthingandroid.service.SyncthingRunnable.run (SyncthingRunnable.java:106) 

PR #1134 #1136

**Comment by Catfriend1** [comment] 2018-06-17 09:02
Caused by: java.lang.NullPointerException: at com.nutomic.syncthingandroid.activities.FolderActivity.updateFolder (FolderActivity.java:486) at com.nutomic.syncthingandroid.activities.FolderActivity.onPause (FolderActivity.java:253)

PR #1144

**Comment by Catfriend1** [comment] 2018-06-17 09:06
This looks rare but interesting: looks like the config got missing or corrupted and the key files got missing?! I think that can still happen after my fixes but its got rare because there is only one code part left to fix I identified not properly synchronizing with the binary lifecycle and service state signals. Its the part where one resets index or database. Should be rare and easy to fix. I'll go for it.

Caused by: java.io.FileNotFoundException: at java.io.FileInputStream.open (Native Method) at java.io.FileInputStream.<init> (FileInputStream.java:146) at com.nutomic.syncthingandroid.activities.WebGuiActivity.loadCaCert (WebGuiActivity.java:213)

**Comment by Catfriend1** [comment] 2018-06-17 09:07
I need to add service state checks and maybe also null checks here.

java.lang.NullPointerException: at com.nutomic.syncthingandroid.service.RestApi.getGui (RestApi.java:375) at com.nutomic.syncthingandroid.fragments.DrawerFragment.showQrCode (DrawerFragment.java:210) at com.nutomic.syncthingandroid.fragments.DrawerFragment.onClick (DrawerFragment.java:241)

**Comment by Catfriend1** [comment] 2018-06-17 09:10
Hmmm... Those popups in MainActivity look as they could be implemented better. Maybe we'll first fix it by suppressing the popup so long until Service state active is reached so restapi is ready to serve the desired calls.

java.lang.NullPointerException: at com.nutomic.syncthingandroid.service.RestApi.getOptions (RestApi.java:371) at com.nutomic.syncthingandroid.activities.MainActivity.lambda$showUsageReportingDialog$10$MainActivity (MainActivity.java:477) at com.nutomic.syncthingandroid.activities.MainActivity$$Lambda$9.onClick (Unknown Source) java.lang.NullPointerException: at com.nutomic.syncthingandroid.activities.MainActivity.lambda$showUsageReportingDialog$10$MainActivity (MainActivity.java:477) at com.nutomic.syncthingandroid.activities.MainActivity$$Lambda$9.onClick (Unknown Source)

**Comment by Catfriend1** [comment] 2018-06-17 21:29
I suggest to close this as I spawned subtasks for every single error (or related errors) by creating the linked issues.
I left out one error intentionally as I have no clue if this is really a syncthing app problem. If it is, it may be caused by a fragment lifecycle been violated. Maybe PR #1144 already fixes the problem with the fragment lifecycle?!

> java.lang.NullPointerException: 
  at android.support.v4.app.BackStackRecord.doAddOp (BackStackRecord.java:392)
  at android.support.v4.app.BackStackRecord.add (BackStackRecord.java:387)
  at android.support.v4.app.FragmentPagerAdapter.instantiateItem (FragmentPagerAdapter.java:104)
  at android.support.v4.view.ViewPager.addNewItem (ViewPager.java:1004)
  at android.support.v4.view.ViewPager.populate (ViewPager.java:1152)
  at android.support.v4.view.ViewPager.populate (ViewPager.java:1086)
  at android.support.v4.view.ViewPager.onMeasure (ViewPager.java:1616)
  at android.view.View.measure (View.java:22104)

**Comment by AudriusButkevicius** [comment] 2018-06-17 21:39
I wonder if this is something todo with the new onBackPress stuff.

**Comment by Catfriend1** [comment] 2018-06-17 21:48
@AudriusButkevicius  I'll keep that in mind and have an eye on it during the next test sessions.

**Comment by Catfriend1** [comment] 2018-06-18 10:40
The message above may correspond to this so article:
https://stackoverflow.com/questions/11099897/viewpager-fragmentpageradapter-nullpointer

**Comment by AudriusButkevicius** [comment] 2018-06-18 11:29
It seems like something that should be addressed, no?

**Comment by Catfriend1** [comment] 2018-06-18 11:31
Yes. I'll file a new issue when I know what to do.

**Comment by Catfriend1** [comment] 2018-06-20 10:13
Closed as all subtasks have been filed as separate tickets on the issue tracker. For the java.lang.NullPointerException:
at android.support.v4.app.BackStackRecord.doAddOp (BackStackRecord.java:392)
see issue #1162 .

**Closed by Catfriend1** 2018-06-20 10:13 UTC
