### ISSUE TITLE
Only in the android release: dyndns-name not possible as a global discovery server?

### ISSUE THREAD

**Issue by merlinuwe** [syncthing/syncthing-android#209] opened 2015-01-22 12:21 UTC
Hi,
is it possible to enable the field for the entry of the global discovery server for a DNS name instead of the server IP number? I use the discosrv.exe on Windows 7 with "dummy.dyndns.org", but the android release of syncthing cannot connect. (The non-android releases do.) The connection to the current IP number works, but only until the DSL line gets interrupted by the provider.
My goal is to set up a private global discovery server and to use the android release of syncthing, too. Can you help?

Greetings,

Uwe

**Comment by AudriusButkevicius** [comment] 2015-01-22 12:23
I've pointed you to the exact specific issue in this repo on discourse.
No need to open duplicates.

**Comment by AudriusButkevicius** [comment] 2015-01-22 12:23
Duplicate of https://github.com/syncthing/syncthing-android/issues/57

**Comment by Nutomic** [comment] 2015-01-22 13:04
yep

**Closed by Nutomic** 2015-01-22 13:04 UTC
