### ISSUE TITLE
[Android Q (as of beta 5)] Syncthing Android can't see files in external storage except for it's own app-specific directory due to Scoped Storage

### ISSUE THREAD

**Issue by bungabunga** [syncthing/syncthing-android#1377] opened 2019-08-04 09:52 UTC
### Problems with file discovery after introduction of Scoped Storege in Android Q

On Android devices with Android Q the current situation (as of beta 5) is this:
- Syncthing can only sync files in /storage/emulated/0/Android/data/com.nutomic.syncthingandroid or /storage/emulated/0/Android/media/com.nutomic.syncthingandroid,
- although Google said that "as of Android Q Beta 4, apps that target Android 9 (API level 28) or lower see no change" that doesn't apply to apps like Syncthing that use direct kernel access. Direct kernel access also won't be supported in final Android Q,
- it seems that the only way possible for Syncthing Android to work like before is if it accesses everything from Java,
- because of the same issue Syncthing is also unable to access Syncthing backed up files.

More on this topic on issue  #1008 (at the end) and also [here](https://github.com/Catfriend1/syncthing-android/issues/457).

[Log](https://gist.github.com/bungabunga/237a15cce677e7cc89c46bc066e177e8).

### Version Information

    App Version: Syncthing Fork 1.2.0.8
    Syncthing Version: v1.2.0
    Android Version: Android Q beta 5 

Please mind: I actually use Syncthing Fork but I belive the issue is the same and should also be adressed here. Sadly I can not test this app myself because of bug #1291. 

Thanks to @Catfriend1 for explanations of more technical stuff!

**Comment by imsodin** [comment] 2019-08-11 09:53
Did you actually check? From all I read by targeting android's sdk version 28 we are in compatibility mode, i.e. scoped storage does not apply to us yet. As @Catfriend1's fork already targets 29, it does apply there. This will become relevant November 2020 unless google changes its mind until then. It's essentially the same issue as https://github.com/syncthing/syncthing-android/issues/29, so I close this in favor of updating the latter.

(As already commented in #1291: That's going to be fixed with the release of go 1.13, which is overdue - so it wont be long.)

**Closed** 2019-08-11 09:58 UTC

**Comment by Catfriend1** [comment] 2019-08-11 10:04
Hi,

Just for a quick info : I went targeting Android Q (29) a few days ago for testing reasons related to that ticket. The user already reported Problems while it was on api 28. We could not test together if the problems are solved by 29 because a go-crashlog came up on his phone after updating to the test apk whilst on my device the apk still works fine.

**Comment by bungabunga** [comment] 2019-08-11 10:09
As @Catfriend1 said. And the shared folders are not read-only but inaccessible on API 28.

**Comment by AudriusButkevicius** [comment] 2019-08-11 10:13
Sure, :man_shrugging: what can we do? Sd cards still suck, google wants to kill support for them, which is essentially a new addition to sd card problems on #29

**Comment by bungabunga** [comment] 2019-08-11 10:16
@AudriusButkevicius but this is not SD card related. it's a phone's (ext) storage not SD card. I don't even have SD card slot on my Pixel device.

**Comment by imsodin** [comment] 2019-08-11 10:16
> Sure, man_shrugging what can we do? Sd cards still suck, google wants to kill support for them, which is essentially a new addition to sd card problems on #29

The thing is, it's not just SD cards in 29, it's all "external storage", with "external" being any directory whether on SD card or not that's not in Syncthing's own directory (the `.../Android/.../com.nutomic/syncthing-android/...` kind of paths).

**Comment by taigrr** [comment] 2019-08-11 19:08
I can reproduce. Or rather, I can't *not* reproduce. Had to switch to the fork after the latest android update when I noticed my files weren't getting synced. I can open the app and accept the permission requests, then it fails trying to generate ssl certs. Tried many times.

I'm running the OG Pixel XL, Android 10, update beta 6.
