### ISSUE TITLE
Android GUI does not update with sync status

### ISSUE THREAD

**Issue by kl4ng** [syncthing/syncthing-android#526] opened 2015-12-26 16:35 UTC
Hello, on my first sync I notice that the Android GUI is showing me as disconnected from my other two devices and the folder I'm syncing as "Idle (100%)" despite syncing actually going on.

If I click on "Web GUI", it shows all the expected data (that I'm syncing a folder and at XX% and I'm connected to Y and Z". So I'm guessing it's just a problem with the android-GUI not being updated accordingly.

I did restart the app shortly after it started syncing for the first time, so the android-GUI displays the folder that is syncing as being, as mentioned before, complete and Idle (100%) with 111/111 files and 16.1MB/16.1MB. Maybe the reset during the sync had something to do with it.

EDIT: When the sync finally finished the android-GUI got updated accordingly, showing the folder as being 100% with the 800MB downloaded.

**Comment by Nutomic** [comment] 2016-01-18 11:28
This is a duplicate of #74. Unfortunately, I haven't managed to investigate that yet.

**Closed by Nutomic** 2016-01-18 11:28 UTC
