### ISSUE TITLE
UX - No notification when folder shared from other device

### ISSUE THREAD

**Issue by jockbert** [syncthing/syncthing-android#359] opened 2015-04-15 14:50 UTC
Scenario - I have two devices. Device A is is a Linux desktop. Device B is a android phone with the syncthing app. Both devices has de folder X defined. On device A, I share folder X with device B. The problem is that device B does not notice that device A shares the folder X with it, so I also (!) have to manually share folder X with A on device B.

**Comment by Nutomic** [comment] 2015-04-22 21:24
Duplicate of #295.

**Closed by Nutomic** 2015-04-22 21:24 UTC
Labels: bug
