### ISSUE TITLE
Syncthing fails to start up if a wireless proxy is in place

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#534] opened 2016-01-11 05:47 UTC
Hi

I realized that if I use an http proxy through the wireless connection dialog, Syncthing fails to start up. 

You can change your proxy by long click on a connection and modify network.

**Comment by Nutomic** [comment] 2016-01-22 21:13
Seems to be a duplicate of #440.

**Closed by Nutomic** 2016-01-22 21:13 UTC
Labels: bug
