### ISSUE TITLE
"Always run in background" and "only on wifi" odd behaviour.

### ISSUE THREAD

**Issue by vext01** [syncthing/syncthing-android#633] opened 2016-04-26 21:20 UTC
Set:

 * "Always run in backgbround" ON
 * "sync only on wifi" ON
 * reboot android
 * Wait for wifi to cinnect

At this point the syncthing service is not running despite being connected to wifi.

 * Go to settings
 * Turn "sync only on wifi" OFF

Syncthing notification will now appear indicating that syncthing service is now running.

It should have been running all along?

**Comment by licaon-kter** [comment] 2016-04-26 22:03
Device? Android version?

**Comment by Nutomic** [comment] 2016-04-26 22:05
Seems to be a duplicate of #625. Fixed in 0.7.16

**Comment by vext01** [comment] 2016-04-26 22:05
Its an LG G4 running 5.1. I have not installed custom firmware.

**Comment by vext01** [comment] 2016-04-26 22:07
Already fixed, great. So i just have to wait for an update.

Thanks

**Closed** 2016-04-26 22:08 UTC
Labels: duplicate
