### ISSUE TITLE
Bypass proxy to access localhost

### ISSUE THREAD

**Issue by da2x** [syncthing/syncthing-android#440] opened 2015-08-04 09:50 UTC
Android doesn’t bypass Wi-Fi configured proxies by default when loading 127.0.0.1 (localhost). Resulting in Synthing being stuck with a “Loading …” dialog indefinetely. 

The Syncthing app should:
- provide an error when failing to connect to itslf.
- always bypass any proxies when connecting to 127.0.0.1 (not guaranteed by the OS to actually be localhost)

**Comment by Nutomic** [comment] 2016-10-16 17:19
I just tried this by setting an invalid proxy, and the app still worked fine. So apparently this has been fixed by some other change. Let me know if you still have the problem.

**Comment by Aeyoun** [comment] 2016-10-16 17:49
Problem persists in Android 6 and 7 with the latest version of the app.

**Comment by Nutomic** [comment] 2016-10-16 23:31
Can you tell me how exactly I can reproduce this?

**Comment by Aeyoun** [comment] 2016-10-17 00:15
I’m sorry for not providing enough details here.

1. Connect to a WiFi network and disconnect any power supply
2. Go to Settings: WiFi, and long-press on your network; choose Modify network
3. Expand advanced and pick Proxy Auto-Configure from the list of proxy types
4. In the PAC address field type "http://example.com/ (sic), [we want to always bypass proxies here so doesn't need to be a working proxy server]
4. Save the changes
6. Open the Synchthing app
7. Menu: Web GUI

"Webpage not available" net::ERR_CONNECTION_TIMED_OUT

The bug here is that the connection to Syncthing on 127.0.0.1 (loopback) shouldn't ever be passed through the system proxy. You never need to consult a remote server, e.g. the proxy, when talking through the loopback interface as that is always the local device talking to itself. Most Android apps handle this just fine and send HTTP traffic through the proxy server with the exception of traffic aimed at the local device. Syncthing’s behavior is quite abnormal here.

**Comment by Nutomic** [comment] 2016-10-17 03:30
I just tried these steps, and the app starts without problems (on Android 6.0). What Android version are you using?

**Comment by Aeyoun** [comment] 2016-10-18 10:31
I dug up an Android 6 and an Android 7, and both exhibit the same problem. I remember this issue appeared when I upgraded from Android 5 to 6, but I don’t have a non-upgraded device to test with Android.

**Comment by Nutomic** [comment] 2016-10-19 23:27
Well unfortunately I can't reproduce the problem, so I don't know how to fix it. And when I seached for this problem online, I couldn't find anything either.

**Comment by reevelau** [comment] 2017-03-21 06:48
I come to here because I am working a similar issue.

The issue is caused by this chromium fix.
https://bugs.chromium.org/p/chromium/issues/detail?id=471400

Basically, chrome will send localhost http request to proxy server whenever it is available. In my case, my mobile service operator defines and enforce APN settings on 3G/4G network. So when the wifi is not available. Web GUI of Sycthing will show error message like this.

```
Webpage not available

The webpage at http://127.0.0.1:8384/ could not be loaded because:

net::ERR_CONNECTION_RESET
```

Hope my information may help.

**Comment by Nutomic** [comment] 2017-03-21 07:23
Do you know of any workaround that we could implement to fix the issue?

**Comment by reevelau** [comment] 2017-03-21 07:51
I am still looking for a clean way of disable the proxy for the webview. AFAIK, this is a viable but hacky way to disable that using code.
http://stackoverflow.com/questions/4488338/webview-android-proxy

**Comment by shibe2** [comment] 2017-08-26 11:23
I have this problem on Android 4.

**Comment by shibe2** [comment] 2017-08-26 13:47
I figured it out. Turns out, it's a localization problem. In Russian locale, "bypass proxy for" is "прокси для", which has the opposite meaning. I switched language to English and was able to enter correct connection settings: bypass proxy for 127.0.0.1. Syncthing now works.

**Comment by Catfriend1** [comment] 2018-04-27 20:34
I am experiencing this issue too ERR_TIMEOUT but can reach the web UI properly using firefox on android connecting to the adress https://0.0.0.0:8384 syncthing's UI stated as TIMEOUT. I'll make some tests to narrow down the cause and hopefully come up with a suggestion to fix it. I am also having a PAC file with proxy in place on my network.

**Closed** 2018-05-02 22:11 UTC
Labels: bug
