### ISSUE TITLE
[FEATURE REQUEST] - Granular Data/WiFi control

### ISSUE THREAD

**Issue by J316** [syncthing/syncthing-android#989] opened 2017-11-15 00:16 UTC
An option should be added for each specific synced folder to be synced under particular conditions (e.g. only on WiFi or on 3G but not 2G). The reason for this is I might want to sync a small folder with whatever connection available, but sync a big folder only on WiFi

**Comment by Nutomic** [comment] 2017-11-15 07:23
Duplicate of #511. Please use the search before opening a new issue.

**Closed by Nutomic** 2017-11-15 07:23 UTC
