### ISSUE TITLE
Clean install: "Failed to create syncthing config¸Please check the logs."

### ISSUE THREAD

**Issue by AltJ** [syncthing/syncthing-android#544] opened 2016-01-21 16:21 UTC
I just installed 0.7.6 on a Galaxy Tab 7 plus
Android 4.0.4
kernel 3.0.15
never been rooted
no SD card installed
I used to run syncthing on this device a few months ago without problems.

I've attached the full log from install through initial launch.
[logcat.txt](https://github.com/syncthing/syncthing-android/files/99437/logcat.txt)

**Comment by Nutomic** [comment] 2016-01-21 20:33
Seems to be a duplicate of #518.

**Closed by Nutomic** 2016-01-21 20:33 UTC
