### ISSUE TITLE
Browse repos without storing them locally

### ISSUE THREAD

**Issue by davidgfnet** [syncthing/syncthing-android#575] opened 2016-03-01 23:53 UTC
Hey guys!

Is it possible (and how difficult would be) to actually have a shared folder that is not actually stored locally? This is, similarly to the Dropbox app in Android, the ability to "just browse" the repo and manually downloading some files. I guess it would require to download the index and then if the user wants a file, syncing that file.
Thanks for the great work!

**Comment by Nutomic** [comment] 2016-03-02 15:22
Duplicate of #81. It would be possible, but we'd need support in Syncthing (and most importantly, someone to work on it).

**Closed by Nutomic** 2016-03-02 15:22 UTC

**Comment by davidgfnet** [comment] 2016-03-02 15:41
Hey Nutomic,
Can you give some insight? I might be up for some Go coding :D 
Thanks!

**Comment by Nutomic** [comment] 2016-03-02 15:55
Actually, according to [this comment](https://github.com/syncthing/syncthing/issues/193#issuecomment-54534512), this might be possible by using the .stignore. So you'd have to test and figure out if this works for all cases, and then write an Android GUI to (un)select files/folders.

It's probably best if we discuss this in #81, or even better in the [forum](http://forum.syncthing.net/).

**Comment by Nutomic** [comment] 2016-03-02 17:30
Actually, browsing a repo without downloading anything is a different one than what I linked. You should open an issue at [syncthing](https://github.com/syncthing/syncthing) and discuss there how this could be implemented.

The actual issue for Android is #205.
