### ISSUE TITLE
"Waiting for GUI" forever after backup and restore

### ISSUE THREAD

**Issue by fantom-x** [syncthing/syncthing-android#885] opened 2017-05-09 14:46 UTC
Cannot access Web GUI after the following steps:

1. Install and connect to another device (not android), share two folders and see them sync both ways with no issues.
2. Backup configuration 
3. Uninstall the android app
4. Install it again
5. Import the configuration: checked every parameter and all is imported properly
6. Try accessing "Web GUI" and never get past "Waiting for GUI"

I tried restarting, rebooting, uninstalled several times, etc all with the same result. 

The last messages in the log :

14:33:50 INFO: GUI and API listening on 127.0.0.1:28540
14:33:50 INFO: Access the GUI via the following URL: https://127.0.0.1:28540/

The CPU usage reported by the app is constantly at 15%.

If I wait long enough I see these messages in the log, but not sure if related:

2017/05/09 14:31:29 http: TLS handshake error from 127.0.0.1:45820: tls: client using inappropriate protocol fallback
2017/05/09 14:31:29 http: TLS handshake error from 127.0.0.1:44457: tls: client using inappropriate protocol fallback
2017/05/09 14:31:29 http: TLS handshake error from 127.0.0.1:37612: tls: client using inappropriate protocol fallback

Is there a better way to import settings?

**Comment by licaon-kter** [comment] 2017-05-09 14:50
App source? Android version? Device?

**Comment by fantom-x** [comment] 2017-05-09 14:57
Android store; just installed whatever version is currently available
Android 6.0.1
Blackberry PRIV

**Comment by fantom-x** [comment] 2017-05-09 15:53
The app version is 0.9.9 with syncthing v0.14.26

**Comment by fantom-x** [comment] 2017-05-09 16:25
The build from f-droid (seems to be older with 0.14.25) behaves exactly the same. After the restore and restart, the CPU usage is around 0% and goes to constant 15% after trying to acres Web GUI. "Waiting for GUI" is displayed for a while and then I see a blank screen.

**Comment by licaon-kter** [comment] 2017-05-09 16:35
What folders do you share? Internal or on external sdcard? Did you enable root?

**Comment by fantom-x** [comment] 2017-05-09 16:38
No root; plain vanilla Android
No sd card
Shared two folders : DCIM/Camera and Documents. They both together have around 50 files in them, which did not take long to index the first time.

**Comment by fantom-x** [comment] 2017-05-09 17:43
Are there debug logs I could collect to help troubleshoot?

**Comment by fantom-x** [comment] 2017-05-09 18:37
Found this. Could it be related?

05-09 14:33:22.983 I/System (14258): Failed to destroy process 15061
05-09 14:33:22.990 I/System  (14258): android.system.ErrnoException: kill failed: ESRCH (No such process)
05-09 14:33:22.990 I/System  (14258): at libcore.io.Posix.kill(Native Method)
05-09 14:33:22.990 I/System  (14258): at libcore.io.ForwardingOs.kill(ForwardingOs.java:105)
05-09 14:33:22.990 I/System  (14258): at java.lang.ProcessManager$ProcessImpl.destroy(ProcessManager.java:260)
05-09 14:33:22.990 I/System  (14258): at com.nutomic.syncthingandroid.activities.LogActivity.getLog(LogActivity.java:146)
05-09 14:33:22.990 I/System  (14258): at com.nutomic.syncthingandroid.activities.LogActivity.access$100(LogActivity.java:24)
05-09 14:33:22.990 I/System  (14258): at com.nutomic.syncthingandroid.activities.LogActivity$1.doInBackground(LogActivity.java:104)
05-09 14:33:22.990 I/System  (14258): at com.nutomic.syncthingandroid.activities.LogActivity$1.doInBackground(LogActivity.java:101)
05-09 14:33:22.990 I/System  (14258): at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-09 14:33:22.990 I/System  (14258): at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-09 14:33:22.990 I/System  (14258): at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-09 14:33:22.990 I/System  (14258): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-09 14:33:22.990 I/System  (14258): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-09 14:33:22.990 I/System  (14258): at java.lang.Thread.run(Thread.java:818)
05-09 14:33:26.892 I/art (14258): Starting a blocking GC Explicit

**Comment by fantom-x** [comment] 2017-05-09 19:21
According to the timestamp that happens very soon after the backup import.

**Comment by belidzs** [comment] 2017-05-15 15:25
Duplicate of #868

**Closed** 2017-05-16 03:56 UTC
