### ISSUE TITLE
Stopped Working in Android 10

### ISSUE THREAD

**Issue by carlzulauf** [syncthing/syncthing-android#1393] opened 2019-09-04 01:02 UTC
App was working fine prior to upgrade from Android 9 to Android 10 on Pixel 3a.

After upgraded I got these "TLS segment underaligned" errors as shown in the attached screenshot. I tried removing the app's cache/data and reinstalling.

Appears certain components may need to be re-compiled for the latest android version.

App Version: 1.2.2
Synthing Version: 1.2.2
Android Version: Android 10 (Pixel 3a, Kernel 4.9.165)

![Screenshot_20190903-185519](https://user-images.githubusercontent.com/203546/64218077-67d8b500-ce7d-11e9-92bc-ddc1b4146cf0.png)

**Comment by YmerejRedienhcs** [comment] 2019-09-04 02:46
Same: 
--------- beginning of main
--------- beginning of crash
09-03 22:40:28.889 W/SyncthingNativeCode( 8426): error: "/data/app/com.nutomic.syncthingandroid-2g7BhnVUWuOzYUtyRMCT2g==/lib/arm64/libsyncthing.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic

**Comment by AudriusButkevicius** [comment] 2019-09-04 06:02
Check closed issues

**Comment by Catfriend1** [comment] 2019-09-04 06:17
Duplicate of : https://github.com/syncthing/syncthing-android/issues/1291#issuecomment-527754834

**Comment by AudriusButkevicius** [comment] 2019-09-04 06:23
I'll leave it open for visibility.

**Closed** 2019-09-09 07:57 UTC
