### ISSUE TITLE
Massive network activity despite "Run on mobile data" being disabled 

### ISSUE THREAD

**Issue by malcircuit** [syncthing/syncthing-android#1861] opened 2022-11-22 14:05 UTC
Apparently Synching Android decided to transfer 4.6 GB of who the f*ck knows overnight, even though it's explicitly set to not do anything when it's not on WiFi ("Run on mobile data" was un-checked). The phone should have been up-to-date anyway (I did not do anything that would have modified 4.6 GB of files), so I don't understand what data was even being sent. 

My cell bill is going to be over double what it normally is because of this. I'm too livid to care about trying to replicate this issue, not to mention I was 400 miles away from home (and asleep) when it happened.

### Version Information

    Syncthing-Android Version: 1.22.1.1
    Syncthing Version: v1.22.2-dev.1.g15c0afec
    Android Version: 12

**Comment by acolomb** [comment] 2022-11-22 20:20
Duplicate of #1852?

**Comment by malcircuit** [comment] 2022-11-22 21:16
This was not the device mistakenly recording network traffic that didn't happen. My cellular saw activity on their network and charged me money for it. My battery was almost dead by the morning. Synching was sending real IP packets somewhere when it shouldn't be.

**Comment by imsodin** [comment] 2022-11-22 22:09
Sorry to hear about this issue.  
I believe the detail about no actual data being transferred was either a fluke or a mistake in reporting - there's already a second report in that issue that had real data transfer. Thus I am closing as a duplicate of https://github.com/syncthing/syncthing-android/issues/1852

**Closed by imsodin** 2022-11-22 22:09 UTC
