### ISSUE TITLE
Allow (encrypted) app backups e.g. via SeedVault

### ISSUE THREAD

**Issue by Diapolo** [syncthing/syncthing-android#1826] opened 2022-08-22 08:21 UTC
Current Implementation

Current Syncthing app doesn't allow encrypted backups via SeedVault (backup App for Android, integrated in LineageOS or CalyxOS, see https://calyxinstitute.org/projects/seedvault-encrypted-backup-for-android).

Suggested Enhancement
You could easily allow encrypted app backups :).
See https://github.com/seedvault-app/seedvault/wiki/FAQ#why-do-some-apps-not-allow-to-get-backed-up for a description of the problem and see this sample how Transport (Android app for public travel) implemented it: https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71

**Comment by tomasz1986** [comment] 2022-08-22 10:50
Probably a duplicate of https://github.com/syncthing/syncthing-android/issues/1791? Or at least that issue is broader and kind of encompasses this one.

> Current Orbot app

I think you meant to write Syncthing Android here 😉.

**Comment by Diapolo** [comment] 2022-08-22 11:28
> I think you meant to write Syncthing Android here 😉.

You are right, I opened that issue for some other apps, which also don't support or refuse to allow encrypted backups.

**Comment by AudriusButkevicius** [comment] 2022-08-22 15:08
Closing as duplicate.

**Closed by AudriusButkevicius** 2022-08-22 15:08 UTC

**Comment by Diapolo** [comment] 2022-08-22 15:35
Did you check the provided links? Should be easy to implement and would be very welcome 🙂.

Am 22. August 2022 15:08:56 UTC schrieb Audrius Butkevicius ***@***.***>:
>Closing as duplicate.
>

**Comment by AudriusButkevicius** [comment] 2022-08-22 23:05
I don't know how android backups work, but unless it allows to selectively select files, it's a no-go, as restoring some old database, and potentially no files etc, will lead to disasters. 

Hence we can't just flip the flag and expect stuff to work.
Someone needs to do research, testing and verification.
Personally I have no interest in that.

**Comment by Catfriend1** [comment] 2022-12-08 01:55
I'm currently testing to allow the Google Drive Backup if the user opts-in. See https://github.com/Catfriend1/syncthing-android/commit/40eb7f5af5f82b763f986939f2bcba47e556ab2a

Android dev docs: https://developer.android.com/guide/topics/data/autobackup

**Comment by AudriusButkevicius** [comment] 2022-12-08 19:31
Because if you suddenly restore the database, but not the data, it will assume that you deleted everything, and delete the data everywhere.

**Comment by soredake** [comment] 2022-12-09 08:40
@AudriusButkevicius i don't think it will work like this, i've tested this scenario with and without data, without data after restoring syncthing with database it just showed `Error (folder path missing)` and as you can guess, deleted nothing, and when data is present it continued syncing as expected. 

@Catfriend1 can you please include database in sync too?
https://github.com/syncthing/syncthing-android/issues/1791#issuecomment-1157476760

**Comment by Catfriend1** [comment] 2022-12-09 08:46
@soredake I don't think this will work. Android dev docs state "max  25 MB" quota.

**Comment by soredake** [comment] 2022-12-09 08:51
@Catfriend1 syncthing database can be bigger than 25mb? I haven't used syncthing for large folders for a long time.

**Comment by imsodin** [comment] 2022-12-09 08:57
Please lets move this discussion around why the DB should not be backed up resp. the inherent risks of restoring it to https://forum.syncthing.net/. Respectively search for prior discussions, as to be expected this topic of restoring a setup has come up a few times already. The forum has a lot more eyes and friendly people on it than the issue tracker. Thanks!

Also this has been marked as a duplicate of https://github.com/syncthing/syncthing-android/issues/1791 - please move any discussion about implementation there.
