### ISSUE TITLE
UNDOCUMENTED DANGEROUS BEHAVIOR OF SHARING

### ISSUE THREAD

**Issue by ecxod** [syncthing/syncthing-android#1465] opened 2020-01-17 13:35 UTC
I want to point out a pretty critical bug, and I can’t imagine how bad it is at the moment.

If someone uses this program intensively then he has different folders that he shares with Person1 and other folders that he shares with Person 2 and again other folders or even shared folders that he shares with Person3.

The following happens on the android: If I share a folder with Person1 and then accidentally share the same folder with Person2, and then find that I have made a mistake and push the lock back, then the correction decision is ignored by the Android version.

If Person2 does not accept the folder, she will be informed endlessly that I want to share the order with her, long after I have already put the bar back in the Android-UI.

If I then look into the web UI, I discover that there is the tick next to the folder that I accidentally shared, even though I removed the lock in the Android UI. So I remove the tick also in the Web-UI

So now there is no deadlock between the Android UI, and the hack is in the Web UI. Only you don’t see that. You think that if you have pushed the bar in the web UI back, then everything is over. And what is really happening? Person2 will continue to be notified that I want to share the folder with her.

After some hours I was informed by Person2 that Syncthing still want to share the Folder. Then I got my phone and found that it was true. The lock wasn’t pushed, but the tick was back in. If I now uncheck in both UI and close the program, the hack in the Web UI will reinsert itself and the Android UI will continue to share the folder with Person2.

Now if Person2 accepts the folder at some point, the data will be transferred even though I have taken the ticks out several times.

WHAT SHOULD HAPPEN IS LOGICAL FOR EVERYONE: Once the ticks have been removed, a notification should no longer be displayed on the Person2 Computer, and no single bit should be transmitted.

Person2 was using a Microsoft Version.

Please contact me if there are any Questions.

**Comment by imsodin** [comment] 2020-01-17 13:44
Duplicate of https://github.com/syncthing/syncthing-android/issues/1464 and further discussion on that happens at https://forum.syncthing.net/t/problem-un-sharing-folder-on-android/14352. Please do not create several issues about the same thing.

**Closed by imsodin** 2020-01-17 13:44 UTC
