### ISSUE TITLE
Syncthing silently breaks if permission gets removed

### ISSUE THREAD

**Issue by klement** [syncthing/syncthing-android#871] opened 2017-03-29 10:56 UTC
I recently tried a workaround for Nexus 6p battery drain issues - reset all app permissions. I went for 2 weeks before I noticed that syncthing isn't doing anything. The notification just says "syncthing is running" when charging & on wifi - per my config, but it isn't syncing because - of course, permission denied. Error is shown above folder icon once syncthing is opened. Clicking on that icon/text causes syncthing to force close.

Please **please** _please_ make syncthing loudly complain when the permission is not granted. There is zero reason to continue even running if the permission is not granted since, obviously, syncthing cannot do the one job it is supposed to do.

I would suggest to add an extra error notification (the non-permanent like "new email") kind - similar to e.g. gmail's "sign-in error" with a warning triangle or exclamation mark or a hypnotoad asking the user to click it and grant the permission.

Of course, the notification should show only if there is a valid sync configuration - meaning there is a shared folder and at least one peer with whom the folder is shared.

**Comment by Nutomic** [comment] 2017-03-31 04:00
We check the permission whenever you launch the app. But you're right, you wont notice if you dont start the app. We should probably fix this by showing notifications for any errors reported by Syncthing (shouldnt be too hard with the events API).

**Comment by Catfriend1** [comment] 2018-05-28 06:52
This is similar to issue https://github.com/syncthing/syncthing-android/issues/747 .
My suggestion to solve both issues which I appreciate having your feedback before implementing this: Google doesn't like permissions being checked by something like a permanent timer in an app (that could result in problems getting the app approved in play store...) I would instead catch error events in the EventProcessor.

If there are errors that arise when the storage permission got removed at runtime, a permission check is done in the app to verify that has been really done. If the user removed a permission, Syncthing will show a notification (maybe or quit?) that it cannot go on syncing.  I'll get the according events syncthing events API issues on that case by testing with the reproducer of #747) and removing the storage permission at runtime.

@AudriusButkevicius @Nutomic Would you agree with a PR like that? Any suggestions how to handle this even better?

**Comment by AudriusButkevicius** [comment] 2018-05-28 11:47
I think we should just check for pernissioms as we access things that require the permissions and be done with it. If peoplw refuse some permission, we print a message as to why we are quitting.

**Comment by Catfriend1** [comment] 2018-05-28 17:15
@AudriusButkevicius Sorry, but we can't "check for things as we access them" because we don't access the files using the Android Java Framework. So on my opinion, the only spot where we can catch an effect that may have permissions as a cause is the Events API. Or did I miss something?

**Comment by AudriusButkevicius** [comment] 2018-05-28 17:31
Well we can always as for permissions to access files when we open the app if it's not there.

**Comment by Catfriend1** [comment] 2018-05-28 19:00
We are already asking if necessary on app start (best practice).
So is my feeling right you better would like this ticket closed as wontfix instead of a hacky workaround with detecting runtime perm removal by events api check trigger?

**Comment by AudriusButkevicius** [comment] 2018-05-28 19:15
Well why didn't then syncthing as for permissions when it was started in this case?
As it seems the user had to go to the web ui to figure out what's actually up.

**Comment by Catfriend1** [comment] 2018-05-28 19:40
Thats because the user revoked the permission while syncthing was started and running in the background.

**Comment by AudriusButkevicius** [comment] 2018-05-28 20:20
Right, so why did switching back to the app not ask for permissions?

**Comment by Catfriend1** [comment] 2018-05-28 21:28
We currently dont check for the permissions on resume of the activity. If the user runs syncthing as a service we dont know if he gets back to the activity in short or long term. But maybe we should check onResume() as the event polling would be too expensive always running in the background wjth keep awake.

**Comment by Nutomic** [comment] 2018-05-29 12:47
I think the events api is the best option for this. Then we can just show a notification from there. The notification should go to either MainActivity or FirstStartActivity, with the permission prompt. Plus there should be a permission request in MainActivity#onResume (or you could finish() MainActivity and start FirstStartActivity for the permission request).

**Comment by Catfriend1** [comment] 2018-05-29 19:53
Sorry for disappointing you a bit, I also thought at a first glance events API would be best. Playing around some test cases with the app I made an observation relevant to this:
When I switch to another app and syncthing is running in the background, the verbose line "polling ..../rest/events" is not issued anymore after some seconds of waiting time. Getting back to the app, it continues to read events. Does it work for you getting events queried by the wrapper from the REST when you're running the app in the background after switching away from it?

If my observation is right, MainActivity#onResume might be the only and best place to re-check permissions and quit by showing a message if the user revoked the storage permission.

**Comment by Nutomic** [comment] 2018-05-29 21:31
Sorry I don't really have the time and tools to test this. But in that case, we could still have a task in the background service that checks the permissions every minute or so.

Btw if events don't work in the background, that might be a bug, as it is used to notify about new devices and folders.

**Comment by Catfriend1** [comment] 2018-06-01 17:56
I'll put this later to a new issue as I observed it on debugging: EventProcessor doesnt make calls according to the log to the rest when I leave the app.
Instead, permanent calls to the folder endpoint are made every 5 seconds draining the battery
 06-01 19:53:38.216 V/ApiRequest(27237): Performing request to https://127.0.0.1:8384/rest/db/status?folder=lg-h815-Bilder

**Comment by Catfriend1** [comment] 2018-06-01 18:14
About perm revoke, heres a log I will need later:

06-01 20:09:42.405 I/ActivityManager(952): Killing 27237:com.nutomic.syncthingandroid.debug/u0a11 (adj 900): permissions revoked

06-01 20:09:42.410 W/ActivityManager(952): Scheduling restart of crashed service com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.service.SyncthingService in 1000ms

So this would be the suggested Place for rechecking the permission.

**Comment by Catfriend1** [comment] 2018-06-01 18:18
Second bug: pressing home and switching apps I can still go back to the main UI seeing syncthing running and getting no notice about perms. Then I went back to the app drawer , started syncthing.debug , I was asked to grant perm I denied and ended on a white screen. Pressing back brought me to the main UI showing st still running.

**Comment by Catfriend1** [comment] 2018-06-02 14:03
Solved by commit https://github.com/Catfriend1/syncthing-android/commit/2fece28ab5f02ed905394983f0568e7816b09a7d

**Closed** 2018-06-02 19:49 UTC
Labels: bug
