### ISSUE TITLE
Run conditions don't always behave as expected

### ISSUE THREAD

**Issue by Ingegneus** [syncthing/syncthing-android#1774] opened 2022-03-25 22:46 UTC
Sometimes when my phone is connected to AC power syncthing doesn't start. Unplugging and plugging back in usually resolves the issue.
I am using the lastest version of the app on Android 9.

**Comment by linesquarecube** [comment] 2022-03-26 12:28
First of all, thanks to the Syncthing Devs for this great piece of SW :heart: 

Unfortunately i have the same isse, but unplugging and plugging back in does not sove the problem for me. What usually helps me for some days is to start the App manually and "swipe up" to put it in the background. This has to be done again every 3-4 days. Running the App on a Pixel4a with CalyxOS, Android 12.

Thanks for looking into this :)

**Comment by imsodin** [comment] 2022-03-26 15:13
Duplicate of https://github.com/syncthing/syncthing-android/issues/1595

**Closed by imsodin** 2022-03-26 15:13 UTC
