### ISSUE TITLE
Buttons are invisible, but still function correctly

### ISSUE THREAD

**Issue by NAL60** [syncthing/syncthing-android#1950] opened 2023-07-21 12:23 UTC
Buttons are invisible in top right corner of some screens, but still function correctly.

I’m using a Samsung A13 running Android 13

Syncthing version is 1.23.6 Fresh install yesterday after factory reset.

Nigel

![image](https://github.com/syncthing/syncthing-android/assets/140171572/0c6bf0de-359f-4ad1-a616-731637f013f5)

![image](https://github.com/syncthing/syncthing-android/assets/140171572/1ba103d8-524e-45f2-9eea-e02c7a928af9)

**Comment by tomasz1986** [comment] 2023-07-21 12:30
Should already be fixed in the latest Release Candidate (see https://github.com/syncthing/syncthing-android/releases/tag/1.23.7-rc.1.2).

**Comment by imsodin** [comment] 2023-07-21 13:17
Duplicate of https://github.com/syncthing/syncthing-android/issues/1947

**Closed by imsodin** 2023-07-21 13:17 UTC
