### ISSUE TITLE
feature flag are cleared after a while

### ISSUE THREAD

**Issue by bbigras** [syncthing/syncthing-android#1648] opened 2021-05-01 17:08 UTC
I can use the web interface to add the "untrusted" feature flag, but it gets cleared after a while.

While testing, it might have something to do with restarting syncthing from the android app (not the web ui). Not sure.

### Version Information

    App Version: 1.15.1
    Syncthing Version: v1.15.1
    Android Version: Android 11

**Comment by imsodin** [comment] 2021-05-04 16:36
This specific issue isn't problematic anymore, since the feature flag has been removed in v1.16.0. However I assume the general problem is that the config is "recreated" in java and is pretty out-of-date, thus might clobber some values.

**Comment by imsodin** [comment] 2021-12-19 17:29
Closing as a duplicate of https://github.com/syncthing/syncthing-android/issues/1257

It's not the same effect, but the same cause: Outdated config in java, respectively not using the new PATCH methods.

**Closed by imsodin** 2021-12-19 17:29 UTC
