### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by edrex** [syncthing/syncthing-android#791] opened 2016-11-27 08:51 UTC
I've been seeing (very) frequent crashes for a few releases now. 

I've done `adb logcat | grep synthing` from starting the app to crash (almost immediate - sometimes it doesn't crash though) but it seems like the log has a lot of sensitive information. Can I send to a private email? It may be worth building in a crash reporter to try to collect more reports and stabilize the app.

TBH, I'm on the edge of dropping syncthing if I can't get the android client to be stable. I wonder if this gomobile hybrid approach for long running services isn't just a dead end since it seems to be so difficult to get it to run well.

**Comment by wweich** [comment] 2016-11-27 09:21
I think, this is a duplicate of #778.

**Closed** 2017-08-25 10:10 UTC
