### ISSUE TITLE
After enabling root and adding `/data/data`, it fails to load again.

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#524] opened 2015-12-20 20:50 UTC
I've enabled root and added `/data/data` using WebUI. It synchronized (except of some volatile files from currently running applications, including Syncthing itself).

But after some time I noticed a loop of `Syncthing requesting superuser access for command lib.....so` messages. Even after disabling Syncthing in SuperUser I can't open Syncthing (it is stuck on "loading"), cant' reach settings. No error messages (apart from some transient toaster message about some configuration) shown. I haven't yet checked the logcat.

I think Syncthing for Android should rate limit restart attempts and it should allow to go to settings even if the engine cannot be started for some reason.

**Comment by licaon-kter** [comment] 2015-12-20 22:20
Still a duplicate of https://github.com/syncthing/syncthing-android/issues/453

/close

**Comment by vi** [comment] 2015-12-20 22:23
Now I see my problem in comments to #453, but not in the title (which is just about GUI, not about failing to load).

Either title of #453 should be extented ("and application fails to load after enabling root") or generalized ("Problems with using root mode").

**Comment by Nutomic** [comment] 2015-12-21 21:08
Yeah there seem to be various issues related to root. Can you post a logcat?

**Comment by vi** [comment] 2016-02-06 14:39
Workaround for turning off root mode:

1. As root, edit `/data/data/com.nutomic.syncthingandroid/shared_prefs/com.nutomic.syncthingandroid_preferences.xml`, setting `use_root` to `false`.
2. Change owner for all touched files from `root` to the respective user, for example, `chown u0_a143:u0_a143 /data/data/com.nutomic.syncthingandroid/files/* /data/data/com.nutomic.syncthingandroid/files/index-v0.11.0.db/*`
3. Force restart Syncthing, maybe multiple times.

Unfortunately folders seem to has been reset either by this or because of some previous upgrade and device ID reset to one like `AAAAAAAAAAA-AAAA-A`, but this may be unrelated.

**Comment by Nutomic** [comment] 2017-09-21 03:36
This should be fixed by #949.

**Closed by Nutomic** 2017-09-21 03:36 UTC
Labels: bug, root
