### ISSUE TITLE
changing gui listening address fails

### ISSUE THREAD

**Issue by Eddy2909** [syncthing/syncthing-android#493] opened 2015-11-13 12:06 UTC
everytime I try to change the address from 127.0.0.1 to 0.0.0.0 the app doesnt change the address and doesnt prompt me to restart..

It only worked using the webgui inside the app..

**Comment by Nutomic** [comment] 2015-11-15 20:00
The restart prompt works now, but the change doesn't always seem to apply after the restart. Haven't looked into that yet.

**Comment by Nutomic** [comment] 2016-02-25 17:51
Just noticed that this is a duplicate of #442.

**Closed by Nutomic** 2016-02-25 17:51 UTC
Labels: bug
