### ISSUE TITLE
Run while open

### ISSUE THREAD

**Issue by michaelilyin** [syncthing/syncthing-android#2074] opened 2024-04-06 19:04 UTC
Hi! I've noticed battery draining issues on android with constatnt connection. I set mode "only when charging" but it is not so useful when you need to sync files "right now". 

What if on the modal which is shown when sync is disabled add third option "run for this launch" or "run until not synced" or "run for N minutes"?

It would be helpful to sync files manually when it is needed. Or even add some kind of widget for instant launch?

**Comment by imsodin** [comment] 2024-04-06 20:32
Duplicate of https://github.com/syncthing/syncthing-android/issues/1031 and/or https://github.com/syncthing/syncthing-android/issues/769. Also https://github.com/syncthing/syncthing-android?tab=readme-ov-file#no-feature-request-taken-feature-contributions-case-by-case

**Closed by imsodin** 2024-04-06 20:32 UTC
