### ISSUE TITLE
Allow syncing some directories via Mobile Data

### ISSUE THREAD

**Issue by mic-e** [syncthing/syncthing-android#1764] opened 2022-02-23 18:57 UTC
Some of my syncthing directories are large and should only be synced when connected to an unmetered Wifi (e.g.: Photos).
Others are low-bandwidth and should be synced always (e.g.: Orgzly TODOs).

It would be nice to have fine-grained control over for which directories Syncthing runs.

**Comment by AudriusButkevicius** [comment] 2022-02-23 20:03
Dupe of #511 

Please search before opening new issues.

**Closed by AudriusButkevicius** 2022-02-23 20:03 UTC
