### ISSUE TITLE
Enhancement request: local changes reported on the notification bar

### ISSUE THREAD

**Issue by rdarioc** [syncthing/syncthing-android#513] opened 2015-12-09 13:41 UTC
Would it be possible to be notified of changes on the local file system directly in the notification bar of Android?

Maybe this option could be enabled on a per directory basis or even per type of event (new file, deleted file, modified file, etc).

 I keep syncthing always on and it would be nice to have a simple notification informing when a large new file has been downloaded.

Thanks
Rosario

**Comment by Nutomic** [comment] 2015-12-09 13:52
Duplicate of #130 ;)

**Closed by Nutomic** 2015-12-09 13:52 UTC

**Comment by rdarioc** [comment] 2015-12-09 13:55
Sorry man, I swear I searched it before posting. My fault. Well, hope it will be implemented some day.
Great work anyway.
