### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by DrSchnagels** [syncthing/syncthing-android#1092] opened 2018-05-16 21:53 UTC
Hi there!
I tried to get into programming on my own with go but VirtualBox doesn't work for me under Windows.
Under Ubuntu as VM I cannot emulate an Android device... :(

Anyway, my idea was to program a dark mode für Syncthing Android. I'm sure you get the idea (Amoled & not being blinded at night from the white screen of ST).

It would be nice to have. Maybe someone else is capable of doing that. I'm just a mechanical engineer lol.
If anyone knows a different Virtual Machine thingy than VirtualBox which can handle pass-through of of this Intel VM stuff to an Ubuntu Android Studio Android Device... I'd love to hear about that!

Thanks!

**Comment by Nutomic** [comment] 2018-05-17 10:31
You don't need any VM. Just install Android Studio and connect your phone via usb.

**Comment by lokesh-krishna** [comment] 2018-05-22 08:00
Duplicate of #653?

**Comment by AudriusButkevicius** [comment] 2018-05-22 08:19
Yeah

**Closed by AudriusButkevicius** 2018-05-22 08:19 UTC
