### ISSUE TITLE
Layout of share function broken on Android 11 after upgrade to Material Design 3

### ISSUE THREAD

**Issue by adolfintel** [syncthing/syncthing-android#1925] opened 2023-06-23 17:24 UTC
See screenshot below.

To reproduce:
* Open the gallery or a file manager and select something
* Share with syncthing
* The save button is invisible (but works), layout is slightly messed up

### Version Information

    App Version: 1.23.5 from F-Droid
    Syncthing Version: 1.23.5
    Android Version: Android 11 (LineageOS 18)

![photo_2023-06-23_19-19-04](https://github.com/syncthing/syncthing-android/assets/16307689/142328e3-c330-463d-a837-d1b8e6099905)

**Comment by imsodin** [comment] 2023-06-23 17:54
Duplicate of https://github.com/syncthing/syncthing-android/issues/1918 (fix available in the latest beta release)

**Closed by imsodin** 2023-06-23 17:54 UTC
