### ISSUE TITLE
Syncthing won't start when run conditions are met

### ISSUE THREAD

**Issue by jebeld17** [syncthing/syncthing-android#922] opened 2017-07-17 03:46 UTC
Even when my specific run conditions are met - WiFi connected, disabled battery savings, allowed ST to bypass Android Doze feature - Syncthing still won't start, and furthermore gives me an error upon starting the app telling me that Syncthing is not allowed to run and that I need to change my settings if I want it to run.

Adding to this, if I force quit the app in my Android settings and re-open it, I'm not given the error anymore and the app runs fine.

**Comment by licaon-kter** [comment] 2017-07-17 06:01
Device? Android version? App source (F-Droid/Google)?

**Comment by Unrud** [comment] 2017-07-18 18:21
If you are using Android 7.0 this is probably a duplicate of #783.

**Comment by jonathanturcotte** [comment] 2017-10-20 20:08
I'm having this issue on a Oneplus 3, Android 7.1.1. If either run only when charging/run only on wifi is selected it won't run, even when I'm connected to wifi and charging. I've tested it with normal charging vs dash charging, and no difference. 

App version is 0.9.17. I have also tried a full uninstall/reinstall of the app with no success.

Are there any logs that could be helpful?

**Comment by licaon-kter** [comment] 2017-10-21 07:26
`Run in foreground` is ON?

**Comment by jonathanturcotte** [comment] 2017-10-21 15:20
Run service in foreground fixed it for me, thanks!

 Is this now a requirement for run condition checking on higher Android versions?

If it is, I'd vote to move it out of the Experimental menu, as nothing in here should need to be set for the app to work properly.

**Comment by Nutomic** [comment] 2017-10-23 14:17
Yes that makes sense.

**Closed** 2017-10-23 14:17 UTC
