### ISSUE TITLE
Syncthing is spinning "Loading..." and nothing else happens

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#687] opened 2016-06-25 01:32 UTC
Nothing interesting in logcat... Something like this:

```
$ adb logcat -v time |& grep -i syncthing
06-25 04:25:36.350 I/log     (15228): Launching app://com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity
06-25 04:25:36.370 I/ActivityManager(  496): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.nutomic.syncthingandroid/.activities.MainActivity} from pid 15228
06-25 04:25:36.600 D/SyncthingService(18212): All SSIDs allowed for syncing
```

Syncthing is supposed to be running in this configuration. No reaction to back button. No error message. Can't enter settings. Etc.

For a good app I don't expect such things to happen.

**Comment by vi** [comment] 2016-06-25 01:42
Meanwhile the actual underlying Syncthing is working now.

Version of Syncthing-android is 0.7.20 from F-Droid.

**Comment by vi** [comment] 2016-06-25 01:57
After a while it has just crashed:

```
06-25 04:56:38.390 D/AndroidRuntime(19376): Shutting down VM
06-25 04:56:38.390 W/dalvikvm(19376): threadid=1: thread exiting with uncaught exception (group=0x41ac0c50)
06-25 04:56:38.390 V/GetTask (19376): Calling Rest API at https://127.0.0.1:57924/rest/system/status
06-25 04:56:38.395 E/AndroidRuntime(19376): FATAL EXCEPTION: main
06-25 04:56:38.395 E/AndroidRuntime(19376): Process: com.nutomic.syncthingandroid, PID: 19376
06-25 04:56:38.395 E/AndroidRuntime(19376): java.lang.NullPointerException
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at org.json.JSONObject.<init>(JSONObject.java:155)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at org.json.JSONObject.<init>(JSONObject.java:172)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at com.nutomic.syncthingandroid.syncthing.RestApi$2.onPostExecute(RestApi.java:270)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at com.nutomic.syncthingandroid.syncthing.RestApi$2.onPostExecute(RestApi.java:266)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at android.os.AsyncTask.finish(AsyncTask.java:632)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at android.os.Looper.loop(Looper.java:136)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at java.lang.reflect.Method.invokeNative(Native Method)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at java.lang.reflect.Method.invoke(Method.java:515)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
06-25 04:56:38.395 E/AndroidRuntime(19376): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by licaon-kter** [comment] 2016-06-25 06:19
Android version?
Did you ever toggle root for syncthing?

**Comment by vi** [comment] 2016-06-25 11:48
4.4.2
Previously was turned on, after reinstalling wasn't re-enabled as far as I remember.

**Comment by licaon-kter** [comment] 2016-06-25 12:02
Well, you might have "corrupted" the install folder when you've previously enabled root.

Eg:
* install
* give root to syncthing
* do something
* uninstall (but old folder was not deleted since it was edited by root; this should not happen but read issue linked below) 
* reinstall (same folder)
* issues (since the syncthing process can't control files in folder since now it has no root access)

This sounds to me as a duplicate of #453 aka DO NOT ENABLE ROOT since it can't be handled correctly now.

How to fix: uninstall syncthing, then with a root enabled file manager (eg. Total Commander ) go to */data/data/*, */data/user/*, */sdcard/Android/data/* and whatever, look for *com.nutomic.syncthingandroid* folders and delete them all, then reinstall and NEVER ENABLE ROOT.

Retry...

**Comment by vi** [comment] 2016-06-25 19:03
How do I avoid messing with SyncthingAndroid configuration again.

I've already did something like that before (at least I got new ID and needed to set up folders anew) and didn't enable root again. It was working for some time.

I doubt that it is because of root.

**Comment by vi** [comment] 2016-06-25 19:05
The "Run Syncthing as Superuser" checkbox is currently off.

**Comment by licaon-kter** [comment] 2016-06-25 21:54
What's your use case for root (in syncthing) exactly?

**Comment by vi** [comment] 2016-06-25 21:56
It's offtopic in this #687, but I though Syncthing would just back up entire device (including installed programs and their settings). It probably got stuck when falled into recursion when trying to backup Syncthing's data directory (or something like that).

It wasn't recently. I've reinstalled and updated SyncthingAndroid multiple times since those experiments.

**Comment by licaon-kter** [comment] 2016-06-25 22:01
Well, that's a problem, you see apps get UIDs on install, restoring needs to account for that and change permissions and owners and all that.
Syncthing is not a proper tool for this task, see either [oanbackup](https://github.com/jensstein/oandbackup) or [TitaniumBackup](http://www.titaniumtrack.com/titanium-backup.html).

**Comment by jebeld17** [comment] 2016-06-26 03:18
I've gotten the same thing, on several devices. 
All my Android devices run 6.0 or higher.

**Comment by jebeld17** [comment] 2016-06-26 11:40
I never enabled root. I did read the linked issues.

**Comment by Nutomic** [comment] 2016-06-29 21:28
I've encountered this myself a few times. Don't think I used root in that case either, there's probably a bug somewhere in the startup code.

**Comment by Mannshoch** [comment] 2016-06-29 21:29
I had the same problem like the thread starter and an other Problem to. I let this loading after installing fom f-droid and start running and did some other things (thought it calculate keys or something similar). After a while i tried to enter Internet on mobile phone as android told me he canceled Internet because Data-limit. The stats told me that syncthing consumed until this time around 100 MB. Thanks God the end of Month isn't far way.

**Comment by scienmind** [comment] 2016-07-06 13:47
Related: #634

**Comment by licaon-kter** [comment] 2016-07-06 14:28
Got one these days too. Stop/start fixed it though.

**Comment by DrSchnagels** [comment] 2016-07-11 10:44
Another problem: If this happens, then often the stignore file is ignored.
All files are synced then.

**Comment by go2null** [comment] 2016-08-25 01:18
Was having this and it went away with, IIRC, v0.8.0.

**Comment by scienmind** [comment] 2016-08-25 07:52
I still experience this from time to time

**Comment by Nutomic** [comment] 2016-08-25 11:19
Can anyone with this problem check if Syncthing is actually running in the background? Eg by checking if `http://localhost:8384` opens the Syncthing. That will let us narrow down where exactly the problem is.

**Comment by vi** [comment] 2016-08-28 16:25
Got `Loading...` again.

```
# busybox netstat  -tl -n -p                                  
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:57924         0.0.0.0:*               LISTEN      31748/libsyncthing.
tcp        0      0 :::52460                :::*                    LISTEN      31748/libsyncthing.
```

Remove Syncthing (for Linux) instance shows the device as connected.

Port 8384 is closed.

**Comment by Nutomic** [comment] 2016-08-28 21:43
So we check if Syncthing is started by polling port 8384 (or whatever is set in the config.xml). If that port is closed, we will keep polling forever. Did you do anything that would result in the port staying closed? Or is the web interface possibly running on a different port somehow?

**Comment by AudriusButkevicius** [comment] 2016-08-28 22:10
It will pick automatically a different port oof 8384 is taken, potentially due to some strain process.

**Comment by Nutomic** [comment] 2016-08-28 22:34
@AudriusButkevicius We read the port from the config, so that is normally not a problem. 

@vi Can you figure out what port the web interface is running on (if any), and check if that is the same port listed in the config file?

**Comment by vi** [comment] 2016-08-29 10:57
Where is the config file?

I didn't change any configuration regarding to web interface.

Note that currently Syncthing is tied to Wi-Fi presense, and with flaky Wi-Fi connection it can stop and re-start in quick succession. Maybe Syncthing fails to bind to 8384 due to TIME_WAIT sockets, ignores this error and continues with a randomly assigned port?

**Comment by vi** [comment] 2016-08-29 12:21
Can Syncthing listen UNIX socket instead of TCP socket for the web interface?

**Comment by AudriusButkevicius** [comment] 2016-08-29 14:20
No, because this makes no sense in context of browsers.

**Comment by vi** [comment] 2016-08-29 14:59
It is hovewer doable: https://stackoverflow.com/questions/14771172/http-over-af-unix-http-connection-to-unix-socket

Using UNIX socket can also decrease the attack surface, avoiding API keys or other after-connect checks.

**Comment by AudriusButkevicius** [comment] 2016-08-29 15:07
Sure, many things are possible, it doesn't mean they are rational.

**Comment by Nutomic** [comment] 2016-08-29 17:59
[See the readme](https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions). You can also check what port Syncthing shows in the [logs](https://github.com/syncthing/syncthing-android/blob/master/CONTRIBUTING.md).

**Comment by edrex** [comment] 2016-08-31 22:00
@Nutomic when syncthing-android is in the permanent "Loading..." state https://localhost:8384 doesn't connect. After swiping away the app and starting it again I can connect to the web ui.

Sorry for the slow response.

**Comment by Nutomic** [comment] 2016-09-01 19:24
Do you mean you can't open localhost:8384 in the browser? In that case, can you check (eg using top on command line) if `libsyncthing.so` is running?

**Comment by edrex** [comment] 2016-09-01 20:07
`libsyncthing.so` isn't running:

```
u0_a104@msm8916:/data/data/com.arachnoid.sshelper/home $ ps|grep sync
u0_a171   19785 353   694400 64216 SyS_epoll_ 00000000 S com.nutomic.syncthingandroid
```

**Comment by Nutomic** [comment] 2016-09-02 16:22
So for some reason, Syncthing is either not started, or it crashes and isn't restarted correctly. Can you check if there's any error in `adb logcat`? Particularly `adb logcat -s SyncthingRunnable:v SyncthingNativeCode:v`.

**Comment by edrex** [comment] 2016-09-02 17:59
Yes, I believe it is crashing or being killed by the system and not restarting. I try to get a good logcat. Since the actual error probably happens when the phone is idle for awhile, will I have to have adb connected at idle, or is there a way to queue up the log on device?

**Comment by Nutomic** [comment] 2016-09-04 00:20
I think adb also shows older logs when you run the command. You can also try to use a logcat app instead.

**Comment by MartinX3** [comment] 2016-12-26 12:02
Same problem here.
Syncthing wants to restart, because i changed the settings or it get stopped by android in the background.
I open the APP and recieve the "Loading..." screen.
My Syncthing-Network is telling me, that my smartphone is offline.
And the APP is in this "Loading..."-Screen forever, until i force kill the APP and start it manually.

**Comment by jebeld17** [comment] 2016-12-29 19:55
#3826 may be related

**Comment by m-khvoinitsky** [comment] 2017-06-29 13:35
I also experience this issue constantly on three different devices (two of them have LineangeOS, one OxygenOS) — the application works properly only for about few hours before subj happens.
I've even developed a habit to restart Syncthing most times when I do something on my devices.
Similar issue #481 is definitely not my case — other devices doesn't see the affected ones.

May be there is some way to build a sort of debug version which will help to determine the cause of the issue?

**Comment by 2SI3NX** [comment] 2017-10-03 15:39
Um im having the same problem the other day it started all of a sudden.. What can i do to fix this and to actually get into syncthing without losing my settings??

**Comment by MartinX3** [comment] 2017-10-03 20:17
Whitelisting this APP
I run it with foreground priority.
Drains the battery more, but this workaround works.

And I activated the WLAN Option, so this APP only runs in certain WLAN Networks.

**Comment by nyancow** [comment] 2017-10-04 10:08
@2SI3NX see #957, may be related

**Comment by 2SI3NX** [comment] 2017-10-04 18:45
The only thing that solved the problem since it started doing that.. was to Clear Data and re-configure all the settings manually again.
BTW this problem started happening from Sept 19.

**Comment by Nutomic** [comment] 2017-10-08 07:00
I've added a button that lets you open the logs if Syncthing takes more than 30 seconds to load. If you get this issue again, make sure to check the logs, and open a new issue (with logs), if a bug prevents Syncthing from starting.

**Comment by Catfriend1** [comment] 2018-04-22 13:28
... and since then, no more reports of the loading issue were posted here.

**Closed by Catfriend1** 2018-04-22 13:28 UTC
Labels: bug
