### ISSUE TITLE
Persistent notification of "Syncthing is Running" even when notifications set to none

### ISSUE THREAD

**Issue by kschach** [syncthing/syncthing-android#981] opened 2017-10-26 18:08 UTC
For the last few days I've been getting a persistent "Syncthing is running" notification even when the Behaviour -> Notification setting is set to "None". I've tried to change this setting and change it back to no avail. I can block all notifications from Syncthing using Android, but I suppose this would prevent new device / new folder notifications as well.

Let me know if you need further info.

Thanks,
Kevin

### Version Information

    App Version: 0.10.0-beta1
    Syncthing Version: v0.14.40-rc.1
    Android Version: Android 7.12 / PureNexus 7.1.2-20170725-OFFICIAL
    Device: Nexus 6P

**Comment by licaon-kter** [comment] 2017-10-27 06:11
Did you enable the use of the foreground service?

**Comment by Nutomic** [comment] 2017-10-28 12:27
Yes, this is the expected behaviour now if "run in background" is enabled. It makes sure that the service can't be killed by android accidentally and is required in Android 8.

**Comment by nekr0z** [comment] 2017-11-02 05:35
There most definitely should be some other way to go about this. Currently the "running in background" Android 8 notification is shown for syncthing even if run conditions are not met. While I understand that in this case it's the part that waits for run condidtion to be met that's causing this notification, it is confusing, especially for less tech-savvy users.

Maybe an option would be to schedule these checks to be run at periods. I understand this would be a trade-off, but I can see situations where it aould be welcome, at least as an option.

Somehow apps like GMail, messengers and even Tasker manage to get their job done without hanging the constant notification. Granted, Tasker in this case tends to take longer to act, but it still works. (This last paragraph hopefully shows how little idea I have about all the under-the-hood aspects.)

**Comment by licaon-kter** [comment] 2017-11-02 05:59
Android 8.**1** will allow you to hide such notification.

**Comment by capi** [comment] 2017-11-06 19:00
Do we really need to have the service running with foreground priority even though we are just waiting for the run conditions to be met? Actually, it would even be better if the service is `finish()`-ed until the run-conditions are met (the service should be created/restarted automatically by the broadcast receivers for the various events).

(Disclaimer: I'm currently still running a very old self-compiled version, since it does everything I need, going to have to have a look at recent (i.e. last half year) changes in the code and how things are working now.)

**Comment by Nutomic** [comment] 2017-11-07 04:00
Android 8 doesn't let you listen to battery/network events via receivers defined in the manifest (https://stackoverflow.com/a/45819605/1837158). 

Of course it still works on older Android versions, but there have been many complaints that Syncthing isn't started when it's supposed to. Anyway there is no perfect solution, and we need some kind of compromise.

**Comment by capi** [comment] 2017-11-07 07:48
Oh, I see. But do we really need to specify such a high API level? We could target a lower API level and benefit from the old behavior. At least that's how I understand the documentation.

**Comment by licaon-kter** [comment] 2017-11-07 08:07
Careful, as you are not allowed to downgrade API level in the future, iirc.

**Comment by Nutomic** [comment] 2017-11-08 14:26
Unfortunately I already upgraded the API level :/

**Comment by jebeld17** [comment] 2017-12-31 14:54
This is an Android 8.x limitation set by Google to keep apps from hiding their battery and data usage.

**Comment by trymeouteh** [comment] 2018-01-17 05:23
I get this notification too and I wish I can disable it. I will like to see notifications when Syncthing is syncing folders, has a new device that wants to be added or a new folder that wants to by synced. The notification takes up a slot in my notification bar.

**Comment by vsespb** [comment] 2018-02-01 08:11
On Xiaomi Redmi 4, Android 6.0.1, MIUI 8.0 I have lot's of other apps and services, none of them install persistent notification

**Comment by jurf** [comment] 2018-02-20 13:01
Yeah, isn’t there another way? How do all the other apps do it?

**Comment by licaon-kter** [comment] 2018-02-20 13:12
@jurf On Android 8 get [Hide notification....](https://play.google.com/store/apps/details?id=com.iboalali.sysnotifsnooze&hl=ro)

**Comment by nelsonblaha** [comment] 2018-02-20 17:41
@licaon-kter this app doesn't do the trick for me on 8.1.0. Anyway, it shouldn't be necessary. I'm no android expert but I observe that many apps run in the background successfully without keeping a notification in the tray.

**Comment by Catfriend1** [comment] 2018-05-07 06:34
Duplicate of https://github.com/syncthing/syncthing-android/issues/1048

**Closed by Catfriend1** 2018-05-07 06:34 UTC
Labels: question
