### ISSUE TITLE
Sharing to syncthing: "Save" button text is the same color as background when light system theme is active

### ISSUE THREAD

**Issue by JpTiger** [syncthing/syncthing-android#1928] opened 2023-06-30 03:15 UTC
When you share something to syncthing,  the save button is invisible because the text is the same color as background. I didn't even know it was there until I tried again after dark and the color scheme changed to match my system settings

**Comment by imsodin** [comment] 2023-06-30 08:36
Duplicate of https://github.com/syncthing/syncthing-android/issues/1925

**Closed by imsodin** 2023-06-30 08:36 UTC
