### ISSUE TITLE
Lost linked devices aftere app update

### ISSUE THREAD

**Issue by urza** [syncthing/syncthing-android#252] opened 2015-03-17 06:21 UTC
After updating the Syncthing app to latest version (0.5.20) from Play store, my linked devices are gone. The folder persisted, but no devices (from previously connected and working) are listed and Syncthing is not syncing any folder.

Also the "Device ID" in the left panel is empty (see attached picture).

Edit: I have Samsung Galaxy Note2 GT-N7100 with Android 4.1.2

![syncthing_id_empty](https://cloud.githubusercontent.com/assets/189804/6682267/225ace2c-cc76-11e4-82b0-f00efaa0e413.png)

**Comment by cedricbrx** [comment] 2015-03-17 06:50
Can confirm this on a HTC One M8 with Android 5.0.1
All my linked devices are gone, but other devices still "see" my phone

**Comment by Zillode** [comment] 2015-03-17 07:05
Duplicate of https://github.com/syncthing/syncthing-android/issues/243, already fixed

**Closed by Zillode** 2015-03-17 07:05 UTC
