### ISSUE TITLE
logging efforts to tactically avoid: "Failed to create a Syncthing config..."

### ISSUE THREAD

**Issue by orlin** [syncthing/syncthing-android#576] opened 2016-03-04 21:13 UTC
There is [an issue about the same (or similar) problem](https://github.com/syncthing/syncthing-android/issues/449) that has "Blackberry" in the title, though it applies to other phones as well.  I open this issue so people can share their attempts to bypass the issue and make syncthing for android usable while the real issue hopefully gets fixed.  This is about trial-and-error experience, observations of a user who doesn't know how to read the logs, or the code, or doesn't have the time to learn, etc.

I thought I found a way to [trick syncthing to sync my stuff](https://github.com/syncthing/syncthing-android/issues/449#issuecomment-190860878).  That worked for almost a whole day and concluded with the same problem.  So, leaving root until last doesn't lead to a stable state.  Conclusion: editing the config is not what causes this issue.  At least not editing as far as the user is concerned.

I don't make changes and yet a change happens - syncthing enters a state of "Failed to create a Syncthing config.", again...  Here are my observations about the context from a user's perspective:

1. it was syncing reliably for almost 24 hours, several times I made changes on the master and everything was good, at least as far as this one folder is concerned
2. having been away from location (no wifi = no sync), I come back and plug it in to charge, later I unplug the charge cord and notice the root flashing rapidly (cyanogenmod has the # indicator at the top) - this happens when syncthing fails to open and gives me the config error, alarmed I go into syncthing and what a relief: it gives me the web ui screen, everything still looks fine...
3. after looking around the expand-collapse info boxes, I press the "back" arrow (back to native ui) and the root starts flashing rapidly again, and now I get the error (syncthing ui quits and no longer opens)
4. getting the same root rapid flashes ever since, this happens for both wifi-off and charger-off even though I have asked syncting to only check for wifi on and that the charging doesn't matter (the problem could have been triggered by being away from wifi, but this bug doesn't seem to respect existing preferences)

Next, I will try try other approaches until something sticks, or I run out of ideas, or I get frustrated enough to quit trying for a while.  Some possible directions to explore:

1. Don't use the Web UI -- the back from web ui's screen is what broke syncthing last time, it seems...
2. Don't use "sync in the background" -- there will be no control over wi-fi, but at least sync will work when really needed.  Does this "not in background" mean manually opening the app and keeping it open on screen until all is in sync?
3. What else could one try?

**Comment by licaon-kter** [comment] 2016-03-04 21:15
/duplicate of https://github.com/syncthing/syncthing-android/issues/453

**Comment by orlin** [comment] 2016-03-04 21:22
Didn't notice that, sorry.  Guess I should have read through all the issues...  However, my goal is to trick it working with root on (and probably fail).  It did work for a while with root though, writing to sd card, and for that I do need root.  Naively, I think that if I try a few more times it can remain stable enough.  Maybe my waste of time could help find the root bug too.

**Comment by licaon-kter** [comment] 2016-03-04 21:51
See @Nutomic first 2 posts there.

Now, what exactly is your need here? You sync what from where?

**Comment by Nutomic** [comment] 2016-03-19 17:42
Yeah this looks like a duplicate of existing issues. Unfortunately, there seem to be some problems with root. I don't use Syncthing with root myself, so I'm not motivated to spend a lot of time fixing them. Did you check if there's anything relevant in the logs?

**Closed** 2016-04-10 15:11 UTC
Labels: duplicate

**Comment by jult** [comment] 2016-10-29 18:39
May be a duplicate, it's still unsolved! Just started with syncthing on my (up to date) Android 6 device (Samsung N910C, Exynos). The solution posted at #453 did not solve it for me..
