### ISSUE TITLE
The new version don't respect run only on wifi

### ISSUE THREAD

**Issue by ediazrod** [syncthing/syncthing-android#870] opened 2017-03-29 05:13 UTC
The new version on sync don't respect run conditions only run on wifi
### Version Information

    App Version: 0.9.8
    Syncthing Version: v0.14.25
    Android Version: Android 7.0 (Oneplus 3T)

The new version don't respect the run conditions to run only on wifi, but it is works run only if the charger are connected.

To test enable run conditions (Run only on wifi) and you will see. connect you charger.

The last version works ok, But this new one not.

**Comment by Nutomic** [comment] 2017-03-29 07:03
I suspect this is the same as previous issues, because we havent changed anything regarding wifi conditions.

**Comment by bungabunga** [comment] 2017-04-09 21:54
Same here.

> Xperia XZ
> Android 7.0
> Latest version Syncthing Android

**Comment by snpalavan** [comment] 2017-06-12 21:56
Still same issue here, Wi-Fi connected, set to run only in Wi-Fi, but asks to change settings. Starts working if I force close, though.

**Comment by bungabunga** [comment] 2017-06-13 20:52
@snpalavan which version of android do you have? i only experienced this behavior on 7.0.0, not on 6.0.0 or 7.1.1. the device is Xperia XZ.

**Comment by snpalavan** [comment] 2017-06-14 19:39
@bungabunga i have a Samsung GS8+ (SM-G955U) running Android 7.0 and Samsung Experience 8.1. I actually have started having a new issue where Syncthing no long loads on startup (or soon thereafter) when connected to Wi-Fi, I have to manually run it before it starts.

**Comment by snpalavan** [comment] 2017-06-20 21:10
Fyi this is still an issue in v0.9.11, v0.14.30. However, charger condition seems to work fine.

Also, a new issue introduced in this last version is that syncthing (not syncthing android) stops working after a few (5-10) min, including that the localhost website no longer functions and the folder info on ST android no longer functions

**Comment by Unrud** [comment] 2017-07-18 18:20
Duplicate of #783. Fixed by a3deb81c72bc502e5cfcb1d5a81193afb0c353a6.

**Closed by Unrud** 2017-07-18 18:20 UTC
