### ISSUE TITLE
Run on condition in specific folder

### ISSUE THREAD

**Issue by EHMilon** [syncthing/syncthing-android#2087] opened 2024-07-10 14:40 UTC
In the sync folder's advanced section, there should be options to select Run on condition, "Run on mobile data," and "Run on metered Wi-Fi." Occasionally, certain folders are too large to sync over mobile data. Conversely, some folders are lightweight yet crucial and require syncing across devices. I found it a bug of this software. So please fix it. 
### Version Information

    App Version: 
    Syncthing Version: 1.27. 3
    Android Version: Android 12

**Comment by imsodin** [comment] 2024-07-11 13:45
Duplicate of

**Closed by imsodin** 2024-07-11 13:45 UTC
