### ISSUE TITLE
why not integrate the web gui more tightly into syncthing-android wrapper?

### ISSUE THREAD

**Issue by micahscopes** [syncthing/syncthing-android#842] opened 2017-02-04 21:27 UTC
Okay... so I love Syncthing, even when it causes me to gripe.  My question is, why not integrate the web gui into the "android app"?  The syncthing-android wrapper is crap compared to the web gui (b.t.w. the web gui is really great!).  No offense, but it's just so sluggish and gives the impression that everything is unstable, even when the syncthing backend is actually pretty good.

I don't want to have to wait 8 seconds  for it to load and then wait 4 seconds to press "settings" and then wait 3 seconds for settings to open only for the whole thing to crash and I have to start all over again.  

So why not use the syncthing gui as the main gui for the wrapper?

**Comment by licaon-kter** [comment] 2017-02-05 08:07
What device? What Android version?

My experience in the other way around, the Android UI is snappy.

**Comment by micahscopes** [comment] 2017-02-05 17:09
Interesting!  Samsung Galaxy S4 with 6.0.1 (CM13)

I wonder if it has to do with my using an external SD card as internal
emulated storage.  Still, Resilio does not have these issues.  The sync
thing GUI crashes almost every time I use it. I should start saving the
crash logs.

**Comment by Nutomic** [comment] 2017-02-05 23:54
Yes, please post crash logs. The initial loading times are caused by Syncthing, they won't be any different for the web interface.

**Comment by Jalbre2** [comment] 2017-02-22 16:13
I find the Android UI very unreliable, it often seems to by lying to me(Saying disconnected when my NAS says otherwise and is showing transfers, for example).

I also hate that when starting the app, you can't get into the options or go to the WebGui until the app interface finishes taking forever with "Loading..." and the spinning circle animation. It even does this when the setting to run in the background is on. I don't get it. Sometimes that loading process takes 5+ minutes for me(Or even longer, which leads to me rebooting my phone or trying other things to get it working). My NAS also sometimes reports being connected and transferring while the android app spends a long time "Loading..."

My app has been "Loading..." the entire time I have been writing this comment. My NAS reports connected and "Up to Date" though! So weird.

**Comment by licaon-kter** [comment] 2017-02-22 17:19
@Jalbre2 Device? Android version?

**Comment by Jalbre2** [comment] 2017-02-22 17:20
Nexus 6P, 6.0.1

**Comment by st4856** [comment] 2017-02-27 04:33
Similar webgui hangs (despite sometimes files syncing) on Samsung Tab 2 running Jellybean, with a 32G external SD card, syncing 6G in 8 folders, low volume of change.. Also, if I've had to kill the process, the next startup might crash without logs. The slow/hung gui happens 90% of the time on the tablet. It also happens about 15% of the time on a Samsung S4 rooted on Kitkat. I've upgraded Syncthing a few times hoping it would improve, but no joy. For a while, I had the impression that starting Syncthing with wifi off, might reduce the frequency of hung gui starts, but then it seemed to no longer make a difference.

**Comment by gerroon** [comment] 2017-03-09 19:57
I prefer web gui to be the default ui as well. I find the app's gui is unstable, sometimes freezes, hard to tell if the syncthing working fine or not in the background. I find the web gui to be more reliable and more responsible to be honest.

Bear in mind that the apps becomes more and more unstable as the number of files in shares go up.

I am using Lollipop with samsung note 4

**Comment by jedie** [comment] 2017-03-20 20:11
Same here with v0.14.24 on Android 7.1.1

**Comment by Nutomic** [comment] 2017-09-04 02:18
With #578 implemented, you can start the app directly into the web gui (instead of showing the main screen). So I'm closing this issue.

**Closed by Nutomic** 2017-09-04 02:18 UTC
