### ISSUE TITLE
Can't edit folders with Wifi disconnected and "WiFi only" setting enabled

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#554] opened 2016-02-06 14:46 UTC
Editing folders and devices should be possible without actual sync running. Now it just offsers either to enable syncing or go away.

**Comment by AudriusButkevicius** [comment] 2016-02-06 15:16
No, it's not possible, due to how this whole thing works. It essentially runs the same binary as the desktop, just has the UI implemented in Android. So if syncthing is not running, you can't edit the config.

**Comment by licaon-kter** [comment] 2016-02-06 15:40
Duplicate of https://github.com/syncthing/syncthing-android/issues/540

/close

**Comment by vi** [comment] 2016-02-06 16:47
It can just edit Syncting's XML files without running Syncthing itself.

**Comment by Nutomic** [comment] 2016-02-07 18:20
It's a duplicate (not sure what title is better though). 

We don't edit the config directly, but use the Rest API instead. That's only available while Syncthing is running. We can probably avoid this problem in the future by running Syncthing, but pausing it.

**Closed by Nutomic** 2016-02-07 18:20 UTC
