### ISSUE TITLE
Create can spam multiple folders with the same ID

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing-android#354] opened 2015-04-14 13:41 UTC
Steps to reproduce:

1. Fill in everything in creating menu
2. Hit Create
3. Tap outside of the restart message (it is discarded)
4. Hit Create multiple times (nothing happens)
5. Restart

**Comment by Profpatsch** [comment] 2015-04-14 13:50
This might be due to #355.

**Comment by Nutomic** [comment] 2015-04-22 21:57
Closing this as duplicate of #355.

**Closed by Nutomic** 2015-04-22 21:57 UTC
