### ISSUE TITLE
Generating key is not finished on WSA

### ISSUE THREAD

**Issue by ivysrono** [syncthing/syncthing-android#1802] opened 2022-07-10 09:06 UTC
### Happened

Generating key is not finished.

like https://github.com/syncthing/syncthing-android/issues/1703

### Tried

- force stop and restrart

- reinstall

### Version Information

    App Version: 1.20.3
    Syncthing Version: v1.20.3
    Android Version: Android 12.1 ( WSA  2204.40000.20.0 )

**Comment by imsodin** [comment] 2022-07-10 11:00
I am closing this as a duplicated of the already linked #1703  
Someone even already reported there that WSA is also affected since running in some virtualized env - likely to be the same root cause.

**Closed by imsodin** 2022-07-10 11:00 UTC
