### ISSUE TITLE
dynamic listening address not working after upgrading to 1.19.0.3

### ISSUE THREAD

**Issue by maxox** [syncthing/syncthing-android#1759] opened 2022-02-14 23:17 UTC
after the latest update the Android syncthing client went offline, unless I downgrade to 19.0.0 or lower versions and I check the syncthing log on version 1.19.0.3 there is nothing inside

### Version Information

    App Version: 1.19.0.3
    Syncthing Version: v1.19.0
    Android Version: Android 11

**Comment by maxox** [comment] 2022-02-14 23:31
I tried changing the listening address from "dynamic" to tcp://192.168.1.xxx:22000 now it works, so imo the dynamic address breaks after the update

**Comment by imsodin** [comment] 2022-02-15 07:46
Yes, this is known unfortunately and a duplicate of https://github.com/syncthing/syncthing-android/issues/1628  
It's a restriction imposed by Android, which is pretty hard to work around.

**Closed by imsodin** 2022-02-15 07:46 UTC
