### ISSUE TITLE
Syncthing on Android Oreo

### ISSUE THREAD

**Issue by GinoBombino** [syncthing/syncthing-android#994] opened 2017-11-21 21:05 UTC
Starting this bug regarding the "Apps Using Battery" problem on Android Oreo.

It is my understanding that their are API changes that can be adopted to get Syncthing removed from this dialog and handled better as a background application. 

Other Apps that sync data do not appear in this dialog. 
(Signal, Google Drive, WhatsApp, etc)

It should be feasible to get Syncthing shifted and alleviate its numerous problems with running in background (which I presume are all related)

**Comment by AudriusButkevicius** [comment] 2017-11-21 21:08
Perhaps other applications genuinely do not run in the background all the time like syncthing does.
You should provide example of what changes you expect to happen.

**Comment by GinoBombino** [comment] 2017-11-21 21:12
Its my understanding that newer API's exist which Android wants Apps to shift over to, and once that occurs these "annoyance" dialogs will disappear.

As for the apps listed, I can only speak to Signal, which definitely keeps a background daemon running at all times. 

This problem is unique only to a select few, often older apps. 

I am not an expert in android development, so I can't give you more specifics. 
I do know this is a solvable issue.

**Comment by GinoBombino** [comment] 2017-11-21 21:17
Here is the migration guide from Android on this issue

https://developer.android.com/about/versions/oreo/background.html

**Comment by yacoob** [comment] 2017-12-22 07:35
Even after fixing https://github.com/syncthing/syncthing-android/issues/966 the notification about "Syncthing is using battery" is still there. It's kind of worse now, as there are *two* notifications about Syncthing now - one from the app itself, and other from the operating system :|

![screenshot_20171208-082614](https://user-images.githubusercontent.com/190463/33852448-914adaa6-deb2-11e7-8555-cc2f5f41827a.png)

**Comment by Nutomic** [comment] 2017-12-26 17:52
From the link posted by @GinoBombino, this seems to be caused by the fact that we are listening for wifi/battery events. Unfortunately, that is not something we can easily change. There are some alternative APIs, but I don't think the Syncthing app would be able to work with those like it does now. It would basically require a complete rewrite of the app.

Alternatively, you might check out [Syncthing Lite](https://github.com/Nutomic/syncthing-lite) (alpha state).

**Comment by Ajedi32** [comment] 2018-04-23 15:20
So this bug is basically asking Syncthing to move over to the new JobScheduler API?

Seems like a good move, not just to get rid of the annoying notifications, but also just in general. Continuously running a foreground service just to listen to Wi-Fi and power events doesn't seem like good practice.

**Comment by AudriusButkevicius** [comment] 2018-04-23 17:11
Feel free to make a pull request addressing this.

**Comment by Catfriend1** [comment] 2018-05-07 06:32
Duplicate of 
https://github.com/syncthing/syncthing-android/issues/1048

**Closed by Catfriend1** 2018-05-07 06:32 UTC
Labels: pr-welcome
