### ISSUE TITLE
Sync does not work if Android Account Sync is disabled or Battery-Saver is active

### ISSUE THREAD

**Issue by defan21** [syncthing/syncthing-android#727] opened 2016-08-20 01:29 UTC
After upgrading to version 0.8.2 I get the following message when opening app:

Syncthing is disabled
Do you want to change your preferences?

I've tried every setting in preferences but when I hit the back arrow to return to syncthing the app just closes.

Rooted nexus 6
Android build MMB29K

**Comment by defan21** [comment] 2016-08-20 01:30
Please fix this... i just love this app!!

**Comment by licaon-kter** [comment] 2016-08-20 01:41
Do you have Wi-Fi only enabled?

**Comment by defan21** [comment] 2016-08-20 03:19
I tried every option  on and off. Rebooted.  Re-installed app.  No joy.

**Comment by defan21** [comment] 2016-08-20 03:33
The only thing i havent tried is resetting the db

**Comment by defan21** [comment] 2016-08-20 03:40
I tried it both ways.
Ive rebooted.
ive reinstalled.
The only thing i havent trief is resetting the database.


On August 19, 2016 6:41:57 PM PDT, licaon-kter <notifications@github.com> wrote:
>Do you have Wi-Fi only enabled?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing-android/issues/727#issuecomment-241170726

-- 
Sent from my Nexus 6 with K-9 Mail. Please excuse my brevity.

**Comment by defan21** [comment] 2016-08-20 03:43
The syncthing log only has;
--------- beginning of main



The android log has:
--------- beginning of main
08-19 20:41:14.282 11766 11802 D OpenGLRenderer: endAllStagingAnimators on 0xa0287a80 (RippleDrawable) with handle 0x9ae3f440
08-19 20:41:31.023 11766 11802 D OpenGLRenderer: endAllStagingAnimators on 0x9f508500 (RippleDrawable) with handle 0xaa198690
08-19 20:41:34.882 11766 11802 D OpenGLRenderer: endAllStagingAnimators on 0x9ff43500 (RippleDrawable) with handle 0x9f316f70
08-19 20:41:38.239 11766 11766 I ListPopupWindow: Could not find method setEpicenterBounds(Rect) on PopupWindow. Oh well.
08-19 20:41:38.330 11766 11802 D OpenGLRenderer: endAllStagingAnimators on 0x9ff46600 (ListView) with handle 0x9ae3f490


Hope this helps

On August 19, 2016 6:41:57 PM PDT, licaon-kter <notifications@github.com> wrote:
>Do you have Wi-Fi only enabled?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing-android/issues/727#issuecomment-241170726

-- 
Sent from my Nexus 6 with K-9 Mail. Please excuse my brevity.

**Comment by frotutz** [comment] 2016-08-20 04:40
Stupid update.
Says "respect battery saving mode and global sync setting"  which means syncthing is unconditionally disabled while 'auto-sync data' under the device settings "accounts" is disabled. 

After telling you it is disabled it offers to take you to the syncthing settings where there is no option to make it work.  Why should it take notice of a global sync setting under accounts when syncthing has nothing at all to do with accounts in there?  I would rather it didn't and it should be optional if some people want it to. 

Also whenever I manually exit this version I get a window telling me "Unfortunately Syncthing has stopped" - well duh?

**Comment by defan21** [comment] 2016-08-20 04:44
It never told me anything about the global sync setting but after turning global sync on it looks like its working.  Wish i hadnt reinstalled, now i have to set up all of my sync folders again:(

On August 19, 2016 9:40:34 PM PDT, frotutz <notifications@github.com> wrote:
>Stupid update.
>Says "respect battery saving mode and global sync setting"  which means
>syncthing is unconditionally disabled while 'auto-sync data' under the
>device settings "accounts" is disabled. 
>
>After telling you it is disabled it offers to take you to the syncthing
>settings where there is no option to make it work.  Why should it take
>notice of a global sync setting under accounts when syncthing has
>nothing at all to do with accounts in there?  I would rather it didn't
>and it should be optional if some people want it to. 
>
>Also whenever I manually exit this version I get a window telling me
>"Unfortunately Syncthing has stopped" - well duh? 
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing-android/issues/727#issuecomment-241179044

-- 
Sent from my Nexus 6 with K-9 Mail. Please excuse my brevity.

**Comment by gaydenko** [comment] 2016-08-20 05:29
I also get a dialog forcing to go to preferences. Syncing options are disabled in settings. Also I have found at the settings list end there isn't version for syncthing. Rather for syncthing-android only. Is syncthing packed for Android 4.4.2 at all? :)

**Comment by licaon-kter** [comment] 2016-08-20 08:04
@defan21: That's why you have 'Export' and 'Import' options, so you don't setup it everytime.

**Comment by ronanM** [comment] 2016-08-20 10:24
@gaydenko same problem on Android 4.2.1. No syncthing version displayed. I've try uninstall/reinstall/reset database. Nothing works :-(

**Comment by gaydenko** [comment] 2016-08-20 10:54
To workaround I have downloaded 0.8.1 from F-Droid

https://f-droid.org/repository/browse/?fdid=com.nutomic.syncthingandroid

, saved prefs, uninstalled current version, installed downloaded apk and resotred prefs.

**Comment by Nutomic** [comment] 2016-08-20 11:18
Yes, this is probably because you have sync disabled in account settings, which was requested #588. Do you think we should get rid of this behaviour, or add a setting for it? I always have the sync enabled, so I don't really know what's the best option.

**Comment by gaydenko** [comment] 2016-08-20 11:22
Frankly speaking, I guess it is crazy idea to try to find correlation between accounts syncing and syncthing :) The last one is definitely exists in it's own league. Of course, to my taste.

**Comment by defan21** [comment] 2016-08-20 12:12
Can the global sync but keep the 'sync on wifi only'.

On August 20, 2016 4:22:36 AM PDT, Andrew Gaydenko <notifications@github.com> wrote:
>Frankly speaking, I guess it is crazy idea to try to find correlation
>between accounts syncing and syncthing :) The last one is definitely
>exists in it's own league. Of course, to my taste.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/syncthing/syncthing-android/issues/727#issuecomment-241194128

-- 
Sent from my Nexus 6 with K-9 Mail. Please excuse my brevity.

**Comment by frotutz** [comment] 2016-08-20 15:04
I have no desire to sync any of my information through google ever - one of the reasons why I run syncthing on a private server. 

The sync system on android is designed with google's typical zero respect for personal privacy. You can't change sync options for particular accounts while auto-sync is off and when you turn it on it starts syncing immediately. New accounts also start syncing immediately. 

If syncthing is going to take notice of the accounts auto-sync setting it should definitely be controlled by a syncthing setting.

IMO the current implementation is broken anyway. If you turn off auto-sync syncthing exits and I presume the same on battery saver. If you turn on auto-sync again or charge the battery you are not going to 'syncthing' anything till you start the app again. 

In both cases syncthing should not quit or refuse to start it should just be as dormant as possible and come back to life when you enable auto-sync or leave battery save mode (and both should still be optional). Doesn't it already do something like that for the while charging and on WiFi options?

**Comment by Nutomic** [comment] 2016-08-20 15:46
If you enable sync again, Syncthing will automatically be started again. No need to do anything. Same for battery saver.

I just added this feature because it was requested, I don't care about this myself. I see that you all don't want it, so I will remove it for the next release (some time next week).

**Comment by AudriusButkevicius** [comment] 2016-08-20 15:51
Why not add a checkboxes, respect battery saver, respect android sync settings, and actually add a message explaining why syncthing is disabled?

**Comment by frotutz** [comment] 2016-08-20 17:57
"If you enable sync again, Syncthing will automatically be started again. No need to do anything. Same for battery saver."

That is still broken. If I turn off auto-sync syncthing is still actually running? I can't tell if it is running and I can't stop it if it is and I can't start it so it will run when I enable auto-sync either. 

Conceptually the whole thing is messed up. 

Maybe syncthing isn't actually running and there is some kind of start/stop hook from the auto-sync setting, still broken because that hook is still conditional (on syncthing being running when auto-sync was disabled?). When I turn on auto-sync I can't tell if syncthing is going to start syncing or not and there is no way I can prevent it from starting if that isn't what I wanted. 

I don't know what to suggest is this a conflict of ideas between syncthing being an  application you run while you need it and a system service which needs settings to enable/disable it?

**Comment by gaydenko** [comment] 2016-08-20 18:08
> I see that you all don't want it, so I will remove it for the next release (some time next week). 

Thanks!

**Comment by Nutomic** [comment] 2016-08-20 18:58
@AudriusButkevicius I don't really like to add so many options, but that's definitely another option. As for the explanation message, I'm not sure where that should go. With your PR merged, we can have the GUI even when Syncthing is paused, so a dialog doesn't make sense. Maybe in the notification? But that's not obvious, and the notification can be disabled.

@frotutz That's true. I'm not sure what the expected behaviour is there (also for battery saver). Just stop Syncthing until it is manually started again?

**Comment by capi** [comment] 2016-08-21 11:15
According to Android docs, expected behavior would be that an Android application works as expected while it's activity is in foreground (with as much power-saving as possible while in power-saver & battery, e.g. reduced frame-rate, reduced update-rate, etc.). While activity is in background, it should stop any background network activity while in both, power-saver and sync-disabled.

Adding this correctly and in a way most people use it for now, we'd need to add two things in my opinion:

1. A possibility that Syncthing runs while the activity is in foregorund (and stops as soon as you switch away). This would also get rid of the "Syncthing is disabled" message. But it's tricky regarding using mobile-data when people have "WiFi only" enabled. I think the new "pause/unpause" feature in the upcoming Syncthing release will provide new possibilities here.

2. Settings which let user configure their expected behavior if they have "always run in background" enabled and if they disable global sync preference.

Since I agree with you that this starts to get out-of hands in regards of settings quite fast, I personally think that the previous behavior was sensible and closer to what most users expect of Syncthing (i.e. always run, depending on the settings inside the application and not based on the global settings of Android). Syncthing is not a "classic" Android application, that polls some data / messages from a centralizes server, but it's a file synchronization _service_.

**Comment by AudriusButkevicius** [comment] 2016-08-21 11:37
@nutomic well you do say "syncthing is disabled" yet don't explain why, no? Why not add a reason explaining why its disabled?

**Comment by AudriusButkevicius** [comment] 2016-08-21 11:38
@nutomic you also don't need my PR to do what you are talking about, as you can already pause all devices which is equivalent of syncthing being disabled I guess.

**Comment by UserFriendlyyy** [comment] 2016-08-21 14:42
I had this same problem but it had nothing to do with account sync.  What finally fixed it was taking it off battery saver mode,, going into settings and unchecking only sync while charging. which un-grey's "syncthing options' and then I toggled anonymous usage (probably not important)  and  it restarted and worked.

**Comment by Nutomic** [comment] 2016-08-21 14:55
@capi That makes sense. Pausing Syncthing instead of stopping it is definitely something we should do. Then we can just enable sync according to settings, and the GUI is always available. But it will be a pretty big change. As for 2, I'm think more options here only get confusing, especially when users have to figure out how they work together. So for now I would just remove the global sync thing.

@AudriusButkevicius That makes sense, only problem is that we need to change everything again when we use pause instead of stopping Syncthing. Does the current pause option also let you add new devices as paused?

**Comment by AudriusButkevicius** [comment] 2016-08-21 15:00
The pause option just kills the connection and refuses connections from that device, and stops dialing, so yes.

**Comment by AudriusButkevicius** [comment] 2016-08-21 15:01
I think you still need to indicate why stuff is paused though, if you advertisef that now, we wouldn't even have this issue.

**Comment by Nutomic** [comment] 2016-08-21 16:28
Agreed. I was thinking of showing the status (syncing/paused) in the notification. Only problem is that the notification can be disabled, and that people might not see it.

**Comment by AudriusButkevicius** [comment] 2016-08-21 16:40
You have the status bar in the side slide thing. Or maybe you can have new element above the list for devices folders which shows up only in the cases where it's disabled/paused.
Or if you stay with the current approach of killing syncthing, then you just add the status in where it says It's disabled.

**Comment by lpalgarvio** [comment] 2016-08-21 23:51
what are you thinking??? not everyone wants a always running background app eating your CPU and flash memory. this is a major letdown... you need to give control to users and let them decide if they want syncthing to behave like a daemon or like a normal application without depending on sync options...

**Comment by licaon-kter** [comment] 2016-08-21 23:54
@lpalgarvio It's not doing anything most of the time anyway, only syncing files if needed.

**Comment by lpalgarvio** [comment] 2016-08-22 00:06
@licaon-kter how do you measure "anything"?
Have you considered people who wish to sync the entire sdcard and internal memory (media) for backup purposes? Anything that Facebook or any other app farts to the normal user accessible storage your app will crawl it!! And double the IO. That isnt anything!

FYI, anything isnt the resources it takes on idle either: It's consuming 65MB of RAM

Plus it takes up to 5min to start (because of the extensive file coverage) and be completely operational on my device. Like many people, i don't want to wait 10min to start using my phone. Having control over your device is CRUCIAL.

**Comment by licaon-kter** [comment] 2016-08-22 00:23
The problem here is that there is no app control over syncing, while an app with a device account entry has 2:
* global sync
* per account option to disable

Regarding app usage, yes it varies depending on device, but when you want backup you'll swallow the RAM and I/O penalty anyway.

What device and what sync data size takes 15 min to enter idle state?

**Comment by lpalgarvio** [comment] 2016-08-22 00:35
@licaon-kter
What device and what sync data size takes 15 min to enter idle state?

Galaxy S3 Mini - http://www.gsmarena.com/samsung_i8190_galaxy_s_iii_mini-5033.php
Dual Core 1GHz, ARMv7, with 1 GB of RAM.
About 2000 files in a periodically (secondary) device used with almost no social apps, but many tools, browser, password manager, etc. Total about 400MB of data, including caches, but also contains the TWRP recovery backups for the entire storage which i keep in sync, and that consumes 8GB in about 6 files.

The longer than usual launch is likely due to the forced rehashing of all files with the update to 0.14.4. Same happened last time about 1-2months ago with another version. My computers have finished rehashing and synchronizing, but none of the phones did so far.

**Comment by capi** [comment] 2016-08-22 06:37
@lpalgarvio If you do not change the defaults, "Always run in background" is disabled, so it is entirely under your control when you start it up and when you shut it down.

**Comment by lpalgarvio** [comment] 2016-08-22 21:49
@capi @licaon-kter I can confirm now it's not currently autostarting on my Android 4.4.x devices with foreground option and android sync enabled.

**Comment by acornsirup** [comment] 2016-08-23 12:45
I was also confused by Syncthing being disabled while Sync is off as there is no message telling you what's the culprit. But now I really love the new feature!

My scenario: Always on in background, only sync in certain WiFis. Now I can simply turn Android Sync off and Syncthing stops consuming battery. I really like this.

But still, another toggle liḱe "Sync only with charger" and "Sync only with WiFi" would be very handy for the people who don't like this situation. E.g. "Sync only when Android's automatic synchronisation is enabled" (like in K-9 Mail). 
Plus it's accessible from the "Syncthing is disabled. Do you want to change your preferences?" prompt.

Thanks for all your efforts!

**Comment by Nutomic** [comment] 2016-08-24 20:52
New version is out, with the link to account sync disabled. I'm closing this issue in favor of #729.

**Closed by Nutomic** 2016-08-24 20:52 UTC
Labels: question
