### ISSUE TITLE
Syncthing doesn't work on Sd-Card

### ISSUE THREAD

**Issue by bjo81** [syncthing/syncthing-android#87] opened 2014-08-14 12:20 UTC
When syncthing has been moved to the SD-card via the App2SD-function, it crashes with errorcode 126 when you try to run it.

The device is a Sony Xperia Neo V running CM11, the app is version 0.4.6.

Log:
http://paste.m0u.de/paste/G2Fzx1yB#

**Comment by kowach** [comment] 2015-07-12 11:44
I have the same problem, solved by moving back form SD card to main storage.

	E/SyncthingRunnable( 4423): Failed to execute syncthing binary or read output
	E/SyncthingRunnable( 4423): java.io.IOException: Error running exec(). Command: [/data/data/com.nutomic.syncthingandroid/lib/libsyncthing.so, -generate, /data/data/com.nutomic.syncthingandroid/files] Working Directory: null Environment: [ANDROID_SOCKET_zygote=9,SECONDARY_STORAGE=/storage/sdcard1, ANDROID_STORAGE=/storage, STNOUPGRADE=1, ANDROID_BOOTLOGO=1,EXTERNAL_STORAGE=/storage/sdcard0, ANDROID_ASSETS=/system/app...
	...
	E/SyncthingRunnable( 4423): Caused by: java.io.IOException: Permission denied
	E/SyncthingRunnable( 4423):     at java.lang.ProcessManager.exec(Native Method)
	E/SyncthingRunnable( 4423):     at java.lang.ProcessManager.exec(ProcessManager.java:209)

Running Oppo R819, Android 4.2.1

**Comment by gerroon** [comment] 2015-10-06 23:55
It would be nice if this is allowed because my device has limited data storage and ST is taking abit of space ;(

**Comment by trueschool** [comment] 2016-08-30 15:16
Yes, please address this! I have SyncThing installed in the phone's storage, but when I try to set a directory on my SD card as the sync location, I get an error saying that my phone doesn't allow it?!? (Galaxy S7)

I want to use SyncThing for syncing large files to my phone, so being able to use the SD card is pretty essential to my use case. 
Thanks, and keep up the great work!
Ted

**Comment by Nutomic** [comment] 2016-08-30 15:31
@trueschool Wrong issue, check #29.

**Comment by SergeyDjam** [comment] 2017-02-28 10:40
Not for long. Through short time all resources and the application come to an end doesn't work any more

**Comment by Nutomic** [comment] 2018-01-19 08:21
@ckotte Yes, you just have to create the `.stfolder` directory manually.

**Comment by Catfriend1** [comment] 2018-04-22 21:01
Closed as a duplicate of 
https://github.com/syncthing/syncthing-android/issues/29#issuecomment-383411994

**Closed by Catfriend1** 2018-04-22 21:01 UTC
Labels: bug
