### ISSUE TITLE
Encrypted folders make the app crash

### ISSUE THREAD

**Issue by robertolopardo** [syncthing/syncthing-android#1914] opened 2023-06-08 12:49 UTC
When an encrypted, not trusted, folder is added and the password is not set, the whole app crashes without giving feedback of what's going on.

A workaround is to accept the shared folder from web GUI to setup the password.

**Comment by imsodin** [comment] 2023-06-08 16:55
Duplicate of https://github.com/syncthing/syncthing-android/issues/1650

**Closed as completed by imsodin** 2023-06-08 16:55 UTC
