### ISSUE TITLE
0.5.20: Can't add new devices nor folders on main page, only through "Web GUI"

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#242] opened 2015-03-15 02:49 UTC
`ADD DEVICE` or `ADD FOLDER` on the main page allows me to add all the info but doesn't actually add neither device nor folder. `Settings -> Web GUI` allows me to add both. Strangely, after adding a new device through `Web GUI`, it still doesn't show on the main page, but a new folder added through `Web GUI` is shown on the main page afterwards.

PS: I'm running Android 4.4.4 on a Motorola E XT1022

**Comment by Nutomic** [comment] 2015-03-15 09:48
Duplicate of #239.

**Closed by Nutomic** 2015-03-15 09:48 UTC
