### ISSUE TITLE
0.5.20: "Device Name" in "Settings -> Syncthing Options" not being saved

### ISSUE THREAD

**Issue by marcelpaulo** [syncthing/syncthing-android#241] opened 2015-03-15 02:39 UTC
Any changes to `Device Name` in `Settings -> Syncthing Options` are lost when leaving the `Settings` page.

If changed on `Settings -> Web GUI`, it is preserved. However, it is still not shown on `Settings -> Syncthing Options`.

PS: I'm running Android 4.4.4 on a Motorola E XT1022

**Comment by Nutomic** [comment] 2015-03-15 09:46
Duplicate of #239.

**Closed by Nutomic** 2015-03-15 09:46 UTC
