### ISSUE TITLE
AC Power status is not detected

### ISSUE THREAD

**Issue by sbobbo** [syncthing/syncthing-android#1574] opened 2020-11-09 16:56 UTC
The "Run when device is powered by" setting does not work right for me. If I have it set to "AC Power", syncthing simply never runs, regardless of whether I am plugged in and charging or not. Swapping to either "AC and Battery Power" and "Battery Power" allows Syncthing to run.

I would like to be able to set it to only run when the phone is charging because Syncthing can burn my battery down fairly quickly.

### Version Information

    App Version: 1.10.0
    Syncthing Version: v1.10.0
    Android Version: Android 10, One UI 2.1 on Samsung Note 9

**Comment by itskando** [comment] 2020-11-10 19:54
+1

In AC only mode, plugged in and no said couldn't operate on battery.

Worked later for some reason.
In AC only mode, unplugged and kept running.

**Comment by itskando** [comment] 2020-11-10 20:04
Updated original post.

**Comment by boppreh** [comment] 2021-09-08 19:59
Same problem here, also on a One Plus device when dash-charging, but it's also not 100% reproducible.

**Comment by imsodin** [comment] 2022-03-26 15:13
Duplicate of https://github.com/syncthing/syncthing-android/issues/1595

**Closed by imsodin** 2022-03-26 15:13 UTC
