### ISSUE TITLE
Enable access to SD card?

### ISSUE THREAD

**Issue by mikp** [syncthing/syncthing-android#548] opened 2016-01-26 17:30 UTC
Hi, 

just tried syncthing and syncthing-android and I really like it. Sadly, it is not possible to create shared folders on the SD card due to missing write permission in current versions of android (using 6.0 here). However, other app developers were obviously able to fix this (e.g. FX File Explorer). From what I found out, it is possible by using ACTION_OPEN_DOCUMENT_TREE. 
I found a bunch of questions, and more importantly, answers to the topic here: https://stackoverflow.com/questions/26744842/how-to-use-the-new-sd-card-access-api-presented-for-lollipop
Finally, the android documentation related to the topicthe topic: https://developer.android.com/guide/topics/providers/document-provider.html

My questions are: did you look into this before? If yes, sorry, then I must have missed it. If not, would it be work a try? I myself never developed for android, but what it looks like to me it should not be too much work to implement this. 

For now, thanks! If anything is unclear, please just tell me.

**Comment by Nutomic** [comment] 2016-01-26 17:56
Duplicate of #29. Tl;dr Golang doesn't support document provider yet. There's a link to the Golang ticket in that issue, that would probably be a good place to start.

**Closed** 2016-01-26 17:56 UTC
Labels: duplicate

**Comment by mikp** [comment] 2016-01-26 17:59
Ok sorry, obviously missed that.

**Comment by Nutomic** [comment] 2016-01-27 00:18
Forgot to add: if you want to work on this, feel free to ask any questions you have on the forum or on irc ;)
