### ISSUE TITLE
synthing isn't well terminated on android -ZenUI

### ISSUE THREAD

**Issue by joe147** [syncthing/syncthing-android#887] opened 2017-05-11 18:47 UTC
I have installed syncthing on Zenpad (ZenUI launcher on )android)  and it works, but when I exit the programm regulary synything doesn't terminate right. When I use the quit button on the side menue, it seems to me that a new child process in background is starting.
Other connected devices (for example PC-client) still shows online status until zenpad device hibernates and background processes are shut down by the system. 
When I then turn on Zenpad device, there is still the message 'synthing is running' altough it isn't running anymore (even not in background - processes and child processes has been killed).This malfunction do make me very unhappy , because I like this piece of software very much and I would like to run it also on my Zenpad. But without the problem solved, its not useable for me. Has someone any similar experienes or an idea how to fix this ?
p.s. sorry for bad englisch (AUSTRIA)
Thanks for answers !! regards, joe
Version Information

    Syncthin-Android Version: 0.9.9
    Syncthing Version: v0.14.26
    Android Version: Android 6.0.1

**Comment by Nutomic** [comment] 2017-05-12 03:42
Do you have any logs?

**Comment by joe147** [comment] 2017-05-12 08:03
Yes - attachement. Thanks !
[syncthinglog.txt](https://github.com/syncthing/syncthing-android/files/995437/syncthinglog.txt)

**Comment by joe147** [comment] 2017-05-12 08:06
last line: Cannot open database.... is confusing. Synthing process  not killed/closed  by using quit button in side menu or another child process created ??

**Comment by Nutomic** [comment] 2017-05-15 01:18
Well for some reason, there is another Syncthing instance already running, so it cant start the new instance. But I dont know why that is happening :/

**Comment by joe147** [comment] 2017-05-15 06:04
Thanks for answering ! Its strange- it works very well on my samsung devices. But the same android version. Of course manufactors have their own 'overhead' on android (Samsung: TouchWiz ; Asus: ZenUi,..) but I did try all settings and it do work on samsung devices and do not work on Asus android devices.  Nevertheless thank you very much for this great piece of software. Would be great if this problem can be fixed too. regards

**Comment by Riwaha** [comment] 2018-03-04 17:17
It seems to be caused by /system/bin/grep not having permisions for the user. It's caused by [this line](https://github.com/syncthing/syncthing-android/blob/master/app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java#L187). It never actually shutsdown Syncthing.

It could be fixed if grep is packaged with syncthing-android, ionice(the following line) might also not execute.

**Comment by Riwaha** [comment] 2018-03-04 17:19
It is caused by /system/bin/grep not having the correct permissions. [This line](https://github.com/syncthing/syncthing-android/blob/master/app/src/main/java/com/nutomic/syncthingandroid/service/SyncthingRunnable.java#L230) is where it is happening. It never gets the process id, and in turn can't kill it.

It could be fixed by packaging grep with syncthing-android perhaps.

**Comment by Joe7new** [comment] 2018-03-12 21:51
Thanks for answering! I hope it can be fixed.. regards

**Comment by Catfriend1** [comment] 2018-04-22 13:13
@joe147  is this fixed in the most recent version 0.10.8?

**Comment by Catfriend1** [comment] 2018-05-10 20:41
@joe147 is this fixed in the most recent version 0.10.10?

**Comment by Catfriend1** [comment] 2018-05-26 12:04
@Riwaha 
Can you please give a hint how packaging "grep" with syncthing-android can be achieved?

**Comment by AudriusButkevicius** [comment] 2018-05-26 13:04
We can probably just read all /proc/*/exe to find syncthing, this way we won't need grep nor ps. I don't think we should package grep. We could also do what grep does by just parsing output of ps.

**Comment by Catfriend1** [comment] 2018-05-27 14:36
@AudriusButkevicius Sounds good :)
@joe147 @Joe7new  Are you still around for testing debug builds? If I go on this, I need someone with ZenUI to test it.

**Comment by Catfriend1** [comment] 2018-05-27 15:04
Note for me:
cat /proc/*/status | egrep "^Name:\s+.*$|^Pid:\s+.*$"
(egrep must be done in code ...)

**Closed** 2018-05-27 19:28 UTC
Labels: bug, pr-welcome
