### ISSUE TITLE
"Override Changes" button MUST WARN PEOPLE WHAT IT DOES.

### ISSUE THREAD

**Issue by ZacharyACoon** [syncthing/syncthing-android#2062] opened 2024-02-23 02:48 UTC
The "Override Changes" button in android provides zero information about what it does. 

Override WHAT?
Override WHERE?
What files are being changed how?

This is EXTREMELY dangerous and just nearly cost my partner years of baby photos, I'm shaking.

**Comment by tomasz1986** [comment] 2024-02-23 02:55
Duplicate of https://github.com/syncthing/syncthing-android/issues/1769.

We are aware that this can pose a serious usability issue, as a single miss click can lead to file deletion on the other side, but the app is in maintenance mode, so unless a volunteer steps in and improves the experience, the current state likely won't change in the near future…

There is a confirmation dialog in the Web GUI, but not the app itself.

**Closed by tomasz1986** 2024-02-23 02:55 UTC
