### ISSUE TITLE
Sync Only Chosen Folders via Mobile Connection?

### ISSUE THREAD

**Issue by thumos333** [syncthing/syncthing-android#1653] opened 2021-05-13 16:07 UTC
Hi,

I think an important feature for the Android app would be possibility to sync only selected folders via a mobile connection. Say, a folder with photos should only be synced on wifi, while a notes folder can be synced on mobile network.

Thank you.

**Comment by AudriusButkevicius** [comment] 2021-05-13 16:38
Duplicate of #511

**Closed by AudriusButkevicius** 2021-05-13 16:38 UTC
