### ISSUE TITLE
Wifi only condition doesn't seem to be working.

### ISSUE THREAD

**Issue by dimdam** [syncthing/syncthing-android#975] opened 2017-10-22 12:40 UTC
After last updates syncthing on Android doesn't seem to comply with WiFi only condition. It stays on with WiFi on/off ,i stays on with 4G and even when  the device is offline. This started about 2 weeks ago if i remember correctly.

i tried every setting , i even formatted my device and set up as new but nothing changed.

### Version Information

    App Version: 0.9.17
    Syncthing Version: v0.14.39
    Android Version: Android 7.1.2 RESURRECTION REMIX 5.8.5

**Comment by Nutomic** [comment] 2017-10-23 14:16
There was a change recently, if there is no network connection at all (eg flight mode), Syncthing will still run.

As for wifi only, does it work correctly if you (dis)connect wifi while the app is open? Does it help if you enable "run in foreground" in experimental settings?

**Comment by dimdam** [comment] 2017-10-23 14:42
If I enable the "run in the foreground" sometimes it works sometimes it doesn't. Syncthing running  while switching on/off the WiFi toggle.

**Comment by jonathanturcotte** [comment] 2017-11-09 04:02
I'm also getting this, 0.10-beta2 from the play store, on Android 7.1.1.

Disconnecting and reconnecting wifi while the app is open did not help.

**Comment by Nutomic** [comment] 2017-11-13 02:39
@jonathanturcotte Can you check if the final 0.10.0 release fixes the problem?

**Comment by dimdam** [comment] 2017-11-13 16:13
@Nutomic in my case ,nothing changed.

**Comment by Nutomic** [comment] 2017-11-13 16:15
Please post logs then.

**Comment by dimdam** [comment] 2017-11-13 16:35
@Nutomic There you go: https://pastebin.com/iq3KPdFd

**Comment by jonathanturcotte** [comment] 2017-11-14 06:11
Updated, still happening on the final 0.10. The syncthing log is empty, but here is the android log: https://pastebin.com/f4NxqPN7

**Comment by dimdam** [comment] 2017-11-14 10:46
Why is this issue marked as closed?

**Comment by jonathanturcotte** [comment] 2017-11-19 21:49
I just got an update for my OP3 this morning, and I can confirm that this is still happening on android 8.0

**Comment by MartinX3** [comment] 2018-04-11 20:13
Still happening
(Changelog said it is fixed in 8.1 but it isn't.

**Comment by AudriusButkevicius** [comment] 2018-04-11 21:04
The changelog talks about an issue that fixed "run on X network" not working, but you might have to toggle the option to retrigger additional permission requests.

**Comment by capi** [comment] 2018-04-12 06:10
I will have a look that we also request the permission if the setting is already enabled and the permission has been invoked in the meantime. @AudriusButkevicius it seems that your request for that in the PR was indeed needed.

**Comment by MartinX3** [comment] 2018-04-16 06:17
@AudriusButkevicius  I retriggered the option, but it always tells me, that syncthing is deactivated.

The only thing that got fixed was the major bug, that it never works without any run condition.
That means, that if I deactivate the wifi run condition, it works now like a charm on Android 8.1/Lineage 15.1.

**Comment by AudriusButkevicius** [comment] 2018-04-16 06:32
Did you grant syncthing all permissions it asked for?

**Comment by MartinX3** [comment] 2018-04-16 06:40
There are only storage and location, which are both allowed.

**Comment by AudriusButkevicius** [comment] 2018-04-16 08:06
So what's the issue here, syncthing always things you are connected to wifi even if you are not?

**Comment by MartinX3** [comment] 2018-04-16 08:08
I open the APP without any run condition.
It syncys.

Then I activate the wifi run condition.
Then I mark my wifi networks.
Then I press the back button and be in the main interface.
Then I press the back button again and be in my Android launcher.
Then I click in the syncthing APP icon to open the APP.
Then I See the "synching is deactivated" message.

**Comment by MartinX3** [comment] 2018-04-16 08:24
Damn. :(
I think the app need more rights in the manifest.
I gave the app every permission grant.
(Storage & Location)

**Comment by AudriusButkevicius** [comment] 2018-04-16 08:28
Well the app asks for the permission as you open the wifi selection dialog:

https://github.com/syncthing/syncthing-android/commit/7ab45a9d889b068e3dd848abb0836290cd9f3816#diff-c30baf50c8c1207771b2fbdaf2f5a5ceR79

**Comment by MartinX3** [comment] 2018-04-16 08:41
But the app list the wlan SSID's in the selection dialogue.
I think it only doesn't get the SSID of the current connected WiFi.

Does this app asks  for
ACCESS_COARSE_LOCATION
And
ACCESS_FINE_LOCATION
permissions?

**Comment by AudriusButkevicius** [comment] 2018-04-16 08:46
Listing does not require the permission as far as I recall, getting SSID of current connection does.

**Comment by capi** [comment] 2018-04-16 09:01
Location permission is required to get names of WiFi that are in range (since this information can be used to look up various Geo-Databases). It is not required to list the known networks (since there is no info if they are in range or not).

I am running the current version on LinageOS 15.1 on a OnePlus2. There this works. _Maybe_ other ROMs need `ACCESS_FINE_LOCATION` as well? At the moment we only list `ACCESS_COARSE_LOCATION` in the manifest, since the discussions in the Google issue tracker indicated this and it worked on my device.

**Comment by vsespb** [comment] 2018-04-16 18:38
When I turned on "only wifi" feaure, switched wifi off, then on again. Syncthing became locked. There was the message "Syncthing is disabled" and "setting" or "exit" choice. I changed setting to disable the feature, but this did not help. Only phone reboot helped. Syncthing was unusable and there was no chance to use it except reboot.

**Comment by Catfriend1** [comment] 2018-04-21 18:16
@vsespb force closing the app from settings>apps also should help if you are stuck. I cannot reproduce this problem being on Android 7.1.2. so I consider it an Android 8.x issue.

**Comment by vsespb** [comment] 2018-04-22 07:57
I have android 6. Exist menu was not available - I think "run in background" was enabled, but turning "run in background" off did not help to get to the menu.
Issue not always reproducible.

**Comment by Catfriend1** [comment] 2018-04-22 08:54
@vsespb correct, if it is set to run in background exit is hidden from the syncthing apps menu. But you should have a chance to exit it using android settings and so on.

**Comment by vsespb** [comment] 2018-04-22 09:08
ah, android app settings. right.

**Comment by Catfriend1** [comment] 2018-06-02 19:48
@vsespb @MartinX3 @jonathanturcotte @dimdam @klement 
Hi together,
Could you please give some feedback on the following debug builds if any of them solves your problem with the "all wifi allowed" but syncthing is disabled or syncthing getting started at the wrong time problem?
build A) https://build.syncthing.net/repository/download/SyncthingAndroid_Build/21858:id/debug/app-debug.apk
build B) https://drive.google.com/file/d/1PPUJ7fFb8tMIBynBU3E6V4X_IVH2EYUe/view?usp=sharing
Please backup syncthing configuration (via app settings > backup > export) and any important files first!
I need your help trying out different builds because I suspect it to be an android 8+ issue and I don't have it myself. On android 7.1.2, I encountered another bug related to run conditions.
Thanks for your feedback on this.

**Comment by MartinX3** [comment] 2018-06-02 20:59
Sorry, my device got a water damage (Nexus 6 with Lineage 15.1).
I own now a xperia with Android 8.0 (Zero), and I don't see this bug on this device. :(

**Comment by jonathanturcotte** [comment] 2018-06-03 17:49
Turns out I'm no longer having this issue - it looks like both the run conditions (charging/wifi) work normally now. No idea when or what caused it to resolve itself. My OP3 is still on android 8.0.0, but I have had a couple of updates to oxygen os since. Syncthing android is now on 0.10.10.

**Comment by Catfriend1** [comment] 2018-06-05 12:05
I think we can close this as the original problem got solved. There is still a UI glitch we'll currently keep track of in issue #1126

**Closed by Catfriend1** 2018-06-05 12:05 UTC
Labels: bug
