### ISSUE TITLE
v. 0.7.12 update - disconnected

### ISSUE THREAD

**Issue by tguser** [syncthing/syncthing-android#593] opened 2016-03-24 23:02 UTC
After latest update on Android, v0.7.12, my 2 android clients (stock Marshmallow) cannot find other nodes.
Global discovery is 0/6.
Syncthing log is empty, there is only:
--------- beginning of main

**Comment by kvj** [comment] 2016-03-25 01:51
Same for me:

Android: 0.7.12
Binary: 0.12.21

Stopped connecting to server both 0.12.20 and 0.12.21 (upgraded, for testing)

There is one possibly relevant message in log output:
W SyncthingNativeCode: ionice: exec 12573: Permission denied

**Comment by kvj** [comment] 2016-03-25 02:29
Well, in my case there is a name resolving issue. Host names are not resolved anymore. Switching to ip address resolved it. 

Probably because of fce35f15016ae315fa6a68bb0dc078efaea147e5 ?

**Comment by AudriusButkevicius** [comment] 2016-03-25 02:40
Yeah, but CGO was crashing for a lot of other people.

**Comment by kvj** [comment] 2016-03-25 06:06
"What's new" section on Play Store has no mention about this degradation... :(

Global Discovery also stopped working, right?

**Comment by tguser** [comment] 2016-03-25 07:05
As for now my client is useless, I can't sync data because of global discovery with 0 server available. 
Will we receive a new update? (Maybe a rollback of some code?)
TY

**Comment by Nutomic** [comment] 2016-03-25 20:43
What devices are you using? I tested DNS on my LG G4running Marshmallow and it worked (I think @Zillode also tested it).

**Comment by tguser** [comment] 2016-03-25 21:20
I have a Nexus 5x, stock android with march update.
It worked until latest syncthing update, after that It stopped to find global discovery servers.
I tried to reinstall but it didn't worked.
Same behaviour in wifi and mobile data.
How do I test DNS?

**Comment by Nutomic** [comment] 2016-03-25 21:46
Okay to explain this issue a bit further:

Until the last version (0.7.10), we used cgo to compile Syncthing, because it supports DNS on Android. However, many people were getting crashes with that version (#518 and other issues). To help them, we switched back to the standard Go compiler now. As I said, DNS also works with that compiler on my device, but apparently it fails on some devices. To see if DNS works, check the number of announce servers (should be at least 5/8), or try to connect to a device by address.

Of course we could switch back to the cgo compiler, but I think it's better to have failing DNS for some people, than to have instant crashes for others. However I don't know how many people are affected by each of these issues.

So both problems considered, I think we should keep the standard Go compiler, and report these DNS failures to the golang project (as they are clearly bugs). As a workaround, you can enter the IP of your server directly, instead of the domain. You'll also have to replace the announce and relay server addresses with their respective IPs. Alternatively, we can do the IP substitution in the code if many people are affected (this is what we did until a few months ago, before we had working DNS).

**Comment by tguser** [comment] 2016-03-25 21:58
Thank you very very much.
I confirm that 1) re-enabling local discovery made Android client to recognize 2of8 discosrv and 2) changing from dynamic to ip address into the remote server details made Android client to restart synchronizing.

Thank you again!

**Comment by wweich** [comment] 2016-03-25 22:27
I can confirm this DNS problem on my Moto X Style (Android 6.0, Feb '16 Security Update, Kernel 3.10.84) and my Nexus 5 (Android 6.0.1, Feb '16 security update + Mar '16 security update, Kernel 3.4.0).

---

Until this issue is resolved, you can get global discovery working again, by replacing the `default` in the field for the global discovery servers with this value:
```
https://194.126.249.5/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA,https://45.55.230.38/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC,https://128.199.95.124/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
```
To get IPv6 discovery working, you will also have to add those:
```
https://[2001:470:28:4d6::5]/?id=SR7AARM-TCBUZ5O-VFAXY4D-CECGSDE-3Q6IZ4G-XG7AH75-OBIXJQV-QJ6NLQA,https://[2604:a880:800:10::182:a001]/?id=DVU36WY-H3LVZHW-E6LLFRE-YAFN5EL-HILWRYP-OC2M47J-Z4PE62Y-ADIBDQC,https://[2400:6180:0:d0::d9:d001]/?id=VK6HNJ3-VVMM66S-HRVWSCR-IXEHL2H-U4AQ4MW-UCPQBWX-J2L2UBK-NVZRDQZ
```
Unfortunately the field is to short to enter all 6 servers, but only 4.

**Comment by lkwg82** [comment] 2016-03-25 22:35
This would be nice, if this is done by the app as workaround.

Thx in advance!

**Comment by thegeek1977** [comment] 2016-03-25 23:04
I can alsp confirm that the update does NOT work on a Sony Xperia Z5 running latest stock marshmallow (6.0.0) However only for the WAN part. Connecting the phone to WIFI on the same network as my server makes Syncthing connect immediately without a problem. However inputting the server manually as explained in @wweich post above makes everything works for me. This should definately be hardcoded into the app as a workaround or as a  permanent sol ution as it wont hurt to have it there anyway if you plan to use the standard Go compiler in the future.

**Comment by PaulAnnekov** [comment] 2016-03-25 23:59
Nexus 5 (latest Android 6.0.1). Discovery: 2/8, Relays: 0/1. It has connected only to local node (router network). Two nodes outside can't connect to my smartphone.
All nodes are using 0.12.21 core. Fix it, please.

**Comment by mouse256** [comment] 2016-03-26 07:38
I'm also having this issue on a motorola moto G (3rd gen) running android 6.0. Discovery: 2/8. I'll try to gather some traces later.

**Comment by bkev** [comment] 2016-03-26 07:53
I can confirm that DNS resolution also fails on a Galaxy S5 with the latest version. In the mean time I've rolled back as it's important for me to have the DNS working.

**Comment by mtift** [comment] 2016-03-26 14:23
I'm having the same issue on my Nexus 6. The latest update seems to have "Disconnected" my server. It's also very important for me to have DNS working, so I am going to try and figure out how to roll back.

**Comment by actinmyosin** [comment] 2016-03-27 08:09
I recommend a dynamic option that will fallback 1st to a cached set of recently seen locations, and 2nd to a static hardcoded list. The hardcoded fallback list could also be handled by seeding the cached locations list with them when the app is run for the first time (and also when it is switched from a manual list back to the default/dynamic public server.)

If manual settings are provided, the cache should be cleared and hardcoded fallback locations should be ignored.

**Comment by elconsultor** [comment] 2016-03-29 07:47
I can confirm that I have 3 devices with the problem of DNS

**Comment by khers** [comment] 2016-03-29 19:18
Thank you wweich, with your work around I am working on my Nexus 6p and 5x.

**Closed** 2016-03-30 20:31 UTC
Labels: bug
