### ISSUE TITLE
version 0.5.0.20 unable to add server with lollipop 5.1

### ISSUE THREAD

**Issue by fobe** [syncthing/syncthing-android#245] opened 2015-03-15 10:36 UTC
Hi,
I just did a fresh reset of my Nexus 5 with Lollipop 5.1. I installed Syncthing and wanted to add the server. I can scan the server ID and fill in the name but when it want's to restart it does nothing.
I tried to exit the app and try it again but it won't add the server. Then i tried to clear the cache and let it generates new keys but no luck. Still unable to add the server...
The server and Nexus 5 have the latest version of Syncthing.

I now tried Android Version 0.5.18 and that works...
So I manually installed version 0.5.20 and then the devices are disappeared (again)

**Comment by renyouguo** [comment] 2015-03-15 12:15
+1
Android 4.4.4

**Comment by Felix2yu** [comment] 2015-03-15 17:21
+2
Nexus 5 Android 5.1

**Comment by agit8** [comment] 2015-03-15 17:37
+3 
0.5.20 will not save added devices on android 2.3.6 .  I've also checked via the web gui and they don't show us there either

**Comment by dimitarkolev** [comment] 2015-03-15 17:59
+1 Nexus 5 Android 5.0.1

**Comment by Nutomic** [comment] 2015-03-16 00:10
Duplicate of #239.

**Closed by Nutomic** 2015-03-16 00:10 UTC
Labels: duplicate
