### ISSUE TITLE
Andriod App - 1.23.6.3 checkmarks white in light mode

### ISSUE THREAD

**Issue by nickichi84** [syncthing/syncthing-android#1955] opened 2023-08-01 22:20 UTC
The checkmarks for creating a folder or adding a new device are hidden in light mode theme. they apear when pressed due to highlight but they are colored white against a white background. 

checkmarks to be black in light mode and white in dark mode

i can change the phone display setting and the theme options within the app to cause it to switch between the two modes. When in light mode, the checkmark is white instead of black making it visually disappear from the gui

![Screenshot_20230801_171837_Syncthing](https://github.com/syncthing/syncthing-android/assets/141187977/bd89933b-769e-47a3-9a3e-d72282f923ef)
![Screenshot_20230801_171822_Syncthing](https://github.com/syncthing/syncthing-android/assets/141187977/4f65fc08-ad76-4842-a5c5-e49ba1e8dd5b)

### Version Information

    App Version: 1.23.6.3
    Syncthing Version: v1.23.6
    Android Version: Android 13
    Samsung S21 5G One UI 5.1

**Comment by nickichi84** [comment] 2023-08-01 22:32
Sorry, looks like it's a duplicate of #1950 & #1947.

**Comment by imsodin** [comment] 2023-08-06 12:51
Duplicate of #1947

**Closed by imsodin** 2023-08-06 12:51 UTC
