### ISSUE TITLE
Android starts and loop first time

### ISSUE THREAD

**Issue by Anthael** [syncthing/syncthing-android#645] opened 2016-05-15 21:16 UTC
On Android device running Android N it s very slow thé first time. Seems to loop infinitly.

**Comment by Nutomic** [comment] 2016-05-17 06:50
The key generation can take a few minutes, especially on a slow device. Is there anything in the logs that suggests an actual problem?

**Comment by lkwg82** [comment] 2016-07-26 20:20
maybe duplicate of #405

**Closed by lkwg82** 2016-07-26 20:20 UTC
