### ISSUE TITLE
Clicking Exit when Syncthing is disabled

### ISSUE THREAD

**Issue by ghost** [syncthing/syncthing-android#1494] opened 2020-04-20 04:15 UTC
In version 1.4.2, clicking Exit in the screen that says Syncthing is disabled because it is not connected to Wi-Fi will not exit the screen nor the application. Instead it runs Syncthing in the background.

**Comment by vhouriet** [comment] 2021-10-03 20:52
It looks like a duplicate of #1361 to me. Or am I missing something ?

**Closed** 2021-10-03 21:02 UTC
