### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by gerroon** [syncthing/syncthing-android#795] opened 2016-12-01 02:01 UTC
0.9.0 is constantly crashing on my device. I deleted the database and reinitiated all the syncs from scratch without much luck. Sometimes it crashes right away sometimes some minutes later.

0.9.0 running on Android Kitkat. I am using the  latest FDroid build. I do not use background run or other special methods. And I am not running it as root.

This is all I have just before the crashe via adb
```
W/GetTask ( 2826): 	at com.nutomic.syncthingandroid.http.RestTask.connect(RestTask.java:90)
W/GetTask ( 2826): 	at com.nutomic.syncthingandroid.http.GetTask.doInBackground(GetTask.java:47)
W/GetTask ( 2826): 	at com.nutomic.syncthingandroid.http.GetTask.doInBackground(GetTask.java:21)
E/AndroidRuntime( 2826): 	at com.nutomic.syncthingandroid.http.RestTask.execute(RestTask.java:66)
E/AndroidRuntime( 2826): 	at com.nutomic.syncthingandroid.service.RestApi.getConnections(RestApi.java:361)
E/AndroidRuntime( 2826): 	at com.nutomic.syncthingandroid.views.DevicesAdapter.updateConnections(DevicesAdapter.java:77)
E/AndroidRuntime( 2826): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment.updateList(DeviceListFragment.java:94)
E/AndroidRuntime( 2826): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment.access$000(DeviceListFragment.java:29)
E/AndroidRuntime( 2826): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment$1.lambda$run$0(DeviceListFragment.java:58)
E/AndroidRuntime( 2826): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment$1$$Lambda$1.run(Unknown Source)
W/ActivityManager(  355):   Force finishing activity com.nutomic.syncthingandroid/.activities.MainActivity
W/ActivityManager(  355): Activity pause timeout for ActivityRecord{41012ad0 u0 com.nutomic.syncthingandroid/.activities.MainActivity}
W/ActivityManager(  355): Activity destroy timeout for ActivityRecord{41012ad0 u0 com.nutomic.syncthingandroid/.activities.MainActivity}
W/ActivityManager(  355): Timeout executing service: ServiceRecord{4143db40 u0 com.nutomic.syncthingandroid/.service.SyncthingService}
I/ActivityManager(  355): Crashing app skipping ANR: ProcessRecord{413b33f0 2826:com.nutomic.syncthingandroid/u0a10039} Executing service com.nutomic.syncthingandroid/.service.SyncthingService
I/WindowState(  355): WIN DEATH: Window{4130aa50 u0 com.nutomic.syncthingandroid/com.nutomic.syncthingandroid.activities.MainActivity}
I/ActivityManager(  355): Process com.nutomic.syncthingandroid (pid 2826) has died.
W/ActivityManager(  355): Scheduling restart of crashed service com.nutomic.syncthingandroid/.service.SyncthingService in 5000ms
I/ActivityManager(  355): Start proc com.nutomic.syncthingandroid for service com.nutomic.syncthingandroid/.service.SyncthingService: pid=3055 uid=10039 gids={50039, 1015, 3003, 1028}
I/dalvikvm( 3055): Could not find method android.os.PowerManager.isPowerSaveMode, referenced from method com.nutomic.syncthingandroid.service.DeviceStateHolder.shouldRun
```

**Comment by gerroon** [comment] 2016-12-01 02:16
E/AndroidRuntime( 3622): FATAL EXCEPTION: main
E/AndroidRuntime( 3622): java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@4160ead0 rejected from java.util.concurrent.ThreadPoolExecutor@40ffca20[Running, pool size = 128, active threads = 128, queued tasks = 9, completed tasks = 56]
E/AndroidRuntime( 3622): 	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:1979)
E/AndroidRuntime( 3622): 	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:786)
E/AndroidRuntime( 3622): 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1307)
E/AndroidRuntime( 3622): 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:589)
E/AndroidRuntime( 3622): 	at com.nutomic.syncthingandroid.http.RestTask.execute(RestTask.java:66)
E/AndroidRuntime( 3622): 	at com.nutomic.syncthingandroid.service.RestApi.getConnections(RestApi.java:361)
E/AndroidRuntime( 3622): 	at com.nutomic.syncthingandroid.views.DevicesAdapter.updateConnections(DevicesAdapter.java:77)
E/AndroidRuntime( 3622): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment.updateList(DeviceListFragment.java:94)
E/AndroidRuntime( 3622): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment.access$000(DeviceListFragment.java:29)
E/AndroidRuntime( 3622): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment$1.lambda$run$0(DeviceListFragment.java:58)
E/AndroidRuntime( 3622): 	at com.nutomic.syncthingandroid.fragments.DeviceListFragment$1$$Lambda$1.run(Unknown Source)
E/AndroidRuntime( 3622): 	at android.os.Handler.handleCallback(Handler.java:725)
E/AndroidRuntime( 3622): 	at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 3622): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3622): 	at android.app.ActivityThread.main(ActivityThread.java:5041)
E/AndroidRuntime( 3622): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3622): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 3622): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
E/AndroidRuntime( 3622): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
E/AndroidRuntime( 3622): 	at dalvik.system.NativeStart.main(Native Method)
E/ViewRootImpl(  420): Skipped update region:StatusBar

**Comment by Nutomic** [comment] 2016-12-01 09:06
Your first seems to be missing some lines at the beginning. It should start with "FATAL EXCEPTION: main" and the name of the exception. Can you reproduce this and get the complete log?

The second one is already fixed in master, I will make a new release with that soon.

**Comment by kluppy** [comment] 2016-12-02 08:14
I just setup a new phone and it crashed continuously until it finally got into sync.
When I went into the logs it just said retrieving logs then crashed before anything was displayed. Is there any way I can get you useful information?

I can wipe the old phone repeatedly and run the syncs logging with any options you would like.

**Comment by Nutomic** [comment] 2016-12-05 05:05
[Install adb on your PC](http://www.howtogeek.com/125769/how-to-install-and-use-abd-the-android-debug-bridge-utility/), then run `adb logcat -s *:E`.

**Closed** 2017-08-25 10:10 UTC
