### ISSUE TITLE
Crash on launch after update to 1.2.2.2

### ISSUE THREAD

**Issue by jackfrost2013** [syncthing/syncthing-android#1403] opened 2019-09-10 01:05 UTC
After updating app crashes on launch.  After reinstalling app it worked until after I clicked finish in the setup.

I did not clear any cashes and I'm not sure how to collect a log for you.

### Version Information

    App Version: 1.2.2.2
    Syncthing Version: v1.2.2.2
    Android Version: Android 9 BUILD PQ1A.190105.112

**Comment by dessalines** [comment] 2019-09-10 02:20
I'm getting this too.

**Comment by ElXreno** [comment] 2019-09-10 03:57
Me too.

**Comment by mrbadluck** [comment] 2019-09-10 04:24
Same here

**Comment by ElXreno** [comment] 2019-09-10 04:24
I dumped a log:

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nutomic.syncthingandroid.debug, PID: 27209
    java.lang.RuntimeException: Unable to start service com.nutomic.syncthingandroid.service.SyncthingService@a3773a4 with Intent { cmp=com.nutomic.syncthingandroid.debug/com.nutomic.syncthingandroid.service.SyncthingService }: java.lang.SecurityException: Permission Denial: startForeground from pid=27209, uid=10146 requires android.permission.FOREGROUND_SERVICE
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3724)
        at android.app.ActivityThread.access$1600(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.SecurityException: Permission Denial: startForeground from pid=27209, uid=10146 requires android.permission.FOREGROUND_SERVICE
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5202)
        at android.app.Service.startForeground(Service.java:695)
        at com.nutomic.syncthingandroid.service.NotificationHandler.updatePersistentNotification(NotificationHandler.java:172)
        at com.nutomic.syncthingandroid.service.SyncthingService.onStartCommand(SyncthingService.java:233)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3705)
        at android.app.ActivityThread.access$1600(ActivityThread.java:200) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:9316)
        at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1193)
        at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:874)
        at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:20619)
        at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:977)`

How I understand this has been already fixed in version 1.2.2.3 by this commit:  https://github.com/syncthing/syncthing-android/commit/439476c18d301db07cc18948b594442750d2adb5.

**Comment by AudriusButkevicius** [comment] 2019-09-10 06:05
1.2.2.3 was released to address this, I am not sure why people don't just update the app?

**Comment by mrbadluck** [comment] 2019-09-10 06:16
Because version 1.2.2.3 isn't in F-Droid repo, yet :)

**Comment by imsodin** [comment] 2019-09-10 06:41
Then just wait, it's still a duplicate of tons of existing, closed issues. We know 1.2.2.2 crashes, any new messages regarding that versions don't help, as there's nothing left to do. (Leaving this open in the hopes of preventing new issues.)

**Comment by puppe** [comment] 2019-09-10 08:45
> 1.2.2.3 was released to address this, I am not sure why people don't just update the app?

[F-Droid doesn't have 1.2.2.3 yet](https://f-droid.org/de/packages/com.nutomic.syncthingandroid/). In fact, 1.2.2.2 has been released there yesterday.

**Comment by imsodin** [comment] 2019-09-10 08:58
Yes, that's known too. They have a script that scrapes our releases every now and then and builds them on their own server. So this still applies:

> just wait

or downgrade while waiting.

**Comment by puppe** [comment] 2019-09-10 09:23
F-Droid [has already picked up on the new release](https://gitlab.com/fdroid/fdroiddata/commits/master/metadata/com.nutomic.syncthingandroid.yml). But there is apparently some latency in the whole process.

> just wait

Will do.

> or downgrade while waiting.

Just adding, that downgrading didn't work for me. I would probably have to uninstall beforehand, but I don't want to lose my configuration.

**Comment by bobdig** [comment] 2019-09-10 16:17
Downgrade didn't work so I uninstalled and reinstalled and LOST ALL MY SETTINGS!!
Just a Warning.

**Comment by dantuck** [comment] 2019-09-10 17:00
This issue also applies to Android 10. Downgrading does not fix the issue.

**Comment by AudriusButkevicius** [comment] 2019-09-10 17:15
Locking this as there is a lot of "me too" even if its some tiny detail that is different.

Yes, it's broken, on all versions on android, on all variations of devices. Wait for the 1.2.2.3 upgrade to flow through fdroid.

**Closed** 2019-09-26 07:04 UTC
