### ISSUE TITLE
Saving versions (Versions Path) to the selected folder does not work properly.

### ISSUE THREAD

**Issue by VlaK0r** [syncthing/syncthing-android#1956] opened 2023-08-04 17:28 UTC
Hello!
Thank you for your work!

It is impossible to select through the application  (Versions Path - Simple File Versioning)
This can only be done through the web interface. 
But after a while the settings are reset and the versions are saved to the default folder (.stversions).

    App Version: v1.23.7-rc1.2
    Syncthing Version: v1.23.7-rc1 android
    Android Version: Android 13 / Samsung One UI 5.1

**Comment by tomasz1986** [comment] 2023-08-04 20:25
Possibly a duplicate of https://github.com/syncthing/syncthing-android/issues/1257? Essentially, the problem can affect a variety of settings that are only available to configure through the Web GUI. I'd say, basically, if you want to use advanced settings that aren't configurable through the app, you should stick to using the Web GUI only and not use the app to add, remove or edit folders and devices at all.

**Comment by imsodin** [comment] 2023-08-06 12:51
Yes, duplicat of #1257

**Closed by imsodin** 2023-08-06 12:51 UTC

**Comment by VlaK0r** [comment] 2023-08-06 12:56
> Yes, duplicat of #1257

I don't agree.
