### ISSUE TITLE
Simplified Chinese garbled

### ISSUE THREAD

**Issue by mapleshadow** [syncthing/syncthing-android#237] opened 2015-03-13 15:04 UTC
Simplified Chinese garbled
Folder, host name, as long as it is simplified Chinese will become a symbol:?

![screenshot_2015-03-13-22-54-50](https://cloud.githubusercontent.com/assets/525478/6640895/4b123d80-c9d5-11e4-8a44-5b6bdb7c98a0.png)

**Comment by Nutomic** [comment] 2015-03-13 17:58
So you have chinese characters only in the path, or also in the folder ID?

Can you check if the web GUI displays it correctly?

**Comment by Nutomic** [comment] 2015-03-13 18:09
Actually, this seems to be a duplicate of #228, and I can reproduce it.

Will look into it.

**Closed** 2015-03-13 18:14 UTC
Labels: duplicate
