### ISSUE TITLE
DCIM folder

### ISSUE THREAD

**Issue by axet** [syncthing/syncthing-android#550] opened 2016-01-30 17:38 UTC
Android has two separate folders for Camera images and Screenshots. Syncthing can help organize those files automatically moving those files into one folder, which can be shared a cross devices.

Android does not allow you to create symlinks on sdcard device, or change custom paths for those folders. The only option - by using external application like syncthing.

Watch Folder /sdcard/DCIM/Camera && /sdcard/Pictures/Screenshot (those are hardcoded in the andrdoid source) and move then into /sdcard/Syncthing with proper rename to make it sorted propertly 2010-12-31.jpg

Like Dropbox does...

**Comment by licaon-kter** [comment] 2016-01-30 17:47
The gallery app organises them pretty good, why bother with this?

**Comment by axet** [comment] 2016-01-31 06:10
@licaon-kter 

Syncthing by default shares Camera folder, but not Screenshots folder. I think would be fair to make a complete solution for "pictures" by moving all camera things to one, user specified folder.

**Comment by licaon-kter** [comment] 2016-01-31 07:19
That's a folder set up as an example, it's not a tailored solution for anything, it's just there to sho you how it looks and what you should expect.
You need to furthur set it up as you wish.

/mark as invalid

**Comment by axet** [comment] 2016-01-31 08:24
Here I made Camera class which does the job:

https://github.com/axet/android-pictures-merge/blob/master/app/src/main/java/com/github/axet/mover/Camera.java

**Comment by veniosg** [comment] 2016-01-31 09:59
This sounds out of scope considering Syncthing is a sync tool and not a
plug and play backup solution.

**Comment by axet** [comment] 2016-01-31 10:05
In my opinion Android version of Syncthing should work with Pictures taken with smartphone.

**Comment by licaon-kter** [comment] 2016-01-31 13:05
It works, once you ADD FOLDER.

I don't really see what the issue is.

**Comment by Nutomic** [comment] 2016-01-31 14:41
I agree, this is out of scope for Syncthing. Just add a new folder, or use your hack. But most people would be confused by this.

**Closed by Nutomic** 2016-01-31 14:41 UTC

**Comment by axet** [comment] 2016-01-31 14:45
You think having two folders to sync one smartphone is a proper way to use this application?

I should add /sdcard/DCIM and /sdcard/Pictures/Screenshots just to keep everything up to date?

Anyway, I'm trying to make this app more friendly to end user, who just need his phone Pictures on laptop without any hacks.

**Comment by Nutomic** [comment] 2016-01-31 15:15
Me and other contributors don't think this should be in Syncthing. Feel free to make a seperate app that does this. Or fork Syncthing and publish your own version.

**Comment by Zillode** [comment] 2016-01-31 20:08
@axet I truly believe there is room for this. A dedicated Syncthing-Android-Picture app could be useful for novice users
