### ISSUE TITLE
"Restart Later" while adding folders doesn't seem to work.

### ISSUE THREAD

**Issue by mkaito** [syncthing/syncthing-android#416] opened 2015-07-02 15:19 UTC
If I select to "restart later" while intending to add multiple folders (use case: setting up a clean device with a bunch of folders), the add folder dialog doesn't close, the folder isn't added to the config, and using the notification to restart syncthing hangs indefinitely (or until I force close the app via app manager).

Actually, the app seems to hang really often, even if I restart it along with adding a folder.

**Comment by Nutomic** [comment] 2015-07-02 16:16
Can you post a logcat?

**Comment by mkaito** [comment] 2015-07-03 02:11
I'm trying to get a logcat of the stuck loading thing, but it's been running rather well ever since I got home this evening. I'll see if it happens again while I'm logging.

As for the issue with restarting later, the create folder dialog should close after the changes have been registered. I shouldn't have to press back out of it once I'm done (and not yet rebooting). Same thing for the delete folder dialog. The impression I first got when trying to add multiple folders was that nothing was happening. So I hit "create" again. And again. And upon restarting, I had 3 duplicate folders.

**Comment by Nutomic** [comment] 2015-07-03 16:04
Ok I opened #417 for that.

**Comment by janjachnik** [comment] 2015-07-07 13:10
I've had the same issue. It seems that if you select "restart later" then "add" operations (devices or folders) don't _appear_ to work anymore (but they do). When you click "add" after a restart later, nothing happens. No prompt, nothing. However, if you now manually restart Syncthing then the folders/devices you tried to add will be there.

Also, is it me being blind or is there no way to restart syncthing from the UI after a "restart later"?

**Comment by Nutomic** [comment] 2015-07-07 16:40
Yeah, this is partially a duplicate of #355. I just noticed it was pretty pointless of me to open #417. 

@janjachnik Only by clicking the notification, or exiting the app and starting it again. Feel free to open a new issue for a proper restart button.

**Closed by Nutomic** 2015-07-07 16:40 UTC
