### ISSUE TITLE
d'nt start, d'nt work on internal/external flash

### ISSUE THREAD

**Issue by SergeyDjam** [syncthing/syncthing-android#851] opened 2017-02-28 07:52 UTC
Android 4.2.2
Qumo Altair 702
Syncthing 0.9.6 f-droid, this problem on all versions
Link2flash
Internal flash 4Gb
External flash 32Gb

1. Install syncthing
2. Move to internal flash
3. Start
4. Crash and message "syncthing не смог создать конфигурацию"

2. Move to external flash
3. Start
4. Crash with message "syncthing не смог создать конфигурацию"

**Comment by licaon-kter** [comment] 2017-02-28 09:28
/clse as duplicate of #87 maybe ?

**Comment by SergeyDjam** [comment] 2017-02-28 09:50
yes, this bug dublicate #87

**Comment by SergeyDjam** [comment] 2017-02-28 10:21
> What does 2. Move to internal flash mean?

Syncthing setup on system section flash by default. 
Flash partitions 
1. system 1 Gb
2. userspace 4 Gb

df
/system 640M
/data    1008M
/storage/sdcard0 4G
/storage/sdcard1 29G

I am after a program installation to move it on other sections

**Comment by SergeyDjam** [comment] 2017-02-28 10:40
Not for long. Through short time all resources and the application come to an end doesn't work any more

**Comment by SergeyDjam** [comment] 2017-03-20 13:27
Now 0.9.7 version. Not fix it

**Comment by SergeyDjam** [comment] 2017-03-31 14:12
Now 0.9.8 version. Not fix it

**Comment by Nutomic** [comment] 2017-04-01 03:58
Storing the app on external storage is not supported, and won't be supported unless someone wants to fix that. What exactly is the problem when you run it on internal storage? Can you post logs?

**Comment by SergeyDjam** [comment] 2017-05-12 17:26
0.9.9 no work too

**Comment by SergeyDjam** [comment] 2017-05-12 17:30
> Storing the app on external storage is not supported, and won't be supported unless someone wants to fix that.

Why? All size program 34.45 Mb!

**Comment by licaon-kter** [comment] 2017-05-12 19:14
The actual program is written in the Go language, the Android version does not yet support external cards.

Connect to a PC via USB, use adb logcat to get the logs during start, you can find info on the internet.

**Closed** 2017-09-20 10:45 UTC
