### ISSUE TITLE
Device status is shown "Up to date" but in reality it is "Syncing"

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#557] opened 2016-02-06 16:32 UTC
Syncthing-android is currently backing up data to remote peer, but both "Folders" and "Devices"  tabs show "Idle (100%)" and "Up to Date" respectively, misleading me as if everything is already backed up and I can disconnect the network. Only nonzero "Download" and "Upload" meters hint that something is happening now.

If I activate "Web UI" I see the "70%" for the peer, which is closer to reality.

**Comment by Nutomic** [comment] 2016-02-07 18:31
Seems to  be a duplicate of #74.

**Closed by Nutomic** 2016-02-07 18:31 UTC
