### ISSUE TITLE
Every checkbox is checked by default in the Web GUI: Settings

### ISSUE THREAD

**Issue by Aeyoun** [syncthing/syncthing-android#474] opened 2015-11-06 00:32 UTC
When you open the Web GUI: Settings, every checkbox is ticked by default regardless of the option's saved state. This problem only exist in syncthing-android distribution. I don't see the same issue in the regular upstream syncthing distribution.

**Comment by Nutomic** [comment] 2015-11-08 22:55
We also need more info here (same as the other issue).

**Comment by Nutomic** [comment] 2015-12-21 21:15
Closing this because I can't reproduce this. Feel free to reopen with more info.

**Closed by Nutomic** 2015-12-21 21:15 UTC

**Comment by Aeyoun** [comment] 2015-12-21 22:21
I can’t reproduce it anymore myself. But I’ve also changed from CyanogenMod  to Sony-Android.
