### ISSUE TITLE
Reinstall of Syncthing--> syncthing remains disabled

### ISSUE THREAD

**Issue by Balinus** [syncthing/syncthing-android#728] opened 2016-08-20 13:14 UTC
I uninstalled Syncthing and reinstalled it. Now, when I launch syncthing, I get a menu saying that syncthing is disabled and I have 2 choice : go to parameters or quit. When going to parameters, I don'T see any option of "enabling" syncthing. Hence, the app keeps closing since I can't seem to be able to enable it. I rebooted, without success. 

### Version Information

    App Version: 0.8.2
    Syncthing Version: v0.14.3
    Android Version: Android 6.0 / Cyanogenmod x / ...

**Comment by Nutomic** [comment] 2016-08-20 13:54
You probably have sync disabled in account settings. Duplicate of #727.

**Comment by Balinus** [comment] 2016-08-20 14:19
Well, sync in android is "on". However, I don't see a syncthing account in the list.

**Comment by Nutomic** [comment] 2016-08-20 14:23
It is not in the list, but still respects that setting. The other possibility is that you are in battery saving mode.

**Comment by Balinus** [comment] 2016-08-20 14:27
Battery saving mode was the culprit. Thanks!

**Closed** 2016-08-20 14:27 UTC
