### ISSUE TITLE
WLAN Filter list does not Work

### ISSUE THREAD

**Issue by Wombatsmann** [syncthing/syncthing-android#700] opened 2016-07-22 05:28 UTC
I activatec Sync only in WLAN. But if I select my Network Name in the WLAN filter list the app asks to end or change settings. Tried this in different Wlans.

**Comment by capi** [comment] 2016-07-22 07:07
Does it work with an empty list (i.e. sync on all WiFis)? If not, your Android is not detecting that it has Internet connection via the WiFi and does not consider the WiFi as connected.

I'm using the WiFi white-list every day and I'm surprised it's not working. Which version are you using? (I'm still on the 0.7.x version (0.13 Syncthing)).

**Comment by Wombatsmann** [comment] 2016-07-22 18:43
Yes it works with an empty list. I updated to Syncthing 0.14 and this problem is still there.
Its an Samsung GT-S7710 on Android 4.1.2

**Comment by capi** [comment] 2016-07-22 19:36
Can you provide me with an `adb log` of the device when switching on/off the entries in the list? I just compiled and installed this version and it works flawlessly in my environment. So it might be that the device does not report the WiFi name correctly but I'd need to get the logs to have a look.

**Comment by Wombatsmann** [comment] 2016-07-23 08:49
This is the output of adb logcat. I activated the Network filter and selected my Wlan. Then the popup came up and asked me to end it or change settings. Thats when I started the log to adb_logcat.txt. The other file is the way back.

Am 22. Juli 2016 21:36:54 MESZ, schrieb Martin Carpella <notifications@github.com>:

**Comment by Wombatsmann** [comment] 2016-07-23 13:18
Sorry I didnt know that the reply would post this here. Did you get the logcat.zip? I don't want to post it here in fact of my personal informations like ST folder Structure etc.

**Comment by Nutomic** [comment] 2016-07-23 18:47
I don't think Github supports email attachments. But you should be able to send it to @capi and me on the [forum](https://forum.syncthing.net/). Usernames are the same.

**Comment by capi** [comment] 2016-08-11 19:14
@Wombatsmann I finally had time to review the adb-logs you submitted. Everything works fine with `All SSIDs allowed for syncing` until suddenly `SSID <redacted> not whitelisted`.

Are you sure you did not change any settings in "Restrict to certain wifi networks" option and removed the SSID in question?

Another possibility would be that there are some characters in the WiFi name, which I never tested (space and `+` sign, actually). Maybe the selector UI messes up the SSID name somehow. I'll add additional logging, so we can be diagnose this better.

**Comment by capi** [comment] 2016-08-11 19:25
I think I found something:

`WifiInfo.getSSID()` specifies:
> If the SSID can be decoded as UTF-8, it will be returned surrounded by double quotation marks. Otherwise, it is returned as a string of hex digits.

Yours is not HEX digits, but not surrounded in quotation marks either. That's why the comparison fails... I'm not entirely sure how to work-around this without breaking stuff. I'll think about it.

**Comment by capi** [comment] 2016-08-11 19:57
@Wombatsmann could you try a build from https://android.syncthing.net/job/Syncthing-Android-PR/254/ and send the logs again to @Nutomic?

**Comment by Nutomic** [comment] 2016-08-19 11:55
Is this a duplicate of #634?

**Comment by capi** [comment] 2016-08-21 11:22
I think they are two separate issues, that could have a common root-cause. #634 is about "Sync on Wifi" not working reliably at all (with and without whitelist), while #700 (this issue) is about the whitelist not working. 

Root-cause for this issue is, that the names returned from the "known WiFi" list are not a literal match to the currently connected WiFi. Should be, but it isn't. I'll propose some workarounds for this in a PR.

**Comment by Nutomic** [comment] 2016-08-21 14:48
Okay cool. Maybe you can rename the issues to clarify a bit?

**Comment by Wombatsmann** [comment] 2016-09-17 13:20
Sorry, I didn't look at this a long time. But when I tried to use the Build from  https://android.syncthing.net/job/Syncthing-Android-PR/254/ somthing failed, I cant even remeber what exactly, and I was frustrated and removed ST from my device. I think I will have some time soon to try it.

**Comment by rsteinberg** [comment] 2017-04-21 13:25
Hey there, looks like the issue still exists in the current version. Syncthing stays off even when I'm on the whitelisted Wi-Fi. Could you look into this again? I can help to test a build if needed. Maybe you could try to put your attempted fix in a build that is more recent than the one you provided last time.

**Comment by Catfriend1** [comment] 2018-04-22 13:27
@Wombatsmann  @rsteinberg  Let's continue this issue if it is still present in the most recent issue linked at https://github.com/syncthing/syncthing-android/issues/975

**Closed by Catfriend1** 2018-04-22 13:27 UTC
Labels: bug
