### ISSUE TITLE
Can't disable usage reports with 0.9.8

### ISSUE THREAD

**Issue by Diapolo** [syncthing/syncthing-android#872] opened 2017-03-31 07:05 UTC
After upgrading to the latest release, I'm not able to disable anon usage reports. I deselect the option, restart and afterwards the option is selected again.

### Version Information

    App Version: 0.9.8
    Syncthing Version: v0.14.25-rc.2
    Android Version: Android 6.0.1 / Cyanogenmod 13

**Comment by wweich** [comment] 2017-03-31 07:32
The Android App now uses the RC version of Syncthing (for some reason). RC versions enforce usage reporting.

Did you install from play store or f-droid?

@Nutomic: I thought the debate in the forums ended with: Android app should only use final versions.

**Comment by Diapolo** [comment] 2017-03-31 09:02
I downloaded the App via F-Droid.

**Comment by scienmind** [comment] 2017-03-31 13:49
>  Android App now uses the RC version of Syncthing (for some reason)

I don't think it should be that way. Stable channel should be used here...
Is it by mistake or by design?

**Comment by wweich** [comment] 2017-03-31 14:23
The play store version uses the final 0.14.25. the f-droid version uses 0.14.25-rc2.
The f-droid version is build by f-droid, not by the Syncthing devs, so maybe they fetched the wrong version (an earlier start android version).

**Comment by Nutomic** [comment] 2017-04-01 03:50
It should definitely not use the rc version. Really sounds like F-Droid used to wrong version, but no idea why.

**Comment by licaon-kter** [comment] 2017-04-01 08:13
Here https://github.com/syncthing/syncthing-android/commit/0d32d180327c52338a06a057432c7fd38172be6f you point to that commit, but Syncthing tags [0.14.25](https://github.com/syncthing/syncthing/releases/tag/v0.14.25) AND [0.14.25-rc2](https://github.com/syncthing/syncthing/releases/tag/v0.14.25-rc.2) BOTH point to that commit, I guess it takes the oldest tag it encounters when importing the submodule (so there might be a difference in the way F-Droid gradle builds this and you build it for Google Play store)

**Comment by imsodin** [comment] 2017-04-01 08:56
@licaon-kter The tagging is intentional: The last release candidate (i.e. where no regressions were found) becomes the new release, without any change, at which point it is tagged again without the rcX suffix. Syncthing detects the "-rcX" in the version (version is the newest tag applied) to decide whether it is a stable release or a release candidate. So the folks at FDroid have the exact same binary, but due to the version string it runs as release candidate. I don't know how that could even happen, as the version string is auto-generated, unless they pulled their version before the actual release.

**Comment by maiaftv** [comment] 2017-04-01 10:00
Whoops. I did post in the wrong repo. Also experiencing the same issue.

**Comment by licaon-kter** [comment] 2017-04-01 11:19
Reported: https://gitlab.com/fdroid/fdroiddata/issues/660

**Comment by AudriusButkevicius** [comment] 2017-04-01 11:59
Closing this in that case.

**Comment by krt16s** [comment] 2017-04-02 14:49
I am not familiar how `git describe` works, but our metadata is fine and works -- at least when building it now. So I'd guess 0.9.8 sometime linked to the right commit, which had the rc tag but was missing the release tag (at least on github) or something... will pull the apk and rebuild it.

**Comment by licaon-kter** [comment] 2017-06-02 19:39
And again in 0.9.10.

**Comment by licaon-kter** [comment] 2017-06-02 19:42
And again in 0.9.10, syncthing 0.14.29-rc1 and 0.14.29 (release) point to the same commit: https://github.com/syncthing/syncthing/commit/8f3f787a343d9f93a4127d2a9e6dd76969082306

**Comment by Nutomic** [comment] 2017-06-05 04:55
Hmm, it seems that git only stores the commit hash for submodule version. So when you checkout that submodule commit and run `git describe`, it probably picks the first tag for that commit. There seems to be no way to set a submodule to a certain tag. 

The `git describe` in question is called from Syncthing's `build.go`, right? @calmh Would it be possible to change that call, so it always prefers a non-rc tag if a commit has multiple tags?

**Comment by calmh** [comment] 2017-06-05 06:44
Git describe selects the most recent tag. Possibly you just haven't fetched all the tags? Probably there is no reason for submodule update to do this if it already has the right hash.

**Comment by Nutomic** [comment] 2017-06-05 08:07
I'm not sure what the F-Droid build server does exactly, but I suppose it just runs `git clone --recursive` and thats it. Would it be enough if we call `git fetch --tags` in the submodule before running build.go?

**Comment by calmh** [comment] 2017-06-05 19:40
I would think so, yes.

**Closed** 2017-06-07 01:36 UTC
