### ISSUE TITLE
Nodes are reported as disconnected 

### ISSUE THREAD

**Issue by icaruseffect** [syncthing/syncthing-android#74] opened 2014-08-04 12:02 UTC
In the newest version all nodes are displayed as disconnected. 
When I'm checking the Web gui they are well shown as online as on all other devices. 
Also the up/download speed are not being displayed in the side bar (this pulley menu thing on the left) 
The behavior can be replicated on different Android devices. 
That all seems strange because as far as I know there were no changes in the rest api. 
Thanks :-)

**Comment by rdiaz02** [comment] 2015-03-31 16:27
Nodes are still being reported as disconnected, whereas the Web GUI correctly shows them as connected. This is with ST version 0.10.29 and ST android version 0.5.27.

**Comment by Nutomic** [comment] 2015-03-31 18:22
I just tried and it works (after a few extra seconds). Can you see if there's anything in the logs?

**Comment by rdiaz02** [comment] 2015-03-31 19:50
After waiting (closer to a minute than a few seconds) nodes are reported. But they were not reported when I moved to the "devices" tab, even if the device had been in sync with several nodes for several hours already.

**Comment by rdiaz02** [comment] 2015-04-05 13:13
In case it matters, I keep seeing this problem very often: frequently (about 50% of the time I try?) truly connected devices are not shown after waiting, say, < 5 seconds. I say about 5 seconds, since more than that I think is unreasonable to wait: it is faster to just go to the web gui. Waiting for longer periods of times (minutes) will often show them as connected, yes.

**Comment by Nutomic** [comment] 2015-04-05 18:09
You're right. We should investigate why this happens.

**Comment by keymaster312** [comment] 2015-05-17 12:22
Is this issue exclusive to Android clients? All my clients work except for Android. Though it also does not seem to be fully syncing, it shows disconnected no matter what I do. Seems to sync at random times though...

**Comment by nikname2k** [comment] 2015-08-07 10:06
We have the same problem, but with Windows nodes only. I don't use Android or something else, I just use Windows 7 on my home PC and remote work PC. Each other write me the Disconnected status. And another guy from my work say the same: Syncthinc works fine in the past, but have broken some time earlier (the same "Disconnected" issue).

The Windows only nodes is the main difference from the already posted comments in this topic. Most of the previous comments are related to the Android, I think.

**Comment by AudriusButkevicius** [comment] 2015-08-07 10:10
This is the android repo, let's keep the thread on subject. You seem to need support, hence I suggest you make a post on the forums.

**Comment by Unode** [comment] 2015-09-14 16:59
I also get a somewhat intermittent Android UI. Usually it works, it just takes longer. I also often find myself going to the Web GUI to confirm if indeed something is happening. This situation seems to happen more frequently when the system is busy doing other things like transferring data/files.

If the refresh issue is somewhat recurring, would it make sense to add a "(Force) UI refresh" button to the sections bar? If not a button, an option in the menu at least.

Thanks.

PS: During the time it took me to write the message, the UI hasn't refreshed once (v.0.11.22 - 0.6.6), the Web-GUI showed a ~40% progress change. Clients also show up as disconnected when clearly they aren't.

**Comment by Nutomic** [comment] 2016-03-08 00:19
This should be fixed in 0.7.9, can someone please confirm this?

**Comment by Unode** [comment] 2016-03-08 14:47
The interface seems a lot more responsive now.
I did notice something I don't remember seeing before though. When the "folders" section is refreshed it scrolls all the way to the top. So I need to keep scrolling down to check the progress.

Other than that it looks fixed here.

**Comment by Nutomic** [comment] 2016-03-08 15:28
Great! Can you open a new issue for the scrolling?

**Comment by rdiaz02** [comment] 2016-03-08 16:23
Thanks for the update: as @Unode mentions, it seems a lot more responsive. 

However, nodes are still being reported as disconnected when they are indeed connected (as shown by other nodes to which the device is connected, and as shown by the Web GUI). After a while, though, as usual, nodes will be reported as connected. But it seems I still need to go to the Web GUI if I want to know what is really connected and what is not.

**Comment by Nutomic** [comment] 2016-03-08 16:27
@rdiaz02 Can you describe under what circumstances this happens? Ideally with steps to reproduce.

**Comment by rdiaz02** [comment] 2016-03-08 16:33
Start syncthing. It comes up. It shows no devices are connected, but I see that the computer is showing that the android device is connected. I open the Web GUI in the Android and it also shows it is connected to the computer. I close the web GUI and the Devices is still saying that nothing is connected.

**Comment by Nutomic** [comment] 2016-03-08 16:36
Ah, that is expected because we only refresh the data [every 100 seconds](https://github.com/syncthing/syncthing-android/blob/7d93d75813ce7f4fd5bbfbedc3aaaa201af2f0ee/src/main/java/com/nutomic/syncthingandroid/syncthing/PollWebGuiAvailableTask.java#L29). See #344 for faster updates .

**Closed by Nutomic** 2016-03-08 16:36 UTC
Labels: bug

**Comment by rdiaz02** [comment] 2016-03-08 16:40
Oh, I see, sorry for being nitpicky then. And thanks for pointing it out. 

(And, parenthetically: I find the behavior of the new version a lot snappier, faster, and more reliable; having to wait up to a 100 seconds for the GUI to show the connected devices, or just switching to the Web GUI is just perfeclty fine.)
