### ISSUE TITLE
App thinks phone is on battery when wirelessly charging

### ISSUE THREAD

**Issue by mdavis-xyz** [syncthing/syncthing-android#1540] opened 2020-08-10 10:33 UTC
# Steps to reproduce

* In settings, set "run when device is power by" to "AC Power"
* Put phone on wireless charger
* open the app

# Expected behavior

App runs

# Actual behavior

App refuses to run

> Device is running on battery

![Screenshot_20200810-202707_Syncthing](https://user-images.githubusercontent.com/7035647/89774144-a32d3a80-db48-11ea-94e5-548a6bc00c61.jpg)

Note the charging icon in the top-right of the screenshot

When I move the phone off the wireless charger onto a wired charger, it works.

### Version Information

    Samsung S20

    App Version: 1.6.1
    Syncthing Version: v1.6.1
    Android Version: Android 10

**Comment by ArkadiuszNiemiec** [comment] 2020-10-18 22:57
This is huge issue for me. I have started investigating, leaving notes here.

The code that's checking the charging state is here:
https://github.com/syncthing/syncthing-android/blob/9f646cc28b7ab40c1556d0d24e1348229e01da84/app/src/main/java/com/nutomic/syncthingandroid/service/RunConditionMonitor.java#L297-312

**Comment by itskando** [comment] 2020-11-11 20:42
From [here](**url**), I think killing the notification would help.
Which might hint that persistent mode is an issue.

**Comment by itskando** [comment] 2020-11-11 21:19
Fixed broken link.

**Comment by lclc98** [comment] 2021-12-04 09:23
I can confirm it seems to be a delay with updating the status. I looked into how home assistant solved this and they seem to be delaying the update by 5 seconds.
https://github.com/home-assistant/android/blob/master/common/src/main/java/io/homeassistant/companion/android/common/sensors/SensorReceiverBase.kt#L85-L90

**Comment by imsodin** [comment] 2022-03-26 15:13
Duplicate of https://github.com/syncthing/syncthing-android/issues/1595

**Closed by imsodin** 2022-03-26 15:13 UTC
