### ISSUE TITLE
Deleting a folder doesn’t change the folder list

### ISSUE THREAD

**Issue by Profpatsch** [syncthing/syncthing-android#353] opened 2015-04-14 13:39 UTC
When you hit delete inside a folder’s settings (and ignore the restart prompt), the folder settings don’t go away and when you hit back, this folder is still displayed in the list.

**Comment by Nutomic** [comment] 2015-04-22 21:57
Closing this as duplicate of #355.

**Closed by Nutomic** 2015-04-22 21:57 UTC
