### ISSUE TITLE
Adding a new device using the native GUI wipes out folder/device defaults previously set in the Web GUI

### ISSUE THREAD

**Issue by tomasz1986** [syncthing/syncthing-android#1744] opened 2021-12-19 17:24 UTC
1. Install the app and start it.
2. Open the Web GUI and change some folder and device default settings.
3. Exit the Web GUI, then use the native GUI to add a new device.
4. The previously modified default settings have been reset.

This happens in the current app release, which is v1.18.3.

The only workaround seems to be to stick strictly to the Web GUI and not use the native GUI to do any actual changes.

**Comment by imsodin** [comment] 2021-12-19 17:30
Closing as a duplicate of https://github.com/syncthing/syncthing-android/issues/1257

It's not the same effect, but the same cause: Outdated config in java, respectively not using the new PATCH methods.

**Closed by imsodin** 2021-12-19 17:30 UTC
