### ISSUE TITLE
Shows "No devices found" in 0.5.20, webgui ok though

### ISSUE THREAD

**Issue by chucic** [syncthing/syncthing-android#243] opened 2015-03-15 08:27 UTC
Syncthing for Android won't show me devices, but in webgui its ok and I'm even connected.

**Comment by Nutomic** [comment] 2015-03-15 09:47
Duplicate of #239.

**Closed by Nutomic** 2015-03-15 09:47 UTC

**Comment by chucic** [comment] 2015-03-15 10:56
For my defense, when I fired this issue, #239 was about "offline".

**Comment by Nutomic** [comment] 2015-03-15 17:51
Yeah sorry i messed that up.
