### ISSUE TITLE
When "run as root" option enabled, Syncthing creates database files as root instead of as Syncthing user

### ISSUE THREAD

**Issue by vi** [syncthing/syncthing-android#558] opened 2016-02-06 17:00 UTC
"root mode" should imply _only_ additional access to directories, everything else (in particular, owner for inner database or configuration files) should remain the same as if Syncthing runs as regular user. Running syncthing instance should know which uid it should use for database/settings/network communications and only use priveleged access for accessing data to be synced.

This prevents switching "root mode" off without [manual intervention](https://github.com/syncthing/syncthing-android/issues/524#issuecomment-180777664).

As a workaround, bindfs-based solution may be used. Bindfs can securely "forward" root's view of filesystem to non-root Syncthing.

**Comment by licaon-kter** [comment] 2016-02-06 19:06
Duplicate of https://github.com/syncthing/syncthing-android/issues/453

/close

**Comment by vi** [comment] 2016-02-06 19:19
@licaon-kter, Again, judging from title of #453 it does not seem to be a duplicate. That is about UI access to root-enhanced locations, not about inability to switch back to non-root.

Maybe issues tend to grow out of initial scope in this repository?

**Comment by licaon-kter** [comment] 2016-02-06 20:00
The issue is discussed there: syncthing inability to use proper root
When that is fixed, all these will be too.

**Closed** 2016-02-07 18:16 UTC
Labels: duplicate
