### ISSUE TITLE
Syncthing permanently have high load

### ISSUE THREAD

**Issue by Mannshoch** [syncthing/syncthing-android#931] opened 2017-07-29 17:26 UTC
After some Problem with High loads on syncthing ig got on the syncthing web-page that syncthing has files in queue which since a long time not anymore exist on mobile phone and also on PC.
I  exported the settings with the syncthing backup Menu entry and removed his date from Android App-Info.
After that I started Syncthing again and imported the settings again. Now again I have high load but also I'm not anymore able to open the syncthing web-page. I also tried to uninstall/install Syncthing. 

Logfile from "OS Monitor" 
[Log-2017-07-29-06.48.14.txt](https://github.com/syncthing/syncthing-android/files/1185104/Log-2017-07-29-06.48.14.txt)

**Comment by Mannshoch** [comment] 2017-08-14 08:58
did you need some more information?

**Comment by Mannshoch** [comment] 2017-08-24 17:32
[Log-sy..2017-08-24-07.14.42.txt](https://github.com/syncthing/syncthing-android/files/1249743/Log-sy.2017-08-24-07.14.42.txt)

**Comment by AudriusButkevicius** [comment] 2017-08-24 18:19
You seem to have ignored files that are preventing folder removal that is causing this.

**Comment by Mannshoch** [comment] 2017-08-25 09:36
thats OK so I do not want get them removed.
In the first I wish some kind of Limit for the CPU use. Even I wish to sync some hundred MB it should not get my phone that hot and Battery draining. 
And second, transferring Data by FTP need Much lower energy.

**Comment by AudriusButkevicius** [comment] 2017-08-25 09:47
Well you removed a folder on the other end, and that folder locally has ignored files and cannot be removed. Syncthing retries every minute to see if the situation has changed, hence why you have battery drain.  You've put yourself in this type of situation by deleting folders that from syncthings perspective are impossible to remove due to the constraints you've given it.

**Comment by AudriusButkevicius** [comment] 2017-08-25 09:48
I am closing this as this is not really a bug, but user impossing unreasonable constraints.

**Closed by AudriusButkevicius** 2017-08-25 09:48 UTC

**Comment by Mannshoch** [comment] 2017-08-25 11:03
Sorry but I work a lot with Ignored Files. Especial on phone. And why should the phone look every time on this directory? Syncthing knows that there are ignored files in it. Whats the different with other directory with content? As far Syncthing is not looking in every direcory every minutes. why should it do that in directories with ignored files?

**Comment by AudriusButkevicius** [comment] 2017-08-25 11:20
Because it's trying to reach a target state (sync state) that another node has advertised as current, in order to become in sync.

**Comment by Mannshoch** [comment] 2017-08-25 13:47
I'm not a developper so I'm not able to understand these detail. But In my opinion there is some work needed to get Syncthing usable on phone. 
I would prefer big warning about using the .ignore file on the phone. Now i also understand why I'm not able to edit .ignore from app and has to edit it manual.

**Comment by AudriusButkevicius** [comment] 2017-08-25 13:51
Syncthing works on the phone. Setting up unreasonable ignore patterns on desktop has the same effect, it's just you don't have battery that small on the desktop.

**Comment by Mannshoch** [comment] 2017-08-25 14:07
Would you say I have to send this Issue to /syncthing/syncthing ?

**Comment by AudriusButkevicius** [comment] 2017-08-25 14:26
There is no issue, this is the expected behaviour for the way you've set it up. I'd argue that your setup is wrong, but only you can verify that. You should probably read the docs for ignores to understand the implications of what you are doing.

**Comment by Mannshoch** [comment] 2017-08-25 14:56
As I said I'm not a developer so I'm not able to understand this. Maybe the docs should add such kind of Warning then.

Maybe you could enhance this Sentence:

> Note that ignored files can block removal of an otherwise empty directory. See below for the (?d) prefix to allow deletion of ignored files.

**Comment by AudriusButkevicius** [comment] 2017-08-25 14:58
Well the warning is already there and you've just read it.
I am not sure what you expect to be enhanced,  because from my as a developers perspective, I understand what is being talked about there.

**Comment by Nutomic** [comment] 2017-08-25 15:16
To be honest, I also wouldn't expect this kind of thing to affect battery life. Why can't Syncthing remember that the folder can't be removed due to ignores, instead of retrying it indefinitely?

**Comment by AudriusButkevicius** [comment] 2017-08-25 15:37
Remember where? If you remember, what do you do with the fact you remembered something? At what point do you retry? The retry interval is adjustable, but you will have to retry at some point?

**Comment by Mannshoch** [comment] 2017-08-26 08:33
Could it be that Ignoring a file mean not only to dont transfer it and also mean to dont  watch it like all other sync-able files?

**Comment by Mannshoch** [comment] 2017-08-26 09:18
btw. is ther no such kind of inotify like I had to install on desktop?

**Comment by Mannshoch** [comment] 2017-08-31 08:49
As I said I'm not a developer so I'm not able to understand this. Maybe the docs should add such kind of Warning then.

Maybe you could enhance this Sentence:

> Note that ignored files can block removal of an otherwise empty directory. See below for the (?d) prefix to allow deletion of ignored files.

**Comment by AudriusButkevicius** [comment] 2017-08-31 09:04
What does inotify have to do with this? Android already supports inotify, but it has nothing todo with this issue. The issue happens because you tell us to ignore files which makes them invisible to us, and then ask us to delete directories that contain these ignored files (which look empty to us) yet we can't as it contains the files you told is to ignore. Which means we can never get in sync as we can't delete the directory, so we keep retrying every X seconds to see if you perhaps removed those files yourself which causes the battery drain. There is no other way around it, you need to fix your ignore patterns (by removing them or adding the (?d) prefix to the files you don't mind being deleted), or stop removing directories where you know these files reside. 

I mean, what do you expect us to do? We are asked to do the impossible, remove a directory, yet somehow not touch the files inside it that you told us to ignore.
