### ISSUE TITLE
No new folder form other host alert

### ISSUE THREAD

**Issue by MauroMombelli** [syncthing/syncthing-android#505] opened 2015-11-22 22:14 UTC
When i share a new folder form other host no alert appear. adding folder by ID does not seems to work; the two host see each other connected.

**Comment by AudriusButkevicius** [comment] 2015-11-22 22:16
The prompt is not implemented in android, only in the web ui.

**Comment by MauroMombelli** [comment] 2015-11-22 22:16
even if i launch the web GUI no alert apper

**Comment by Nutomic** [comment] 2015-11-22 22:19
Duplicate of #295.

**Closed by Nutomic** 2015-11-22 22:19 UTC
