### ISSUE TITLE
web UI not showing folders

### ISSUE THREAD

**Issue by tho-gru** [syncthing/syncthing-android#2009] opened 2023-11-15 17:07 UTC
Thanks for providing this great software.

Today I updated (form former version 1.23.7) syncthing on my android device from the f-droid store.

I am German and therefore my mobile phone uses German as primary language.

The update works fine. I can start the app and it looks pretty nice as usual :-) Especially it seems to work: New files are copied to my PC.

But the **web UI** is not working any more. It periodically shows German and English text of the UI but never shows the essential information: No folder information, no device information (local and remote).

***********************************************
![Screenshot_20231115-174028_1](https://github.com/syncthing/syncthing-android/assets/13496906/9485c66f-d2f6-4d82-8f31-8dbbac70ffd5)
***********************************************
![Screenshot_20231115-174029_1](https://github.com/syncthing/syncthing-android/assets/13496906/d53806aa-e402-467e-86da-5b7594f6421b)
***********************************************

The native android UI looks OK. But the web UI simply switches between the languages.

I switched my system language to English: Now the web UI is does not switch the languages but do not work either: Wherever I tap nothing happens. Now Folders appear nor any system is showing up.

### Version Information

    Syncthing-Android-Version: 1.26.0
    Syncthing Version: v1.26.0
    Android Version: Android 14 - Build: UP1A.231005.007

**Comment by tomasz1986** [comment] 2023-11-15 18:00
Probably a duplicate of https://github.com/syncthing/syncthing-android/issues/1995. You can wait for the upcoming v1.26.1 which should fix the issue.

**Closed** 2023-11-15 18:26 UTC
