### ISSUE TITLE
Folder with sharing password crashing app

### ISSUE THREAD

**Issue by pyhedgehog** [syncthing/syncthing-android#1798] opened 2022-06-19 18:37 UTC
### Steps to reproduce

 * Create folder
 * Add password sharing with some device

### Result

App crashing in cycle untill I pause folder

### Expected result

Folder syncs to "untrusted backup".

### Version Information

    App Version: 1.20.2
    Syncthing Version: v1.20.2
    Android Version: Android 12 / OneUI 4.1 / Samsung Galaxy A52

**Comment by tomasz1986** [comment] 2022-06-19 18:45
This is a duplicate of https://github.com/syncthing/syncthing-android/issues/1650. Similar crashes are described there. In sum, until there's proper support for encrypted folders in the Android app, you should be very cautious when trying to use them, and if you do, you should stick to the Web GUI only.

**Comment by AudriusButkevicius** [comment] 2022-06-20 17:38
Closing as duplicate.

**Closed by AudriusButkevicius** 2022-06-20 17:38 UTC
