### ISSUE TITLE
Cannot enable devices in folder edit screen

### ISSUE THREAD

**Issue by Plonq** [syncthing/syncthing-android#647] opened 2016-05-18 09:22 UTC
Steps:

1. Create folder on internal storage
1. Enable all or some of the configured devices
1. Save
1. Go back into folder settings, see that all devices are off
1. Toggle them on again
1. Press back arrow
1. Go back into folder settings, they are off again

Phone model: Sony Z5 Compact
OS: Android 6.0 (build 32.1.A.1.185)

This is my first time using the app, so it's never worked for me. I've double checked the folder is located on internal storage. I currently have two devices configured, neither work.

Devices remain "Disconnected"

Android log:
```
cmIdleTimerMonitor
05-18 19:15:18.214 15869 15886 V GetTask : API call result: {"alloc":8995920,"connectionServiceStatus":{"dynamic+https://relays.syncthing.net/endpoint":{"lanAddresses":["relay://128.199.108.10:22067/?id=QIDAEXG-SEVXHQ3-IHWGLJQ-GKH47RL-SSXDQT7-UBUTD5N-RKAXMFZ-MW5NVQM\u0026pingInterval=1m0s\u0026networkTimeout=2m0s\u0026sessionLimitBps=0\u0026globalLimitBps=0\u0026statusAddr=:22070\u0026providedBy=nutomic"],"wanAddresses":["relay://128.199.108.10:22067/?id=QIDAEXG-SEVXHQ3-IHWGLJQ-GKH47RL-SSXDQT7-UBUTD5N-RKAXMFZ-MW5NVQM\u0026pingInterval=1m0s\u0026networkTimeout=2m0s\u0026sessionLimitBps=0\u0026globalLimitBps=0\u0026statusAddr=:22070\u0026providedBy=nutomic"]},"tcp://0.0.0.0:22000":{"lanAddresses":["tcp://0.0.0.0:22000"],"wanAddresses":["tcp://0.0.0.0:22000","tcp://118.127.100.57:27382"]}},"cpuPercent":1.0199323148489738,"discoveryEnabled":true,"discoveryErrors":{"global@https://discovery-v6-1.syncthing.net/v2/":"Post https://discovery-v6-1.syncthing.net/v2/: dial tcp [2001:470:28:4d6::5]:443: connect: network is unreachable","global@https://discovery-v6-2.syncthing.net/v2/":"Post https://discovery-v6-2.syncthing.net/v2/: dial tcp [2604:a880:800:10::182:a001]:443: connect: network is unreachable","global@https://discovery-v6-3.syncthing.net/v2/":"Post https://discovery-v6-3.syncthing.net/v2/: dial tcp [2400:6180:0:d0::d9:d001]:443: connect: network is unreachable"},"discoveryMethods":8,"goroutines":56,"myID":"J6Q6CQ4-3E6IIC4-W2LE5ZK-RRKZSVN-CNMUN4Q-32XEIQV-TYPVIVI-XFJHNQQ","pathSeparator":"/","startTime":"2016-05-18T09:11:54.144965801Z","sys":20192380,"themes":["default","dark"],"tilde":"/storage/emulated/0","uptime":204}
05-18 19:15:18.216 15869 15886 V GetTask : Calling Rest API at https://127.0.0.1:8384/rest/system/connections
05-18 19:15:18.222 15869 15886 I DpmTcmClient: RegisterTcmMonitor from: org.apache.http.impl.conn.TcmIdleTimerMonitor
05-18 19:15:18.373 15869 15886 V GetTask : API call result: {"connections":{"BBPKRBS-RQPB6WQ-U43LZJL-NFMW4K4-6LONKEE-JB27XXB-NIPZBBD-NVIDMQR":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":""},"J6Q6CQ4-3E6IIC4-W2LE5ZK-RRKZSVN-CNMUN4Q-32XEIQV-TYPVIVI-XFJHNQQ":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":""},"LYA3WPV-A6K5GN4-NXU5SHA-4HMCFPC-ZMP3N3R-O2LTQCS-2F3CQLZ-D7TBTQ2":{"address":"","at":"0001-01-01T00:00:00Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":""}},"total":{"address":"","at":"2016-05-18T09:15:18.368526443Z","clientVersion":"","connected":false,"inBytesTotal":0,"outBytesTotal":0,"paused":false,"type":""}}
```

(Syncthing log is empty)

**Comment by wweich** [comment] 2016-05-18 11:05
I can confirm that toggling a device in the folder edit is not saved. I just tried to disable a device (the only one I have configured in Android) and after closing the folder settings and opening it again, the device is still enabled.

>Devices remain "Disconnected"

This has nothing the do with sharing folders. Connection is done, even if no folder is shared. So that's another problem.

**Comment by afxgit** [comment] 2016-05-18 19:44
same for me on Galaxy s6 & note 4 running lollipop 5.1.1

**Comment by afxgit** [comment] 2016-05-18 19:55
I'm not sure if related to the original issue but same symptoms for me trying to select upnp on devices mentioned above.

**Closed** 2016-05-19 02:44 UTC
Labels: bug

**Comment by xhabih** [comment] 2016-05-22 08:59
Same problem here, with Android 5.1

**Comment by bentrop** [comment] 2016-05-22 14:50
Same issue on Moto X Play with Android 6.0.1. No notification that the Android device is attempting to share a folder with them on the other devices either. This makes sharing folders from Android quite difficult.

**Comment by Nutomic** [comment] 2016-05-23 06:59
The issue is already fixed. I will release a new version in the next days.

**Comment by rodolf0** [comment] 2016-06-01 16:18
hey @Nutomic did you get a chance to push that version?

**Comment by Nutomic** [comment] 2016-06-01 16:24
@rodolf0 The F-Droid build was disabled, but the new version should be there tomorrow.

**Comment by rodolf0** [comment] 2016-06-04 12:29
Latest version I see is 0.7.18 updated on May 17th, 2016.

**Comment by Nutomic** [comment] 2016-06-04 20:45
@rodolf0 The new version is definitely on F-Droid. Did you update your repo?

**Comment by bentrop** [comment] 2016-06-04 20:53
When will it be propagated to the Play Store?

The Play Store build is still at 0.7.18 and given that this a bug that is impacting the user experience rather significantly, wouldn't it make sense to also quickly push the fixed build to the place that is reaching the widest audience?

**Comment by Nutomic** [comment] 2016-06-04 21:54
Damn I wasn't aware that the Google Play update was also not published. I'm on it now.

**Comment by Nutomic** [comment] 2016-06-04 22:03
0.7.19 is on Google Play now!

**Comment by rodolf0** [comment] 2016-06-05 13:21
Oh I was referring to the Google play version from the beginning, sorry for
the lack of context. I see the new version now, thanks!

On Sat, 4 Jun 2016, 23:03 Felix Ableitner, <notifications@github.com> wrote:

> 0.7.19 is on Google Play now!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/syncthing/syncthing-android/issues/647#issuecomment-223780709>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATHLTWIIsN0VpvEyHHE7auRVAewQHyUks5qIfY8gaJpZM4IhFcO>
> .
>
-- 
- Rodolfo
