### ISSUE TITLE
Request/enhancement: "Save to Syncthing" option in system Share menu when Syncthing is disabled

### ISSUE THREAD

**Issue by kotep** [syncthing/syncthing-android#1790] opened 2022-05-16 04:57 UTC
Current behavior:
If Syncthing Android's run conditions have currently disabled Syncthing (e.g. I am not connected to wifi) and I try to share a file through Android's share menu I get this error message:
<img src="https://user-images.githubusercontent.com/7033407/168518005-ea249654-99ad-4701-aa2a-9e67bbcbb22b.png" width=50% height=50%>
"Exit" will cancel the operation entirely, while "Change Settings" takes me to the Run Conditions setting page.

Desired behavior: 
I want to be able to save a file to the local Syncthing folder . I don't know of any Android system-specific reason why that wouldn't be possible. Syncthing already has its persistent notification running, and it's just putting a file in a directory it already has permissions for. I can accomplish the same result by moving the file manually in my file browser to the appropriate folder, but that requires more steps and isn't available from the share menu like Save to Syncthing.

My ideal UI for this would be something like this:
<img src="https://user-images.githubusercontent.com/7033407/168521146-83da409a-9fde-4f5d-a9ee-2c52344a31e3.png" width=50% height=50%>
This could come with a control in Settings/Behavior like "Always Save to Syncthing while disabled" with a description like "Suppresses warning message when adding files via Share menu".

For a simpler implementation, the checkbox in the modal and its corresponding entry in Settings could be omitted. Just having a third button for "Save Anyway" would be a large improvement in usability.

**Comment by tomasz1986** [comment] 2022-05-16 05:25
This is a duplicate of https://github.com/syncthing/syncthing-android/issues/1329.

**Closed** 2022-05-16 06:21 UTC
