### ISSUE TITLE
Just start syncthing if I'm sharing to it and it's not started

### ISSUE THREAD

**Issue by julian-klode** [syncthing/syncthing-android#1659] opened 2021-05-25 10:03 UTC
A lot of times, when I share to Syncthing, it gives me a popup saying that Syncthing is not running and gives me options to change settings when to run it, or to exit it. That's absurd behavior, because then I have to go to the launcher and launch syncthing and do the share dance again.

The expected behavior here is 

- to start Syncthing in case it's not running yet, but should be
- the sharing action to _always_ work. At least copy the file into the browser and make sure Syncthing will be started on a network change.

### Version Information

    App Version: 1.16.0
    Syncthing Version: v1.16.0
    Android Version: Android 11 (May 2021, Pixel 4a)

**Comment by imsodin** [comment] 2021-05-25 10:14
Duplicate of https://github.com/syncthing/syncthing-android/issues/1329

**Closed by imsodin** 2021-05-25 10:14 UTC
